(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["General`Matrices`",
{"Global`",
"SpinDynamica`",
"General`UserLevel`",
"General`General3D`",
"General`Miscellaneous`"}
]


(* ::Input::Initialization:: *)
DiagonalElements::usage=
	"DiagonalElements[mat] has been superseded by Diagonal";


(* ::Input::Initialization:: *)
DirectProduct::usage=
	"DirectProduct[m1,m2] generates direct product of
	matrices m1 \!\(\[CircleTimes]\) m2.\n
	DirectProduct[v1,m2] generates direct product of row vector v1 and matrix m2.\n
		DirectProduct[m1,v2] generates direct product of matrix m1 and row vector v2.\n
		DirectProduct[v1,v2] generates direct product of row vector v1 and row vector v2.\n
		DirectProduct[a,b,c..] takes many pairwise direct products in sequence, i.e. a \!\(\[CircleTimes]\) b \!\(\[CircleTimes]\) c";


(* ::Input::Initialization:: *)
Adjoint::usage=
	"Adjoint[m] generates the adjoint of m.";


(* ::Input::Initialization:: *)
DyadicProduct::usage=
	"DyadicProduct[v1,v2] generates dyadic product of two vectors";
	


(* ::Input::Initialization:: *)
NDiagonalize::usage="NDiagonalize[mat,opts] returns the form {X,evals,Xinv} where X is the matrix whose columns are the normalized eigenvectors of mat, and Xinv is the inverse of X. The option Assumptions\[Rule]{OrthogonalEigenvectors\[Rule]True} may be used to allow the use of ConjugateTranspose to invert X.

The syntax NDiagonalize[superop,opbasis,basis,opts] causes a superoperator to be converted into diagonalized form in the operator basis opbasis and state basis basis (explicit specification of these bases is optional). The option Assumptions may be used with NDiagonalize when it is applied to a superoperator. If Assumptions\[Rule]Automatic, the setting of SuperoperatorType determines whether assumptions of the type Assumptions\[Rule]{OrthogonalEigenvectors\[Rule]True} are used.

The syntax NDiagonalize[op,basis,opts] causes an operator to be converted into diagonalized form in the Hilbert basis (specification of this is optional). The option Assumptions may be used with NDiagonalize when it is applied to an operator. If Assumptions\[Rule]Automatic, the setting of OperatorType determines whether assumptions of the type Assumptions\[Rule]{OrthogonalEigenvectors\[Rule]True} are used.";


(* ::Input::Initialization:: *)
OrthogonalEigenvectors::usage="An assumption of the form Assumptions\[Rule]{OrthogonalEigenvectors\[Rule]True} may be used in NDiagonalize to allow the use of ConjugateTranspose to invert the eigenvector matrix.";


(* ::Input::Initialization:: *)
HermitianQ::usage=
	"HermitianQ[mat] tests whether a matrix is Hermitian.";
	


(* ::Input::Initialization:: *)
AntiHermitianQ::usage=
	"AntiHermitianQ[mat] tests whether a matrix is AntiHermitian.";
	


(* ::Input::Initialization:: *)
NormalQ::usage=
	"NormalQ[mat] tests whether a matrix is Hermitian.";
	


(* ::Input::Initialization:: *)
UnitaryQ::usage=
	"UnitaryQ[mat] tests whether a matrix is Unitary.";
	


(* ::Input::Initialization:: *)
OrthogonalQ::usage=
	"OrthogonalQ[mat] tests whether a matrix has orthogonal rows and columns.";
	


(* ::Input::Initialization:: *)
OrthonormalQ::usage=
	"OrthonormalQ[mat] tests whether a matrix has orthonormal rows and columns.";
	


(* ::Input::Initialization:: *)
EigensystemQ::usage=
	"EigensystemQ[{evals,evecs},mat] tests whether a set of eigenvalues and evectors really are an appropriate set for the given matrix.";
	


(* ::Input::Initialization:: *)
CommuteQ::usage=
	"CommuteQ[mat1,mat2] tests whether two matrices commute.";
	


(* ::Input::Initialization:: *)
DiagonalQ::usage=
	"DiagonalQ[mat1] tests whether a matrix is diagonal.";
	


(* ::Input::Initialization:: *)
NumericMatrixQ::usage=
	"NumericMatrixQ[mat] returns True if mat is a matrix with numerical elements, and False otherwise.";
	


(* ::Input::Initialization:: *)
If[$VersionNumber<13.1,
(BlockDiagonalMatrix::usage="BlockDiagonalMatrix[{mat1,mat2..}] or BlockDiagonalMatrix[mat1,mat2..] constructs a block-diagonal square matrix out of the given square blocks."
	)
	];


(* ::Input::Initialization:: *)
SetOffDiagonalElementsToZero::usage=
	"SetOffDiagonalElementsToZero[mat,func] sets off-diagonal elements of the square matrix mat to zero, in the case that func[r,c] yields True, where r and c are the row and column indices. The diagonal elements are left untouched.\n
	SetOffDiagonalElementsToZero[mat] sets all off-diagonal elements to zero.";
	


(* ::Input::Initialization:: *)
MultiplyMatricesAndMatrixInterpolationFunctions::usage=
	"MultiplyMatricesAndMatrixInterpolationFunctions[mat1,mat2..] multiplies compatible matrices together. Any argument may also be an InterpolationFunction which evaluates to a matrix.";
	


(* ::Input::Initialization:: *)
SumMatricesAndMatrixInterpolationFunctions::usage=
	"SumMatricesAndMatrixInterpolationFunctions[mat1,mat2..] adds compatible matrices together. Any argument may also be an InterpolationFunction which evaluates to a matrix.";
	


(* ::Input::Initialization:: *)
MultiplyMatricesAndVectorInterpolationFunctions::usage=
	"MultiplyMatricesAndVectorInterpolationFunctions[mat1,mat2,..vec] multiplies compatible matrices and a vector together. Intelligent ordering of products is used to achieve numerical efficiency. Any argument may also be an InterpolationFunction which evaluates to a matrix or a vector.";
	


(* ::Input::Initialization:: *)
OptimalBipartiteGraphMatching::usage=
	"OptimalBipartiteGraphMatching is SpinDynamica's implementation of the Hungarian Algorithm for optimal assignment problems on a bipartite graph. 
Consider the following practical problem: Workers W1, W2, W3 and W4, etc. together have to fulfill jobs A, B, C and D, etc. 
Eacher worker ranks his preference with regard to which job he would like to perform. 
What is the best assignment of jobs as to maximize the satisfaction of each worker? For such cases the Hungarian Algorithm provides an optimal solution. 

In general given a complete weighted Bipartite Graph K(n,n), the Hungarian Algorithm provides an optimal solution. 
OptimalBipartiteGraphMatching assumes the Bipartite Graph K(n,n) to be arranged into a M(n,n) matrix, 
where columns represent the vertices of the set U and rows the vertices of the set V. The matrix-element M_{i,j} is the edge-weight connecting vertices i and j.
OptimalBipartiteGraphMatching returns a permutation sequence. Application of the permutation sequence to the columns of M leads to a minimization of the Trace, 
which is equivalent to an optimal assignment.";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
DirectProduct[matA_?MatrixQ,matB_?MatrixQ]:=
	Flatten[#,1]& @
		Map[
			Function[arow,
				Map[
					Function[brow,
						Flatten[#,2]&@{ 
							Map[
								Function[acol,		
									acol*brow
								],
								arow
							] 
						}
					],
					matB
				]
			],
			matA
		]


(* ::Input::Initialization:: *)
DirectProduct[matA_?MatrixQ,vecB_List]:=
	DirectProduct[matA,{vecB}]


(* ::Input::Initialization:: *)
DirectProduct[vecA_List,matB_?MatrixQ]:=
	DirectProduct[{vecA},matB]


(* ::Input::Initialization:: *)
DirectProduct[vecA_List,vecB_List]:=
	Flatten[#,1]& @DirectProduct[{vecA},{vecB}]


(* ::Input::Initialization:: *)
DirectProduct[a_]:=a;


(* ::Input::Initialization:: *)
DirectProduct[a_, b_, c__]:=
Fold[DirectProduct,a,{b,c}]


(* ::Input::Initialization:: *)
Adjoint[a_+b__]:=Adjoint[a]+Adjoint[Plus[b]];


(* ::Input::Initialization:: *)
Adjoint[Times[a_,b__]]:=Adjoint[a]*Adjoint[Times[b]];


(* ::Input::Initialization:: *)
Adjoint[sa_SparseArray]/;MatrixQ[sa]:=
	Transpose@SparseArray[
ArrayRules[sa]/.{(a_->b_):>(a->ComplexExpand@Conjugate[b]),(a_:>b_):>(a:>ComplexExpand@Conjugate[b])},
Dimensions[sa]
];


(* ::Input::Initialization:: *)
Adjoint[sa_SparseArray]/;VectorQ[sa]:=
SparseArray[
ArrayRules[sa]/.{(a_->b_):>(a->ComplexExpand@Conjugate[b]),(a_:>b_):>(a:>ComplexExpand@Conjugate[b])},
Dimensions[sa]
];


(* ::Input::Initialization:: *)
Adjoint[m_?MatrixQ]:=
	ComplexExpand@Conjugate[Transpose[m]];


(* ::Input::Initialization:: *)
Adjoint[m_?NumericQ]:=
	ComplexExpand@Conjugate[m];


(* ::Input::Initialization:: *)
Adjoint[v_List]:=
	ComplexExpand@Conjugate[v];


(* ::Input::Initialization:: *)
Adjoint[(f:(Cos|Sin|Tan))[x__]]:=ComplexExpand@Conjugate[f[x]];


(* ::Input::Initialization:: *)
Adjoint[num_?NumericQ]:=ComplexExpand@Conjugate[num];


(* ::Input::Initialization:: *)
Adjoint[symbol_Symbol]:=ComplexExpand@Conjugate[symbol];


(* ::Input::Initialization:: *)
Adjoint[Conjugate[symbol_Symbol]]:=ComplexExpand@symbol;


(* ::Input::Initialization:: *)
Adjoint[Conjugate[(f:Sin|Cos|Tan)[symbol_Symbol]]]:=f[symbol];


(* ::Input::Initialization:: *)
Adjoint[Exp[op_]]:=Exp[Adjoint[op]];
Adjoint[Power[E,op_]]:=Exp[Adjoint[op]]


(* ::Input::Initialization:: *)
DyadicProduct[v1_List,v2_List]:=
	DirectProduct[Map[List,v1],v2];


(* ::Input::Initialization:: *)
Options[NDiagonalize]={Assumptions->Automatic};


(* ::Input::Initialization:: *)
NDiagonalize[mat_?NumericMatrixQ,opts___Rule]:=Module[{evals,evecs,X,Xinv,ass,orthogevecs,degevals,degevalpositions},(
ass=Assumptions/.{opts}/.Options[NDiagonalize];
orthogevecs=
Switch[ass,
None|False|Automatic,False,
_Rule|{_Rule...},
	OrthogonalEigenvectors/.Flatten[{ass,OrthogonalEigenvectors->False}],
_,False
];
{evals,evecs}=Eigensystem[If[Length[mat]>=256,N@Normal@mat,N@mat]];
If[orthogevecs,
(degevals=First/@Select[Tally[evals,(Chop[#1-#2]==0)&],(Last[#]>1)&];
degevalpositions=(Flatten@Position[Chop[evals-#],0])&/@degevals;
evecs=ReplacePart[evecs,Flatten[MapThread[Rule,{#,Orthogonalize[evecs[[#]]]}]&/@degevalpositions]]
)
];
X=SparseArray@Chop@Transpose[Normalize/@evecs];
Xinv=If[orthogevecs,
ConjugateTranspose[X],
(If[Chop@Det[X]==0,
(Message[NDiagonalize::sing];$Failed),
SparseArray@Inverse[X]]
)];
Switch[Xinv,
_Inverse|_PseudoInverse,(Message[NDiagonalize::fail];$Failed),
_,{X,evals,Xinv}
]
)];


(* ::Input::Initialization:: *)
NDiagonalize[mat_?MatrixQ,opts___Rule]:=(Message[NDiagonalize::notnummat];$Failed);


(* ::Input::Initialization:: *)
NDiagonalize::fail="Cannot invert the matrix of eigenvectors, possibly because the matrix is singular.";


(* ::Input::Initialization:: *)
NDiagonalize::notnummat="NDiagonalize cannot be applied to a non-numeric matrix. Check that all symbols have numeric values.";


(* ::Input::Initialization:: *)
NDiagonalize::sing="The matrix of eigenvectors cannot be inverted, because it is singular. Diagonalization has failed.";


(* ::Input::Initialization:: *)
HermitianQ[X_?MatrixQ]:=
Chop@ComplexExpand@N@Normal[Adjoint[X]-X]==DiagonalMatrix[Table[0,{Length[X]}] ]


(* ::Input::Initialization:: *)
AntiHermitianQ[X_?MatrixQ]:=
Chop@ComplexExpand@N@Normal[Adjoint[X]+X]==DiagonalMatrix[Table[0,{Length[X]}] ]


(* ::Input::Initialization:: *)
UnitaryQ[X_?MatrixQ]:=
Chop@ComplexExpand@N@Normal[Adjoint[X] . X]==Chop@ComplexExpand@N@Normal[X . Adjoint[X]]==DiagonalMatrix[Table[1,{Length[X]}] ]


(* ::Input::Initialization:: *)
NormalQ[X_?MatrixQ]:=
(Union@Flatten@Chop@ComplexExpand@N@Normal[X+ConjugateTranspose@X]=={0})||
(Union@Flatten@Chop@ComplexExpand@N@Normal[X-ConjugateTranspose@X]=={0})||
(Chop@ComplexExpand@N[Plus@@((Abs[#]^2)&/@Eigenvalues[X])-Plus@@((Abs[#]^2)&/@Flatten[X])]==0);



(* ::Input::Initialization:: *)
OrthogonalQ[X_?MatrixQ]:=
Module[{mat},(
mat=Chop@Outer[(Conjugate[#1] . #2)&,X,X,1];
(mat== DiagonalMatrix[Diagonal[mat]])
)]


(* ::Input::Initialization:: *)
OrthonormalQ[X_?MatrixQ]:=
Chop@Outer[(Conjugate[#1] . #2)&,X,X,1]== DiagonalMatrix[Table[1,{Length[X]}]];


(* ::Input::Initialization:: *)
EigensystemQ[{evals_List,evecs_?MatrixQ},mat_?MatrixQ]:=
Module[{X,L},(
X=Transpose@evecs;
L=DiagonalMatrix[evals];
Chop[N[mat . X - X . L]]==DiagonalMatrix[Table[0,{Length[evals]}] ]
)]


(* ::Input::Initialization:: *)
CommuteQ[m1_?MatrixQ,m2_?MatrixQ]:=
Module[{},(
(Chop[N[m1 . m2-m2 . m1]]== DiagonalMatrix[Table[0,{Length[m1]}]])
)]


(* ::Input::Initialization:: *)
DiagonalQ[mat_?MatrixQ]:=
Module[{m,n},(
{m,n}=Dimensions[mat];
(m==n)&&
And@@(
(Chop[#]==0)&/@Flatten@Table[ Drop[mat[[r]],{r}], {r,1,Length[mat]}]
)
)]


(* ::Input::Initialization:: *)
NumericMatrixQ[{{_?NumericQ..}..}]=True;


(* ::Input::Initialization:: *)
NumericMatrixQ[sa_SparseArray]/;MatchQ[Last/@ArrayRules@sa,{_?NumericQ..}]=True;


(* ::Input::Initialization:: *)
NumericMatrixQ[_]:=False


(* ::Input::Initialization:: *)
If[$VersionNumber<13.1,(BlockDiagonalMatrix[args___]/;!FreeQ[{args},$Failed]:=$Failed)
];


(* ::Input::Initialization:: *)
If[$VersionNumber<13.1,(
BlockDiagonalMatrix[mat1_?MatrixQ,mats___?MatrixQ]:=BlockDiagonalMatrix[{mat1,mats}]
)];


(* ::Input::Initialization:: *)
If[$VersionNumber<13.1,(
BlockDiagonalMatrix[{mat1_?MatrixQ,more___}]/;!MatchQ[Dimensions[mat1],{dim_,dim_}]:=(Message[BlockDiagonalMatrix::notsq];$Failed)
)];


(* ::Input::Initialization:: *)
If[$VersionNumber<13.1,(
BlockDiagonalMatrix[{mat1_?MatrixQ}]/;MatchQ[Dimensions[mat1],{dim_,dim_}]:=mat1)];


(* ::Input::Initialization:: *)
If[$VersionNumber<13.1,(
BlockDiagonalMatrix[{mat1_?MatrixQ,mat2_?MatrixQ,more___}]/;!MatchQ[Dimensions[mat2],{dim_,dim_}]:=(Message[BlockDiagonalMatrix::notsq];$Failed)
)];


(* ::Input::Initialization:: *)
If[$VersionNumber<13.1,(
BlockDiagonalMatrix[{mat1_?MatrixQ,mat2_?MatrixQ,mats__?MatrixQ}]:=
BlockDiagonalMatrix[{BlockDiagonalMatrix[{mat1,mat2}],mats}]
)];


(* ::Input::Initialization:: *)
If[$VersionNumber<13.1,(
BlockDiagonalMatrix[{mat1_?MatrixQ,mat2_?MatrixQ}]:=
Module[{n1,n2},(
{n1,n2}=Length/@{mat1,mat2};
If[MatchQ[Head[mat1],SparseArray]||MatchQ[Head[mat2],SparseArray],
SparseArray[#],#]&@
Join[
Join[#,Table[0,{n2}]]&/@mat1,
Join[Table[0,{n1}],#]&/@mat2
]
)]
)];


(* ::Input::Initialization:: *)
If[$VersionNumber<13.1,(
BlockDiagonalMatrix::notsq="All arguments of BlockDiagonalMatrix must be square matrices."
)];


(* ::Input::Initialization:: *)
SetOffDiagonalElementsToZero[mat_?MatrixQ]:=SetOffDiagonalElementsToZero[mat,True&]/;Equal@@Dimensions[mat]


(* ::Input::Initialization:: *)
SetOffDiagonalElementsToZero[mat_?MatrixQ,func_]:=
Module[{n},(
n=First@Dimensions[mat];
ReplacePart[mat,
DeleteCases[
Position[Table[func[r,c],{r,1,n},{c,1,n}],True],
{r_,r_}
]->0
]
)]/;Equal@@Dimensions[mat]



(* ::Input::Initialization:: *)
MultiplyMatricesAndMatrixInterpolationFunctions[mat1_]:=mat1;


(* ::Input::Initialization:: *)
MultiplyMatricesAndMatrixInterpolationFunctions[matrices:(_?MatrixQ..)]:=Dot[matrices];


(* ::Input::Initialization:: *)
MultiplyMatricesAndMatrixInterpolationFunctions[mat1_,mat2_,more__]:=MultiplyMatricesAndMatrixInterpolationFunctions[MultiplyMatricesAndMatrixInterpolationFunctions[mat1,mat2],more];


(* ::Input::Initialization:: *)
MultiplyMatricesAndMatrixInterpolationFunctions[mat1_?MatrixQ,mat2_?MatrixQ]:=SparseArray[mat1 . mat2];


(* ::Input::Initialization:: *)
MultiplyMatricesAndMatrixInterpolationFunctions[ifunc_InterpolatingFunction[t_],mat_?MatrixQ]/;(Depth[ifunc]>=3)&&
MatchQ[ifunc[ifunc[[1,1,1]]],_?MatrixQ]:=
Replace[ifunc,{m_?MatrixQ:>SparseArray@Simplify[m . mat]},{3}][t];


(* ::Input::Initialization:: *)
MultiplyMatricesAndMatrixInterpolationFunctions[mat_?MatrixQ,ifunc_InterpolatingFunction[t_]]/;(Depth[ifunc]>=3)&&
MatchQ[ifunc[ifunc[[1,1,1]]],_?MatrixQ]:=
Replace[ifunc,{m_?MatrixQ:>SparseArray[mat . m]},{3}][t];


(* ::Input::Initialization:: *)
MultiplyMatricesAndMatrixInterpolationFunctions[ifunc1_InterpolatingFunction[t_],ifunc2_InterpolatingFunction[t_]]/;
(Depth[ifunc1]>=3)&&
MatchQ[ifunc1[ifunc1[[1,1,1]]],_?MatrixQ]&&
(Depth[ifunc2]>=3)&&
MatchQ[ifunc2[ifunc2[[1,1,1]]],_?MatrixQ]&&
MatchQ[First@ifunc1,First@ifunc2]:=
Module[{interptimes},(
interptimes=Sort@Union[ifunc1[[3,1]],ifunc1[[3,2]]];
Interpolation[SparseArray[ifunc1[#] . ifunc2[#]]&/@interptimes][t]
)];


(* ::Input::Initialization:: *)
SumMatricesAndMatrixInterpolationFunctions[mat1_]:=mat1;


(* ::Input::Initialization:: *)
SumMatricesAndMatrixInterpolationFunctions[matrices:(_?MatrixQ..)]:=Plus[matrices];


(* ::Input::Initialization:: *)
SumMatricesAndMatrixInterpolationFunctions[mat1_,mat2_,more__]:=SumMatricesAndMatrixInterpolationFunctions[SumMatricesAndMatrixInterpolationFunctions[mat1,mat2],more];


(* ::Input::Initialization:: *)
SumMatricesAndMatrixInterpolationFunctions[mat1_?MatrixQ,mat2_?MatrixQ]:=SparseArray[mat1+mat2];


(* ::Input::Initialization:: *)
SumMatricesAndMatrixInterpolationFunctions[ifunc_InterpolatingFunction[t_],mat_?MatrixQ]/;(Depth[ifunc]>=3)&&
MatchQ[ifunc[ifunc[[1,1,1]]],_?MatrixQ]:=
Replace[ifunc,{m_?MatrixQ:>SparseArray@Simplify[m+mat]},{3}][t];


(* ::Input::Initialization:: *)
SumMatricesAndMatrixInterpolationFunctions[mat_?MatrixQ,ifunc_InterpolatingFunction[t_]]:=SumMatricesAndMatrixInterpolationFunctions[ifunc[t],mat]


(* ::Input::Initialization:: *)
SumMatricesAndMatrixInterpolationFunctions[ifunc1_InterpolatingFunction[t_],ifunc2_InterpolatingFunction[t_]]/;
(Depth[ifunc1]>=3)&&
MatchQ[ifunc1[ifunc1[[1,1,1]]],_?MatrixQ]&&
(Depth[ifunc2]>=3)&&
MatchQ[ifunc2[ifunc2[[1,1,1]]],_?MatrixQ]&&
MatchQ[First@ifunc1,First@ifunc2]:=
Module[{interptimes},(
interptimes=Sort@Union[ifunc1[[3,1]],ifunc1[[3,2]]];
Interpolation[SparseArray[ifunc1[#]+ifunc2[#]]&/@interptimes][t]
)];


(* ::Input::Initialization:: *)
MultiplyMatricesAndVectorInterpolationFunctions[vec_]:=vec;


(* ::Input::Initialization:: *)
MultiplyMatricesAndVectorInterpolationFunctions[mats1__,mat2_,vec_]:=MultiplyMatricesAndVectorInterpolationFunctions[mats1,
MultiplyMatricesAndVectorInterpolationFunctions[mat2,vec]
];


(* ::Input::Initialization:: *)
MultiplyMatricesAndVectorInterpolationFunctions[mat_?MatrixQ,vec_?VectorQ]:=SparseArray[mat . vec];


(* ::Input::Initialization:: *)
MultiplyMatricesAndVectorInterpolationFunctions[ifunc_InterpolatingFunction[t_],vec_?VectorQ]/;(Depth[ifunc]>=3)&&
MatchQ[ifunc[ifunc[[1,1,1]]],_?MatrixQ]:=
Replace[ifunc,{m_?MatrixQ:>SparseArray@Simplify[m . vec]},{3}][t];


(* ::Input::Initialization:: *)
MultiplyMatricesAndVectorInterpolationFunctions[mat_?MatrixQ,ifunc_InterpolatingFunction[t_]]/;(Depth[ifunc]>=3)&&
MatchQ[ifunc[ifunc[[1,1,1]]],_?VectorQ]:=
Replace[ifunc,{v_?VectorQ:>SparseArray[mat . v]},{3}][t];


(* ::Input::Initialization:: *)
MultiplyMatricesAndVectorInterpolationFunctions[ifunc1_InterpolatingFunction[t_],ifunc2_InterpolatingFunction[t_]]/;
(Depth[ifunc1]>=3)&&
MatchQ[ifunc1[ifunc1[[1,1,1]]],_?MatrixQ]&&
(Depth[ifunc2]>=3)&&
MatchQ[ifunc2[ifunc2[[1,1,1]]],_?VectorQ]&&
MatchQ[First@ifunc1,First@ifunc2]:=
Module[{interptimes},(
interptimes=Sort@Union[ifunc1[[3,1]],ifunc1[[3,2]]];
Interpolation[SparseArray[ifunc1[#] . ifunc2[#]]&/@interptimes][t]
)];


(* ::Input::Initialization:: *)
OptimalBipartiteGraphMatching[mat_]:=Module[{done,dim,zpset,rcoverc,ccoverc,zstarset,zpi,zpj,zstari,zstarj,matblock,newmin,newzeropos,matMR,zmat,colset,rowset,zeroset,rpos,zpos,cpos,zptrack,zstartrack,rcover,findstarredzeroinrow,finduncoveredzero,minR},
matMR=mat;
dim=Length[matMR];
colset=Range[dim];
rowset=colset;
$RecursionLimit=\[Infinity];
rcoverc=rowset;
ccoverc=colset;
zstarset={};
zpset={};
{zpi,zpj}={0,0};
matblock={};
newmin={};
newzeropos={};
OptimalBipartiteGraphMatching["step1"]:=(
minR=Min[#]&/@matMR;
matMR=Chop[matMR-minR];
OptimalBipartiteGraphMatching["step2"];
);
OptimalBipartiteGraphMatching["step2"]:=
(
zmat=matMR/.{0-> 1,x_/;x!=0-> 0};
zeroset=Position[zmat,1];
While[rowset!={},
rpos=First[rowset];
zpos=First@FirstPosition[zmat[[rpos,colset]],1];
If[IntegerQ[zpos],
cpos=colset[[zpos]];
colset=DeleteCases[colset,cpos];
rowset=Complement[rowset,Flatten[Position[zmat[[All,cpos]],1]]];
AppendTo[zstarset,Join[{rpos},{cpos}]],
rowset=DeleteCases[rowset,rpos];
];
];
{zstari,zstarj}=First[zstarset];
OptimalBipartiteGraphMatching["step3"];
);
OptimalBipartiteGraphMatching["step3"]:=(
ccoverc=Complement[ccoverc,zstarset[[All,2]]];
If[MatchQ[ccoverc,{}],
done=True;
zstarset,
OptimalBipartiteGraphMatching["step4"];
]
);
OptimalBipartiteGraphMatching["step4"]:=(
done=False;
While[!MatchQ[done, True],
If[MatchQ[#,{_,_}],
{zpi,zpj}=({rcoverc[[#1]],ccoverc[[#2]]}&@@#);
AppendTo[zpset,{zpi,zpj}];,
done=True;
OptimalBipartiteGraphMatching["step6"];
]&@finduncoveredzero[];
If[MatchQ[#,{0,0}],
done=True;
OptimalBipartiteGraphMatching["step5"];,
{zstari,zstarj}=#;
rcoverc=DeleteCases[rcoverc,zstari];
ccoverc=Union[ccoverc,{zstarj}];
]&@(If[MatchQ[#,{_,_}],#,{0,0}]&@findstarredzeroinrow[]);
]
);
OptimalBipartiteGraphMatching["step5"]:=(
zstartrack={};
zptrack={};
AppendTo[zptrack,Last[zpset]];
AppendTo[zstartrack,FirstCase[zstarset,{_,Last[zptrack][[2]]}]];
While[MatchQ[Last[zstartrack],{_,_}],
AppendTo[zptrack,FirstCase[zpset,{Last[zstartrack][[1]],_}]];
AppendTo[zstartrack,FirstCase[zstarset,{_,Last[zptrack][[2]]}]];
];
zstarset=zstarset/.Thread[zstartrack-> Nothing];
zstarset=Join[zstarset,zptrack];
zpset={};
zptrack={};
zstartrack={};
rcoverc=Range[dim];
ccoverc=Range[dim];
OptimalBipartiteGraphMatching["step3"];
);
OptimalBipartiteGraphMatching["step6"]:=(
rcover=Complement[Range[dim],rcoverc];
matblock=matMR[[rcoverc,ccoverc]];
newmin=Min[matblock];
matMR[[rcover]]=Chop[matMR[[rcover]]+newmin];
matMR[[All,ccoverc]]=Chop[matMR[[All,ccoverc]]-newmin];
OptimalBipartiteGraphMatching["step4"];
);
findstarredzeroinrow[]:=FirstCase[zstarset,{zpi,_}];
finduncoveredzero[]:=FirstPosition[matMR[[rcoverc,ccoverc]],0];
OptimalBipartiteGraphMatching["step1"];
$RecursionLimit=1024;
Sort[zstarset][[All,2]]
]


(* ::Input::Initialization:: *)
End[];
EndPackage[];
