(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["General`UserLevel`", 
{"Global`",
"SpinDynamica`" 
}
];


(* ::Input::Initialization:: *)
SetUserLevel::usage="SetUserLevel[n] sets the user level of SpinDynamica. The minimum user level of 1 implements a high degree of error trapping and reporting, but may have a slow execution speed for some routines. High user levels have fewer syntax checks and error traps, but run faster.";


(* ::Input::Initialization:: *)
UserLevel::usage="UserLevel[] returns the current UserLevel of SpinDynamica. The minimum user level of 1 implements a high degree of error trapping and reporting, but may have a slow execution speed for some routines. High user levels have fewer syntax checks and error traps, but run faster.";


(* ::Input::Initialization:: *)
MaximumUserLevel::usage="MaximumUserLevel is the maximum allowable user level for the current SpinDynamica version.";


(* ::Input::Initialization:: *)
MinimumRecommendedUserLevel::usage="MinimumRecommendedUserLevel is an option setting for some SpinDynamica routines which indicates the minimum recommended user level for that routine.";


(* ::Input::Initialization:: *)
UserLevelDependentDefinition::usage="UserLevelDependentDefinition is used internally by SpinDynamica. UserLevelDependentDefinition[symb,level,code] sets up definitions associated with symb which are only active when the UserLevel is given by level or below. These definitions are inactivated when the UserLevel is set higher than level.";


(* ::Input::Initialization:: *)
UserLevelDependentDefinitions::usage="UserLevelDependentDefinitions is used internally by SpinDynamica. UserLevelDependentDefinitions[symb,level] returns the definitions associated with symb which are only active when the UserLevel is given by level or below. These definitions are inactivated when the UserLevel is set higher than level. UserLevelDependentDefinitions[symb,{level}]  returns all definitions for symb active at user level level and above, and UserLevelDependentDefinitions[symb] returns all definitions for symb active in the current user level environment. ";


(* ::Input::Initialization:: *)
UserLevelDependentSymbols::usage="UserLevelDependentSymbols is used internally by SpinDynamica. UserLevelDependentSymbols[level] lists the symbols which possess user-level-dependent definitions at the user level given by level. UserLevelDependentSymbols[{level}] lists all symbols which possess user-level-dependent definitions at all levels higher and equal to level. UserLevelDependentSymbols[] lists all symbols with currently active user-level-dependent definitions.";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
MaximumUserLevel=3;


(* ::Input::Initialization:: *)
Options[UserLevel]={UserLevel->Undefined};


(* ::Input::Initialization:: *)
UserLevel[opts___Rule]:=UserLevel/.{opts}/.Options[UserLevel];


(* ::Input::Initialization:: *)
UserLevel::badul="The user level must be an integer between 1 and `1`."; 


(* ::Input::Initialization:: *)
UserLevel::toolow="A user level of `2` is recommended for this calculation. The current user level of `1` is too low. Execution speed may be slow. Set a higher user level using SetUserLevel[..]."; 


(* ::Input::Initialization:: *)
Options[SetUserLevel]={};


(* ::Input::Initialization:: *)
SetUserLevel[Infinity,opts___Rule]:=SetUserLevel[MaximumUserLevel,opts];


(* ::Input::Initialization:: *)
SetUserLevel[ul_,opts___Rule]/;(!IntegerQ[ul])||ul<1||ul>MaximumUserLevel:=
(Message[UserLevel::badul,MaximumUserLevel];
$Failed);


(* ::Input::Initialization:: *)
SetUserLevel[ul_,opts___Rule]/;MatchQ[ul,UserLevel[opts]]:=(Message[SetUserLevel::nochge,ul];
UserLevel[]);


(* ::Input::Initialization:: *)
SetUserLevel[ul_,opts___Rule]:=
Module[{ulstodelete,ulstoimplement},(
SetOptions[UserLevel,UserLevel->ul];
DeleteUserLevelDependentDefinitions[];
ImplementUserLevelDependentDefinitions@Range[ul,MaximumUserLevel];
If[$KernelID==0,
(Switch[ul,
1,Message[SetUserLevel::minul,MaximumUserLevel],
MaximumUserLevel,Message[SetUserLevel::maxul, ul],
_,Message[SetUserLevel::ul, ul]
];
Message[SetUserLevel::modsymbs,
Select[
UserLevelDependentSymbols[{ul}],
MemberQ[Attributes[#],Protected]&
]
])
];
If[$KernelID==0&&$KernelCount>0,
ParallelEvaluate[Quiet@SetUserLevel[ul]]
];
UserLevel[]
)
];


(* ::Input::Initialization:: *)
SetUserLevel::ini="The user level is being initialized to `1`. The user level may be set to an integer between 1 and `2` by using SetUserLevel[level]. Low user levels provide strong syntax trapping at the expense of slow execution for some routines. High user levels relax the syntax trapping in order to provide better execution speeds."; 


(* ::Input::Initialization:: *)
SetUserLevel::nochge="The user level is already set to `1`. No action has been taken.";


(* ::Input::Initialization:: *)
SetUserLevel::minul="The user level has been set to the minimum value of 1. Syntax trapping is strong, but execution speed may be compromised.";


(* ::Input::Initialization:: *)
SetUserLevel::ul="The user level has been set to `1`.";


(* ::Input::Initialization:: *)
SetUserLevel::maxul="The user level has been set to `1`, which is the maximum level available. Some syntax traps have been weakened for the sake of speed improvements.";


(* ::Input::Initialization:: *)
SetUserLevel::modsymbs="Additional definitions have been given to the following symbols: `1`";


(* ::Input::Initialization:: *)
SetAttributes[UserLevelDependentDefinition,HoldAll];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[symb_Symbol,code:Except[_Integer|_Rule|Undefined],opts___Rule]:=
UserLevelDependentDefinition[symb,Evaluate@UserLevel[],code,opts];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[symb_Symbol,Infinity,code:Except[_Integer|_Rule|Undefined],opts___Rule]:=UserLevelDependentDefinition[symb,Evaluate@MaximumUserLevel,code,opts];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[symb_Symbol,ul_,code:Except[_Integer|_Rule|Undefined],opts___Rule]/;(!IntegerQ[ul])||ul<1||ul>MaximumUserLevel:=
((*Print[{UserLevelDependentDefinition,symb,ul}];*)
Message[UserLevel::badul,MaximumUserLevel];$Failed);


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[symb_Symbol,ul_Integer,code:Except[_Integer|_Rule|Undefined],opts___Rule]:=
Module[{newdef},(
UserLevelDependentDefinitions[symb,ul,opts]=
AppendTo[
UserLevelDependentDefinitions[symb,ul,opts],
Hold[code]
];
UserLevelDependentSymbols[ul]=Union@AppendTo[UserLevelDependentSymbols[ul],symb];
)
];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition::badul="The user level must be an integer between 1 and `1`."; 


(* ::Input::Initialization:: *)
UserLevelDependentSymbols[opts___Rule]:=UserLevelDependentSymbols[{UserLevel[]},opts];


(* ::Input::Initialization:: *)
UserLevelDependentSymbols[{ul_}]:=UserLevelDependentSymbols[{ul,MaximumUserLevel}];


(* ::Input::Initialization:: *)
UserLevelDependentSymbols[{ulmin_,ulmax_}]:=Union@Flatten[UserLevelDependentSymbols/@Range[ulmin,ulmax]];


(* ::Input::Initialization:: *)
UserLevelDependentSymbols[ul_,opts___Rule]/;(!IntegerQ[ul])||ul<1||ul>MaximumUserLevel:=
(Message[UserLevel::badul,MaximumUserLevel];$Failed);


(* ::Input::Initialization:: *)
UserLevelDependentSymbols[ul_,opts___Rule]:={};


(* ::Input::Initialization:: *)
UserLevelDependentDefinitions[symb_Symbol,opts___Rule]:=UserLevelDependentDefinitions[symb,{UserLevel[]},opts];


(* ::Input::Initialization:: *)
UserLevelDependentDefinitions[symb_Symbol,{ul_},opts___Rule]:=UserLevelDependentDefinitions[symb,{ul,MaximumUserLevel},opts];


(* ::Input::Initialization:: *)
UserLevelDependentDefinitions[symb_Symbol,{ulmin_,ulmax_},opts___Rule]:=Union@Flatten[UserLevelDependentDefinitions[symb,#,opts]&/@Range[ulmin,ulmax]];


(* ::Input::Initialization:: *)
UserLevelDependentDefinitions[symb_Symbol,ul_,opts___Rule]/;(!IntegerQ[ul])||ul<1||ul>MaximumUserLevel:=
(Message[UserLevel::badul,MaximumUserLevel];$Failed);


(* ::Input::Initialization:: *)
UserLevelDependentDefinitions[symb_Symbol,ul_,opts___Rule]:={};


(* ::Input::Initialization:: *)
DeleteUserLevelDependentDefinitions[]:=DeleteUserLevelDependentDefinitions[Range[1,MaximumUserLevel]];


(* ::Input::Initialization:: *)
DeleteUserLevelDependentDefinitions[ul:Except[_Symbol|_List]]:=DeleteUserLevelDependentDefinitions[{ul}];


(* ::Input::Initialization:: *)
DeleteUserLevelDependentDefinitions[uls_List]:=
Module[{symbs},(
symbs=Union@Flatten[UserLevelDependentSymbols/@uls];
DeleteUserLevelDependentDefinitions[#,uls]&/@symbs
)];


(* ::Input::Initialization:: *)
DeleteUserLevelDependentDefinitions[symb_Symbol]:=
DeleteUserLevelDependentDefinitions[symb,Range[1,MaximumUserLevel]];


(* ::Input::Initialization:: *)
DeleteUserLevelDependentDefinitions[symb_Symbol,ul:Except[_Symbol|_List]]:=DeleteUserLevelDependentDefinitions[symb,{ul}];


(* ::Input::Initialization:: *)
DeleteUserLevelDependentDefinitions[symb_Symbol,uls_List]:=
Module[{protected},(
protected=MemberQ[Attributes[symb],Protected];
If[protected,Unprotect[symb]];
If[BuiltInDefinitionsSavedQ[symb],
(Clear[symb];
(*Print["clearing definitions for ",symb];*)
RestoreBuiltInDefinitions[symb])];
ImplementUserLevelDependentDefinitions[symb,Complement[Range[1,MaximumUserLevel],uls]];
If[protected,Protect[symb]]
)];


(* ::Input::Initialization:: *)
ImplementUserLevelDependentDefinitions[]:=ImplementUserLevelDependentDefinitions[Range[1,MaximumUserLevel]];


(* ::Input::Initialization:: *)
ImplementUserLevelDependentDefinitions[ul:Except[_Symbol|_List]]:=ImplementUserLevelDependentDefinitions[{ul}];


(* ::Input::Initialization:: *)
ImplementUserLevelDependentDefinitions[uls_List]:=
Module[{symbs},(
symbs=Union@Flatten[UserLevelDependentSymbols/@uls];
ImplementUserLevelDependentDefinitions[#,uls]&/@symbs
)];


(* ::Input::Initialization:: *)
ImplementUserLevelDependentDefinitions[symb_Symbol]:=
ImplementUserLevelDependentDefinitions[symb,Range[1,MaximumUserLevel]];


(* ::Input::Initialization:: *)
ImplementUserLevelDependentDefinitions[symb_Symbol,ul:Except[_Symbol|_List]]:=ImplementUserLevelDependentDefinitions[symb,{ul}];


(* ::Input::Initialization:: *)
ImplementUserLevelDependentDefinitions[symb_Symbol,uls_List]:=
(
Unprotect[symb];
If[!BuiltInDefinitionsSavedQ[symb],
SaveBuiltInDefinitions[symb]];
ReleaseHold@UserLevelDependentDefinitions[symb,#]&/@uls;Protect[symb]
);


(* ::Input::Initialization:: *)
BuiltInDefinitionsSavedQ[symb_Symbol]:=False;


(* ::Input::Initialization:: *)
SaveBuiltInDefinitions[symb_Symbol]:=
(
(*Print["Storing down & upvalues for ",symb];*)
BuiltInDownValues[symb]=DownValues[symb];
BuiltInUpValues[symb]=UpValues[symb];
BuiltInDefinitionsSavedQ[symb]=True;
);


(* ::Input::Initialization:: *)
RestoreBuiltInDefinitions[symb_Symbol]:=
Module[{protected},(
protected=MemberQ[Attributes[symb],Protected];
If[BuiltInDefinitionsSavedQ[symb],
(
If[protected,Unprotect[symb]];
(*Print["Restoring down & upvalues for ",symb];*)
DownValues[symb]=BuiltInDownValues[symb];
UpValues[symb]=BuiltInUpValues[symb];
If[protected,Protect[symb]]
)];
)];


(* ::Input::Initialization:: *)
End[];


(* ::Input::Initialization:: *)
EndPackage[]
