(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["Ensemble`EnsembleAverage`",
{"Global`",
"SpinDynamica`",
"General`UserLevel`",
"QM`Hilbert`",
"QM`SpinOperators`",
"QM`Liouville`",
"SD`Generators`",
"SD`Approximations`",
"SD`Propagation`",
"Events`Events`",
"Events`PulseSequence`",
"General`Miscellaneous`"
}];


(* ::Input::Initialization:: *)
EnsembleAverage::usage="EnsembleAverage is an option for high-level SpinDynamica routines including Signal1D, Trajectory, TransformationAmplitude and TransformationAmplitudeTable. The default is EnsembleAverage\[Rule]False, in which case no ensemble averaging is done. A general specification is EnsembleAverage\[Rule]{var,samplingscheme}, which implements an ensemble average of the variable var, using the scheme samplingscheme, which takes the form {{{val1},weight1},{{val2},weight2}...}. The computation is performed for all the defined values {val1,val2..} of the variable var, and the results superposed using the weights {weight1,weight2..}. Simplified syntax of the form EnsembleAverage\[Rule]{var,{val1,val2..}} assumes equally weighted values (summing to 1).
The sampling scheme may also be implemented over multiple variables. For example, the syntax EnsembleAverage\[Rule]{{\[Alpha],\[Beta],\[Gamma]},{{{\[Alpha]1,\[Beta]1,\[Gamma]1},w1}, {{\[Alpha]2,\[Beta]2,\[Gamma]2},w2}..} implements summation over a set of Euler angles {\[Alpha],\[Beta],\[Gamma]} with the specified values and weights. 
Each of the EnsembleAverage variables may also be multidimensional, i.e. having a value which is a list. For example, the syntax EnsembleAverage\[Rule]{\[CapitalOmega],{{{\[Alpha]1,\[Beta]1,\[Gamma]1},w1}, {{\[Alpha]2,\[Beta]2,\[Gamma]2},w2}..} implements a summation over a variable \[CapitalOmega], which takes values given by the three-element lists of Euler angle triplets {{\[Alpha]1,\[Beta]1,\[Gamma]1}, {\[Alpha]2,\[Beta]2,\[Gamma]2},..} etc. with computations summed using the weights {w1, w2...}. 
Predefined Euler angle sets for powder averaging are available through syntax of the form EnsembleAverage\[Rule]{\[CapitalOmega],OrientationsAndWeights[<scheme>]} or EnsembleAverage\[Rule]{{\[Alpha],\[Beta],\[Gamma]},OrientationsAndWeights[<scheme>]}. Execute ?OrientationsAndWeights for more information. 
The ensemble variables may appear in any of the other arguments of the high-level SpinDynamica routine, including option specifications such as BackgroundGenerator. 
The additional option setting Parallel\[Rule]True distributes computation of the EnsembleAverage over the available kernels.
";


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage::usage="StandardizeEnsembleAverage is an internal routine used by SpinDynamica.";


(* ::Input::Initialization:: *)
EnsembleWeights::usage="EnsembleWeights is an internal routine used by SpinDynamica.";


(* ::Input::Initialization:: *)
ExpandMultidimensionalEnsembleVariables::usage="ExpandMultidimensionalEnsembleVariables is an internal routine used by SpinDynamica.";


(* ::Input::Initialization:: *)
EnsembleSubstitutionRules::usage="EnsembleSubstitutionRules is an internal routine used by SpinDynamica.";


(* ::Input::Initialization:: *)
EnsembleVariablesFreeQ::usage="EnsembleVariablesFreeQ is an internal routine used by SpinDynamica.";


(* ::Input::Initialization:: *)
MaxBatchSize::usage="MaxBatchSize is an option associated with EnsembleAverage which causes the ensemble average to be divided into batches of dimension not larger than MaxBatchSize. The results of each batch are combined first before the overall combination is generated. This procedure conserves memory for large ensemble averages.";


(* ::Input::Initialization:: *)
Parallel::usage="Parallel is an option for high-level SpinDynamica routines including Signal1D, Trajectory, TransformationAmplitude and TransformationAmplitudeTable. If True (which is usually the default), then the members of EnsembleAverage are computed in parallel using the available kernels. If Parallel\[Rule]<integer>, then the specified number of kernels is used. If Parallel\[Rule]False, then the ensemble average computations are performed sequentially on a single kernel.";


(* ::Input::Initialization:: *)
PrepareParallel::usage="PrepareParallel is an internal routine used by SpinDynamica for setting up the parallelized computation of an ensemble average.";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[None|False]=False;


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[expr_]/;!FreeQ[expr,$Failed]:=$Failed;


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[{var:Except[_List],vals_List}]:=StandardizeEnsembleAverage[{{var},vals}];


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[{vars:{___,_List,___},vals_}]:=StandardizeEnsembleAverage[{Flatten@vars,vals}];


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[{vars_,vals_}]/;!MatchQ[vars,{(_Symbol|_Symbol[_Integer])..}]:=
(Message[EnsembleAverage::badvar];$Failed);


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[{vars_List,vals:{Except[_List]..}}]/;Length[vars]>1:=
(Message[EnsembleAverage::toomanyvars];$Failed);


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[{vars_List,vals:{Except[_List]..}}]/;(Length[vars]==1):=
Module[{nvals,weights},(
nvals=Length[vals];
weights=Table[1/nvals,{nvals}];
StandardizeEnsembleAverage[{vars,Transpose[{List/@vals,weights}]}]
)];


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[{vars_List,vals:{_List..}}]/;!Equal@@(Length/@vals):=(Message[EnsembleAverage::inconslengths];$Failed);


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[{vars:{var_},vals:{{Except[_List],Except[_List]}..}}]:=
Module[{umambigvals,val1,w1},(
umambigvals=MapAt[List,#,1]&/@vals;
{val1,w1}=First[vals];
(Message[
EnsembleAverage::ambig1Dvar,
var,
val1,
w1
];
StandardizeEnsembleAverage[{vars,umambigvals}])
)];


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[{vars_List,vals:{{Except[_List]..}..}}]/;(Length[vars]==Length@First[vals]):=
StandardizeEnsembleAverage[{vars,Map[List,vals,1]}];


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[{vars_List,vals:{_List..}}]:=
Module[{nvar,valdim,nvals,weights},(
nvals=Length[vals];
weights=Table[1/nvals,{nvals}];
StandardizeEnsembleAverage[{vars,MapThread[Join[{#1},{#2}]&,{vals,weights}]}]
)/;(
nvar=Length[vars];
valdim=Length[vals[[1]]];
(nvar==valdim)&&
!MatchQ[First@vals,{_List,Except[_List]}]
)];


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[{vars_List,vals:{_List..}}]:=
Module[{nvar,valdim,nvals,weights},(
nvals=Length[vals];
weights=Table[1/nvals,{nvals}];
StandardizeEnsembleAverage[{vars,MapThread[Join[#1,{#2}]&,{vals,weights}]}]
)/;(
nvar=Length[vars];
valdim=Length[vals[[1,1]]];
(nvar==valdim)&&
!MatchQ[First@vals,{_List,Except[_List]}]
)];


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[{vars_List,valws:{{_,Except[_List]}..}}]:=
Module[{vals,weights},(
{vals,weights}=Transpose@valws;
StandardizeEnsembleAverage[{vars,Transpose[{List/@vals,weights}]}]
)]/;MatchQ[valws[[1,1]],Except[_List]]||
(MatchQ[valws[[1,1]],{Except[_List]..}]&&Length[valws[[1,1]]]!=Length[vars]);


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[{vars_List,valws:{{_List,Except[_List]}..}}]/;(Length[vars]!=Length[valws[[1,1]]])&&(Length[vars]==Length@Flatten[valws[[1,1]]]):=
Module[{vals,weights},(
{vals,weights}=Transpose@valws;{vars,Transpose[{Flatten/@vals,weights}]}
)];


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[{vars_List,valws:{{_List,Except[_List]}..}}]/;Length[vars]==Length[valws[[1,1]]]:={vars,valws};


(* ::Input::Initialization:: *)
StandardizeEnsembleAverage[expr_]:=(Message[EnsembleAverage::badspec];$Failed);


(* ::Input::Initialization:: *)
EnsembleWeights[expr_]/;!FreeQ[expr,$Failed]:=$Failed;


(* ::Input::Initialization:: *)
EnsembleWeights[{vars_,valws_}]/;!MatchQ[{vars,valws},{_List,{{_List,Except[_List]}..}}]||
Length[vars]!=Length[valws[[1,1]]]:=EnsembleWeights@StandardizeEnsembleAverage[{vars,valws}];


(* ::Input::Initialization:: *)
EnsembleWeights[{vars_,valws_}]:=Last/@valws;


(* ::Input::Initialization:: *)
MultidimensionalEnsembleVariables[expr_]/;!FreeQ[expr,$Failed]:=$Failed;


(* ::Input::Initialization:: *)
MultidimensionalEnsembleVariables[{vars_,valws_}]/;!MatchQ[{vars,valws},{_List,{{_List,Except[_List]}..}}]||
Length[vars]!=Length[valws[[1,1]]]:=MultidimensionalEnsembleVariables@StandardizeEnsembleAverage[{vars,valws}];


(* ::Input::Initialization:: *)
MultidimensionalEnsembleVariables[{vars_,valws_}]:=Cases[Transpose[{vars,Map[If[MatchQ[#,_List],Length[#],0]&,valws[[1,1]]]}],{_,Except[0]}];


(* ::Input::Initialization:: *)
SetAttributes[ExpandMultidimensionalEnsembleVariables,HoldFirst];


(* ::Input::Initialization:: *)
ExpandMultidimensionalEnsembleVariables[exprs__]/;!FreeQ[Hold@{exprs},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
ExpandMultidimensionalEnsembleVariables[expr_]/;MatchQ[ReleaseHold[expr],{_,{{_,Except[_List]}..}}]:=
Module[{vars,valws},(
{vars,valws}=expr;
StandardizeEnsembleAverage[
{ExpandMultidimensionalEnsembleVariables[Evaluate@vars,{vars,valws}],valws}
])];


(* ::Input::Initialization:: *)
ExpandMultidimensionalEnsembleVariables[expr_,None|False]:=expr;


(* ::Input::Initialization:: *)
ExpandMultidimensionalEnsembleVariables[expr_,{vars_,valws_}]/;!MatchQ[{vars,valws},{_List,{{_List,Except[_List]}..}}]||
Length[vars]!=Length[valws[[1,1]]]:=ExpandMultidimensionalEnsembleVariables[expr,StandardizeEnsembleAverage[{vars,valws}]];


(* ::Input::Initialization:: *)
ExpandMultidimensionalEnsembleVariables[expr_,{vars_,valws_}]:=
Module[{multidensvar},(
multidensvar=MultidimensionalEnsembleVariables[{vars,valws}];
SetAttributes[Evaluate[First[#]],NHoldFirst]&/@multidensvar;
ReleaseHold[
expr/.(Rule[First[#],Array[First[#],Last[#]]]&/@multidensvar)
]
)];


(* ::Input::Initialization:: *)
EnsembleSubstitutionRules[expr_]/;!FreeQ[expr,$Failed]:=$Failed;


(* ::Input::Initialization:: *)
EnsembleSubstitutionRules[{vars_,valws_}]/;!MatchQ[{vars,valws},{_List,{{_List,Except[_List]}..}}]||
Length[vars]!=Length[valws[[1,1]]]:=EnsembleSubstitutionRules@StandardizeEnsembleAverage[{vars,valws}];


(* ::Input::Initialization:: *)
EnsembleSubstitutionRules[{vars_,valws_}]/;!MatchQ[MultidimensionalEnsembleVariables[{vars,valws}],{}]:=
EnsembleSubstitutionRules@
StandardizeEnsembleAverage[
MapAt[Flatten,
ReleaseHold@ExpandMultidimensionalEnsembleVariables[Evaluate@{vars,valws},{vars,valws}],
1]
];


(* ::Input::Initialization:: *)
EnsembleSubstitutionRules[{vars_,valws_}]/;MatchQ[MultidimensionalEnsembleVariables[{vars,valws}],{}]:=
Module[{vals,nvar},(
vals=First/@valws;
nvar=Length[vars];
Transpose@Map[
(Function[val,First[#]->val]/@Last[#])&,
Table[{vars[[i]],Part[#,i]&/@vals},{i,1,nvar}]
]
)];


(* ::Input::Initialization:: *)
EnsembleVariablesFreeQ[expr_,(None|False)]:=True;


(* ::Input::Initialization:: *)
EnsembleVariablesFreeQ[expr_,{vars_,valws_}]/;!MatchQ[{vars,valws},{_List,{{_List,Except[_List]}..}}]||
Length[vars]!=Length[valws[[1,1]]]:=EnsembleVariablesFreeQ[expr,StandardizeEnsembleAverage[{vars,valws}]];


(* ::Input::Initialization:: *)
EnsembleVariablesFreeQ[expr_,{vars_,valws_}]:=
And@@(FreeQ[expr,#]&/@vars);


(* ::Input::Initialization:: *)
EnsembleAverage::badvar="One or more ensemble average variables already has an assigned value.";


(* ::Input::Initialization:: *)
EnsembleAverage::toomanyvars="The number of ensemble average variables exceeds the dimension of the ensemble average values.";


(* ::Input::Initialization:: *)
EnsembleAverage::inconslengths="The ensemble average values have inconsistent lengths.";


(* ::Input::Initialization:: *)
EnsembleAverage::ambig1Dvar="The syntax is ambiguous. SpinDynamica will assume that `1` is a one-dimensional variable and that {{`2`,`3`}..} specifies a set of one-dimensional values and weights. To avoid this ambiguity, use the syntax EnsembleAverage\[Rule]{`1`,{{`2`},`3`},..}}. If you intend `1` to be a two-dimensional variable taking equally weighted values {{`2`,`3`},..}, use the syntax EnsembleAverage\[Rule]{`1`,{{`2`,`3`}},..}}. 
"; 


(* ::Input::Initialization:: *)
EnsembleAverage::ambig="The syntax is ambiguous. Equally weighted values of dimension `1` have been assumed."; 


(* ::Input::Initialization:: *)
EnsembleAverage::badspec="Cannot interpret EnsembleAverage specification.";


(* ::Input::Initialization:: *)
Parallel::toomany="The number of requested kernels is too high. Calculation is proceeding with `1` kernels";


(* ::Input::Initialization:: *)
Parallel::inval="The value of Parallel is invalid.";


(* ::Input::Initialization:: *)
Options[PrepareParallel]={Parallel->True};


(* ::Input::Initialization:: *)
PrepareParallel[opts___Rule]:=PrepareParallel[OperatorBasis[],opts];


(* ::Input::Initialization:: *)
PrepareParallel[opbasis_,opts___Rule]:=PrepareParallel[opbasis,ZeemanBasis[],opts];


(* ::Input::Initialization:: *)
PrepareParallel[opbasis_,basis_,opts___Rule]/;!MatchQ[Parallel/.{opts}/.Options[PrepareParallel],True|All|_?IntegerQ]||
TrueQ[(Parallel/.{opts}/.Options[PrepareParallel])<0]:=
(Message[Parallel::inval];$Failed);


(* ::Input::Initialization:: *)
PrepareParallel[opbasis_,basis_,opts___Rule]:=
Module[{parallel,nkernelsrunning,nkernelsrequested,path,chronology,stufftodistribute,ul},(
parallel=Parallel/.{opts}/.Options[PrepareParallel];
Which[
MatchQ[parallel,True|All]&&TrueQ[$ProcessorCount>$KernelCount],
	LaunchKernels[$ProcessorCount-$KernelCount],
IntegerQ[parallel]&&TrueQ[parallel>$ProcessorCount]&&TrueQ[parallel>$KernelCount],
	(Message[PrepareParallel::nonparkernels];
	LaunchKernels[parallel-$KernelCount]),
IntegerQ[parallel]&&TrueQ[parallel>$KernelCount],
	LaunchKernels[parallel-$KernelCount],
IntegerQ[parallel]&&TrueQ[parallel<$KernelCount],
	(Message[PrepareParallel::relaunch];
	CloseKernels[];
	LaunchKernels[parallel]),
True,
	Null
];
If[
$KernelID==0,
(path=$Path;
chronology=$Chronology;
DistributeDefinitions[path,chronology];
ul=UserLevel[];
ParallelEvaluate[$Path=path];
ParallelEvaluate[$Chronology=chronology];
DistributeDefinitions[SpinSystem[],Basis[],ZeemanKetBraOperatorBasis[]];
)
];
ParallelNeeds["SpinDynamica`"];
ParallelEvaluate[Quiet@SetUserLevel[ul]];
ParallelEvaluate[Quiet@SetSpinSystem[SpinSystem[basis]]];
	ParallelEvaluate[Quiet@If[basis===Basis[],Nothing,SetBasis[basis]]];
	ParallelEvaluate[Quiet@If[opbasis===OperatorBasis[],Nothing,SetOperatorBasis[opbasis]]];
	stufftodistribute={SpinSystem[],Basis[],OperatorBasis[],$RecursionLimit,$IterationLimit,$ChopThreshold,$Chronology};
	DistributeDefinitions[stufftodistribute];
ParallelEvaluate[stufftodistribute];
DistributeDefinitions["Global`","General`PhysicalConstants`"];
)]; 


(* ::Input::Initialization:: *)
PrepareParallel::relaunch="Closing and relaunching kernels since the requested number of parallel kernels is less than those already running.";


(* ::Input::Initialization:: *)
PrepareParallel::nonparkernels="The number of requested kernels is more than the number of processors, so the kernels will not all run in parallel. Proceeding anyway.";


(* ::Input::Initialization:: *)
End[];
EndPackage[];
