(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["GroupsAndAlgebras`Commutant`",
{"Global`",
"SpinDynamica`",
"General`UserLevel`",
"General`Matrices`",
"General`Miscellaneous`",
"SD`Generators`",
"QM`Hilbert`",
"QM`SpinOperators`",
"QM`Liouville`"}];


(* ::Input::Initialization:: *)
Commutant::usage="Commutant may be used to calculate an operator basis for all elements that commute with a given set of operators Q={\!\(\*SubscriptBox[\(Q\), \(1\)]\),\!\(\*SubscriptBox[\(Q\), \(2\)]\), ...,\!\(\*SubscriptBox[\(Q\), \(n\)]\)} with respect to a given Lie algebra basis B={\!\(\*SubscriptBox[\(B\), \(1\)]\),\!\(\*SubscriptBox[\(B\), \(2\)]\), ...,\!\(\*SubscriptBox[\(B\), \(N\)]\)}. The commutant of Q, comm(Q), is defined by: comm(Q)={b \[Element] B| [b,q]= 0 \[ForAll]q \[Element] Q}. The output is again a set of operators C={\!\(\*SubscriptBox[\(C\), \(1\)]\),\!\(\*SubscriptBox[\(C\), \(2\)]\),...,\!\(\*SubscriptBox[\(C\), \(M\)]\)} with the property: [\!\(\*SubscriptBox[\(C\), \(j\)]\),\!\(\*SubscriptBox[\(Q\), \(k\)]\)]=0 for all operators \!\(\*SubscriptBox[\(C\), \(j\)]\) and \!\(\*SubscriptBox[\(Q\), \(k\)]\), in general though [\!\(\*SubscriptBox[\(C\), \(i\)]\),\!\(\*SubscriptBox[\(C\), \(j\)]\)]\[NotEqual]0.

The syntax distinguishes two important cases:

1) Commutant[{\!\(\*SubscriptBox[\(Q\), \(1\)]\),\!\(\*SubscriptBox[\(Q\), \(2\)]\), ...,\!\(\*SubscriptBox[\(Q\), \(n\)]\)}] calculates a basis for all elements that commute with Q with respect to all of Liouville space.

2)   Commutant[{{\!\(\*SubscriptBox[\(Q\), \(1\)]\),\!\(\*SubscriptBox[\(Q\), \(2\)]\), ...,\!\(\*SubscriptBox[\(Q\), \(n\)]\)},{\!\(\*SubscriptBox[\(B\), \(1\)]\),\!\(\*SubscriptBox[\(B\), \(2\)]\), ...,\!\(\*SubscriptBox[\(B\), \(N\)]\)}}] calculates a basis for all elements that commute with Q relative to B under the assumption that Q is a subset of B, in example Q \[Subset] B. 
";


(* ::Input::Initialization:: *)
Bicommutant::usage="Bicommutant calculates the Bicommutant of a set of operators {Q}. The syntax for Bicommutant is as follows: (1) Bicommutant[{\!\(\*SubscriptBox[\(Q\), \(1\)]\),\!\(\*SubscriptBox[\(Q\), \(2\)]\),...,\!\(\*SubscriptBox[\(Q\), \(N\)]\)}], where \!\(\*SubscriptBox[\(Q\), \(1\)]\),\!\(\*SubscriptBox[\(Q\), \(2\)]\), etc. are spin operators. The Bicommutant is formally equivalent to the commutant of the commutant of Q, in example BC({Q})= C(C({Q})). In practice the Bicommutant is thus calculated as follows: Commutant[Commutant[{\!\(\*SubscriptBox[\(Q\), \(1\)]\),\!\(\*SubscriptBox[\(Q\), \(2\)]\),...,\!\(\*SubscriptBox[\(Q\), \(N\)]\)}]].";


(* ::Input::Initialization:: *)
VectorSpaceIntersection::usage="?";


(* ::Input::Initialization:: *)
$Chronology="LeftToRight";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
Options[Commutant]={OperatorBasis:> OperatorBasis[],Basis:>Basis[]};


(* ::Input::Initialization:: *)
Commutant[args___]:=Commutant[args,{"1","0"}];


(* ::Input::Initialization:: *)
Commutant[args_,opts___Rule,{"1","0"}]:=Which[
MatchQ[args,{_?OperatorQ..}],
Commutant[args,opts,{"2","1"}],
MatchQ[args,{{_?OperatorQ..},{_?OperatorQ..}}],
Commutant[args,opts,{"2","2"}],
OperatorQ[args],
Commutant[{args},opts,{"2","1"}],
True,Message[Commutant::WrongInput];Abort[];
]
Commutant[args___,{"1","0"}]:=(Message[Commutant::WrongInput];Abort[];)


(* ::Input::Initialization:: *)
Commutant::WrongInput= "Commutant expects one of the following two inputs:

1)a set of operators, for example {opI[\"z\"],opI[1].opI[2]}

2)a tuple of a set of operators, for example {{opI[\"x\"]},{opI[\"x\"],opI[\"y\"]opI[\"z\"]}}

In case 1) Commutant calculates the commutant of {\!\(\*SubscriptBox[\(Q\), \(1\)]\),..., \!\(\*SubscriptBox[\(Q\), \(n\)]\)} relative to the total operators space.
In case 2) Commutant calculates the commutant of {\!\(\*SubscriptBox[\(Q\), \(1\)]\),..., \!\(\*SubscriptBox[\(Q\), \(n\)]\)} relative to the truncated operators basis {\!\(\*SubscriptBox[\(B\), \(1\)]\),..., \!\(\*SubscriptBox[\(B\), \(N\)]\)} under the assumption that {\!\(\*SubscriptBox[\(Q\), \(1\)]\),..., \!\(\*SubscriptBox[\(Q\), \(n\)]\)} \[Subset] {\!\(\*SubscriptBox[\(B\), \(1\)]\),..., \!\(\*SubscriptBox[\(B\), \(N\)]\)}. 
";


(* ::Input::Initialization:: *)
Commutant[algebra_?ListQ,opts___Rule,{"2","1"}]:=Module[{opbasis,V,Vinv,commsops,nullspaces,maximalintersection},opbasis=OperatorBasis/.Join[{opts},{OperatorBasis -> OperatorBasis[]}];
V=OperatorBasisTransformationMatrix[opbasis,ZeemanKetBraOperatorBasis[]];
Vinv=ConjugateTranspose[V];
commsops=SuperoperatorMatrixRepresentation[CommutationSuperoperator[#],ZeemanKetBraOperatorBasis[]]&/@algebra;
commsops=Chop@Simplify[V . # . Vinv]&/@commsops;
maximalintersection=NullSpace[ArrayFlatten[List/@commsops]];
If[MatchQ[maximalintersection,{}],{},Simplify[Total[BasisOperators[opbasis]*#]]&/@maximalintersection]
]


(* ::Input::Initialization:: *)
Commutant[{operators_?ListQ,algebra_?ListQ},opts___Rule,{"2","2"}]:=Module[{opbasis,V,Vinv,projalg,projb,commsops,nullspaces,maximalintersection},opbasis=OperatorBasis/.Join[{opts},{OperatorBasis -> OperatorBasis[]}];
V=OperatorVectorRepresentation[#,ZeemanKetBraOperatorBasis[]]&/@algebra//SparseArray;
Vinv=ConjugateTranspose[V];
commsops=SuperoperatorMatrixRepresentation[CommutationSuperoperator[#],ZeemanKetBraOperatorBasis[]]&/@operators;
commsops=Chop@Simplify[V . # . Vinv]&/@commsops;
maximalintersection=NullSpace[ArrayFlatten[List/@commsops]];
(If[MatchQ[maximalintersection,{}],{},Simplify[ExpressOperator[# . algebra,opbasis]]&/@maximalintersection]//DeleteDuplicates)/.{0->Nothing}
]


VectorSpaceIntersection[{},W_]:={};
VectorSpaceIntersection[V_,{}]:={};


VectorSpaceIntersection[V_,W_]:=Module[{lenVW,dimV,rrfVW,colcur,blockB,counter},
dimV=Length[V[[1]]];
rrfVW=RowReduce[ArrayFlatten[{{V,V},{W,0}}]];
counter=-1;
While[MatchQ[Chop[Normal[rrfVW[[counter,1;;dimV]]]],{0..}],
counter=counter-1;
];
rrfVW[[counter+1;;-1,dimV+1;;]]
]


(* ::Input::Initialization:: *)
Options[Bicommutant]={OperatorBasis:> OperatorBasis[],Basis:>Basis[]};


(* ::Input::Initialization:: *)
Bicommutant[args_,opts___Rule]:=Commutant[Commutant[args],opts];


(* ::Input::Initialization:: *)
End[];
EndPackage[];



