(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["GroupsAndAlgebras`LieTheory`",
{"Global`",
"SpinDynamica`",
"QM`SpinOperators`",
"QM`Hilbert`",
"QM`Liouville`",
"General`UserLevel`",
"General`Matrices`",
"General`Miscellaneous`",
"GroupsAndAlgebras`Commutant`"}];


(* ::Input::Initialization:: *)
DualPairing::usage = 
"DualPairing determintes the dual pairing between irreducible representations of S(n) and SO(3). The syntax is as follows: dualpairing[nspins, angularmomentum].

The symbol nspins is an integer representing the number of identical spins and
angularmomentum is an integer or half-integer representing the angular momentum of the spins.

The dual pairing for three identical spin-1/2 particles would be calcualted as follows: dualpairing[3, 1/2]";


(* ::Input::Initialization:: *)
LieAlgebraField::usage = 
"The number field over which the LieAlgebra is defined.";


(* ::Input::Initialization:: *)
LieAlgebra::usage = 
"LieAlgebra calculates the Lie algebra with respect to the a generating set of opertors {\!\(\*SubscriptBox[\(Q\), \(1\)]\), \!\(\*SubscriptBox[\(Q\), \(2\)]\),..., \!\(\*SubscriptBox[\(Q\), \(N\)]\)}. The syntax is as follows: LieAlgebra[{\!\(\*SubscriptBox[\(Q\), \(1\)]\), \!\(\*SubscriptBox[\(Q\), \(2\)]\),..., \!\(\*SubscriptBox[\(Q\), \(N\)]\)}], for example LieAlgebra[{opI[\"x\"],opI[\"y\"]}] calculates the Lie algebra of the rotation group SO(3).";


(* ::Input::Initialization:: *)
LieAlgebraLinIndepOperators::usage = 
"Internal SpinDynamica routine utilised by LieAlgebra to determine a set of linearly independent operators.";


(* ::Input::Initialization:: *)
LieAlgebraField::usage = 
"The number field over which the LieAlgebra is defined.";


(* ::Input::Initialization:: *)
AbelianSubalgebra::usage = "AbelianSubalgebra extends an initial Hermitian-Abelian subalgebra A={\!\(\*SubscriptBox[\(A\), \(1\)]\),\!\(\*SubscriptBox[\(A\), \(2\)]\), ...,\!\(\*SubscriptBox[\(A\), \(n\)]\)} \[Subset] B to its maximal rank with respect to Lie algebra basis B={\!\(\*SubscriptBox[\(B\), \(1\)]\),\!\(\*SubscriptBox[\(B\), \(2\)]\), ...,\!\(\*SubscriptBox[\(B\), \(N\)]\)}.

The syntax distinguishes two cases:

1) AbelianSubalgebra[{\!\(\*SubscriptBox[\(A\), \(1\)]\),\!\(\*SubscriptBox[\(A\), \(2\)]\), ...,\!\(\*SubscriptBox[\(A\), \(n\)]\)}] extends A to its maximal abelian rank with respect to all of Liouville space.

2) AbelianSubalgebra[{{\!\(\*SubscriptBox[\(A\), \(1\)]\),\!\(\*SubscriptBox[\(A\), \(2\)]\), ...,\!\(\*SubscriptBox[\(A\), \(n\)]\)}, {\!\(\*SubscriptBox[\(B\), \(1\)]\),\!\(\*SubscriptBox[\(B\), \(2\)]\), ...,\!\(\*SubscriptBox[\(B\), \(N\)]\)}}] extends A to its maximal abelian rank inside B={\!\(\*SubscriptBox[\(B\), \(1\)]\),\!\(\*SubscriptBox[\(B\), \(2\)]\), ...,\!\(\*SubscriptBox[\(B\), \(N\)]\)} under the assumption that A is an Abelian subalgebra of B, in example A \[Subset] B and [A,A]=0. 
";


(* ::Input::Initialization:: *)
rrefgetpivots::usage = "SpinDynamica internal routine. Calculates the pivot positions of a row-reduced echelon form.";


(* ::Input::Initialization:: *)
MaximalAbelianQ::usage = 
"MaximalAbelianQ determines whether a given Abelian subalgebra A={\!\(\*SubscriptBox[\(A\), \(1\)]\),\!\(\*SubscriptBox[\(A\), \(2\)]\), ...,\!\(\*SubscriptBox[\(A\), \(n\)]\)} is maximal Abelian (Cartan) or not.

The syntax distinguishes two important cases:

1) MaximalAbelianQ[{\!\(\*SubscriptBox[\(A\), \(1\)]\),\!\(\*SubscriptBox[\(A\), \(2\)]\),...,\!\(\*SubscriptBox[\(A\), \(n\)]\)}] checks if A is a maximal Abelian subalgebra for all of Liouville space.

2) MaximalAbelianQ[{{\!\(\*SubscriptBox[\(A\), \(1\)]\),\!\(\*SubscriptBox[\(A\), \(2\)]\),...,\!\(\*SubscriptBox[\(A\), \(n\)]\)}, {\!\(\*SubscriptBox[\(B\), \(1\)]\),\!\(\*SubscriptBox[\(B\), \(2\)]\),...,\!\(\*SubscriptBox[\(B\), \(N\)]\)}}] checks if A is a maximal Abelian subalgebra inside B={\!\(\*SubscriptBox[\(B\), \(1\)]\),\!\(\*SubscriptBox[\(B\), \(2\)]\),...,\!\(\*SubscriptBox[\(B\), \(N\)]\)} under the assumption that A is an Abelian subalgebra of B, in example A \[Subset] B and [A,A]=0. 
";


(* ::Input::Initialization:: *)
InaccessibleOperatorQ::usage = "InaccessibleOperatorQ determines which of a given set of operators {\!\(\*SubsuperscriptBox[\(Q\), \(1\), \(f\)]\),\!\(\*SubsuperscriptBox[\(Q\), \(2\), \(f\)]\),...,\!\(\*SubsuperscriptBox[\(Q\), \(n\), \(f\)]\)} is inaccessible from an initial operator \!\(\*SubscriptBox[\(Q\), \(i\)]\) under Hamiltonian evolution generated by the Hamiltonian algebra {\!\(\*SubscriptBox[\(H\), \(1\)]\),\!\(\*SubscriptBox[\(H\), \(2\)]\),..., \!\(\*SubscriptBox[\(H\), \(N\)]\)}.

The syntax distinguishes two cases:

1) InaccessibleOperatorQ[\!\(\*SubscriptBox[\(Q\), \(i\)]\) \[Rule] \!\(\*SubscriptBox[\(Q\), \(f\)]\), {\!\(\*SubscriptBox[\(H\), \(1\)]\),...,\!\(\*SubscriptBox[\(H\), \(N\)]\)}] returns True or False depending on whether \!\(\*SubscriptBox[\(Q\), \(f\)]\) is inaccessible from \!\(\*SubscriptBox[\(Q\), \(i\)]\) under {\!\(\*SubscriptBox[\(H\), \(1\)]\),...,\!\(\*SubscriptBox[\(H\), \(N\)]\)}-evolution.

2) InaccessibleOperatorQ[\!\(\*SubscriptBox[\(Q\), \(i\)]\) \[Rule] {\!\(\*SubsuperscriptBox[\(Q\), \(1\), \(f\)]\),\!\(\*SubsuperscriptBox[\(Q\), \(2\), \(f\)]\),...,\!\(\*SubsuperscriptBox[\(Q\), \(n\), \(f\)]\)}, {\!\(\*SubscriptBox[\(H\), \(1\)]\),...,\!\(\*SubscriptBox[\(H\), \(N\)]\)}] returns a list of True and False depending on whether the various {\!\(\*SubsuperscriptBox[\(Q\), \(1\), \(f\)]\),\!\(\*SubsuperscriptBox[\(Q\), \(2\), \(f\)]\),...,\!\(\*SubsuperscriptBox[\(Q\), \(n\), \(f\)]\)} are inaccessible from \!\(\*SubscriptBox[\(Q\), \(i\)]\) under {\!\(\*SubscriptBox[\(H\), \(1\)]\),...,\!\(\*SubscriptBox[\(H\), \(N\)]\)}-evolution.

An output of True indicates that the desired operator is not accessible from \!\(\*SubscriptBox[\(Q\), \(i\)]\) under {\!\(\*SubscriptBox[\(H\), \(1\)]\),...,\!\(\*SubscriptBox[\(H\), \(N\)]\)}-evolution. An output of False indicates that the operator may or may not be accessible from \!\(\*SubscriptBox[\(Q\), \(i\)]\) under {\!\(\*SubscriptBox[\(H\), \(1\)]\),...,\!\(\*SubscriptBox[\(H\), \(N\)]\)}-evolution.
";


(* ::Input::Initialization:: *)
$Chronology="LeftToRight";


(* ::Input::Initialization:: *)
Begin["`Private`"];


DualPairing::wrongnspins = "The number of spins should be an integer.";


DualPairing::wrongangularmomentum = "The angular momentum quantum number should be an integer of half-integer.";


NextPartition[p_]:=If[p[[1]]==1,{-1},Block[{k,q,l,s},For[k=PartitionLength[p],p[[k]]<=1,k=k-1];
q=Take[p,k-1];
l=p[[k]]-1;
While[(s=Plus@@p-Plus@@q)>=l,q=Append[q,l]];
If[s==0,q,Append[q,s]]]];

Partitions[n_]:=Partitions[n]=Block[{l,p},l={{n}};
For[p={n},(p=NextPartition[p])!={-1},None,l=Append[l,p]];l];

PartitionCompare[p_,q_]:=(PartitionLength[p]<=PartitionLength[q]&&(And@@Table[p[[i]]<=q[[i]],{i,1,PartitionLength[p]}]));

PartitionLength[p_]:=Length[PartitionTruncate[p]];

PartitionEval[p_,i_]:=If[i<=Length[p],p[[i]],0];

PartitionOrder[p_,q_]:=If[PartitionTruncate[p]==PartitionTruncate[q],0,If[First[Select[Table[PartitionEval[p,i]-PartitionEval[q,i],{i,1,Max[Length[p],Length[q]]}],#!=0&]]>0,1,-1]];

PartitionTruncate[p_]:=If[p=={}||p[[-1]]!=0,p,PartitionTruncate[Take[p,Length[p]-1]]];

PartitionValidate[p_]:=If[p=={}||And@@Table[p[[i]]>=p[[i+1]],{i,1,Length[p]-1}],True,Print["Partition values must descend"];False];

PartitionStrictlyCompare[p_,q_]:=(PartitionCompare[p,q]&&PartitionLength[q]<=PartitionLength[p]+1&&(And@@Table[p[[i]]==q[[i]]||q[[i+1]]<p[[i]]+1,{i,1,PartitionLength[q]-1}]));

AppendStrictTableau[t_,n_]:=(Append[t,#]&/@Select[Partitions[(Plus@@t[[-1]])+n],PartitionStrictlyCompare[t[[-1]],#]&]);

AppendStrictTableauList[l_,n_]:=Join@@(AppendStrictTableau[#,n]&/@l);

LRWord[t_]:=Join@@Table[Join@@Table[Table[j-1,{PartitionEval[t[[j]],i]-PartitionEval[t[[j-1]],i]}],{j,Length[t],2,-1}],{i,1,Length[t[[-1]]]}];

TestWord[w_]:=And@@Table[If[w[[i]]>1,Length[Select[Take[w,i],#==w[[i]]-1&]]>=Length[Select[Take[w,i],#==w[[i]]&]],True],{i,1,Length[w]}];

LRCandidates[p_,q_]:=Block[{r={{p}}},For[i=1,i<=PartitionLength[q],i++,r=AppendStrictTableauList[r,q[[i]]]];r];

LRTableau[p_,q_]:=Select[LRCandidates[PartitionTruncate[p],PartitionTruncate[q]],TestWord[LRWord[#]]&];

LRRule[p_,q_]:=If[PartitionValidate[p]&&PartitionValidate[q],Sort[#[[-1]]&/@LRTableau[p,q],PartitionOrder[#1,#2]>=0&],False];

LRRule[p_,q_,j1_]:=If[PartitionValidate[p]&&PartitionValidate[q],PadRight[#,2j1+1]&/@DeleteCases[Sort[#[[-1]]&/@LRTableau[p,q],PartitionOrder[#1,#2]>=0&],_?(Length[#]>2j1+1&)],False];

LRRuleSO3[A_,j1_]:=LRRule[A[[1]],A[[2]],j1];


isomorphismicreduction[Ylist_List,set_,nspins_]:=Flatten[isomorphismicreduction[#,set,nspins]&/@Ylist];

isomorphismicreduction[SNrep[tab:{(i_)..}],set_,nspins_]:=SNrep[ConstantArray[0,Length[tab]]];

isomorphismicreduction[SNrep[tab:{___}],set_,nspins_]:=Module[{Ystart,Ycycle,lengthcheck},
Ystart=constructisomorphism[SNrep[tab]];
Ycycle={Ystart};
While[!MemberQ[set,Ystart]&&!MemberQ[Ycycle,Ystart],
Ystart=constructisomorphism[Ystart];
Ycycle=Append[Ycycle,Ystart];
];
If[Total[Ystart[[1]]]<= nspins,Ystart,SNrep[tab]]
];

constructisomorphism[SNrep[tab:{___}]]:=transposetableuax@SNrep[Reverse[(ConstantArray[Total[tab],#]&@Length[tab])-tab]];
transposetableuax[SNrep[tab:{___}]]:=If[Union[(#>0)&/@tab]=={True},SNrep[tab-ConstantArray[Last[tab],Length[tab]]],SNrep[tab]];


SNdp[k_List]:=SNdp/@k;
SNdp[SNrep[tab_]]:=Module[{dim,krange},
dim=Length[tab];
krange=Range[dim-1];
Flatten@{Join[SNrep[tab+SparseArray[{1-> 1},dim]]],If[(tab[[#]]>tab[[#+1]])==True,SNrep[tab+SparseArray[{#+1-> 1},dim]],Nothing]&/@krange}
];


amcoupling[jlist:{{___}..},j_]:={amcoupling[#,j,"1"]}&/@jlist;

amcoupling[jlist:{A___},j2_,"1"]:=Total[Flatten[amcoupling[#,j2,"2"]&/@(List@@(A+"dummy")/.{"dummy"-> Nothing})]];

amcoupling[k_.*J[j1_],j2_,"2"]:=k*J/@Range[Abs[j1-j2],j1+j2,1];

amcoupling[{A_,B_}]:=Total@Flatten@Outer[amcoupling[#1,#2,"2"]&,(List@@(A+"dummy")/.{"dummy"-> Nothing}),(List@@(B+"dummy")/.{"dummy"-> Nothing}),1];

amcoupling[k1_.*J[0],k2_.*J[j2_],"2"]:=k1*k2 J[j2]/;(j2!= 0);

amcoupling[k2_.*J[j2_],k1_.*J[0],"2"]:=k1*k2 J[j2]/;(j2!= 0);

amcoupling[k1_.*J[j1_],k2_.*J[j2_],"2"]:=k1*k2 J/@Range[Abs[j1-j2],j1+j2,1];


pairingstep[{Ylist_,Jlist_,decomp_,nspins_},j1_]:=Module[{eqs1,eqs2,Yset,tupsraw,tupsY,SnxSmdecomp,SO3decomp,Yproductset,decomptemp},
Yset=decomp[[All,1]];
eqs1=Join[MapThread[Total[#1]==Total[#2]&,{Ylist,Jlist}],Flatten@{(Thread[Flatten[Ylist]==(isomorphismicreduction[Flatten[Ylist],Yset,nspins]/.decomp)]/.{True-> Nothing})}];
tupsraw=Select[Tuples[Rest@(Yset/.{SNrep[tab_]:> tab}),2],(Total[Flatten@#]<=nspins&)];
tupsY=tupsraw/.{tab:{i_Integer,___}:> SNrep[tab]};
SnxSmdecomp=LRRuleSO3[#,j1]&/@tupsraw;
SO3decomp=amcoupling[#]&/@(tupsY/.decomp);
Yproductset=DeleteDuplicates@(SNrep/@Flatten[SnxSmdecomp,1]);
eqs2=DeleteDuplicates@Join[Flatten@{(Thread[Yproductset==(isomorphismicreduction[Yproductset,Yset,nspins]/.decomp)]/.{True-> Nothing})},MapThread[Total[SNrep/@#1]==#2&,{SnxSmdecomp,SO3decomp}]];
decomptemp=DeleteDuplicates@Join[decomp,First@Quiet@Solve[Join[eqs1,eqs2]]];
{SNdp[Flatten[Ylist]],amcoupling[List/@(Flatten[Ylist]/.decomptemp),j1],decomptemp,nspins+1}
];

DualPairing[n_,j1_]:=Module[{dim,dummy,Ylist,Jlist,decomp,JstartRange},
If[IntegerQ[n], 
True, 
Message[DualPairing::wrongnspins];Abort[]
];
If[IntegerQ[2*j1], 
True, 
Message[DualPairing::wrongangularmomentum];Abort[]
];
dim=2j1+1;
JstartRange=Range[0,2j1];
decomp=If[IntegerQ[j1],
{SNrep[ConstantArray[0,dim]]-> J[0],
SNrep[Join[{1},ConstantArray[0,dim-1]]]->J[j1],
SNrep[Join[{2},ConstantArray[0,dim-1]]]->Total[J/@Select[JstartRange,EvenQ]],
SNrep[Join[{1,1},ConstantArray[0,dim-2]]]->Total[J/@Select[JstartRange,OddQ]]
},
{
SNrep[ConstantArray[0,dim]]-> J[0],
SNrep[Join[{1},ConstantArray[0,dim-1]]]->J[j1],
SNrep[Join[{2},ConstantArray[0,dim-1]]]->Total[J/@Select[JstartRange,OddQ]],
SNrep[Join[{1,1},ConstantArray[0,dim-2]]]->Total[J/@Select[JstartRange,EvenQ]]
}
];
Ylist={{SNrep[Join[{2},ConstantArray[0,dim-1]]]},{SNrep[Join[{1,1},ConstantArray[0,dim-2]]]}};
Jlist=List/@(Flatten[Ylist]/.decomp);
Multicolumn[dualpairingplot/@Cases[Rest[Nest[pairingstep[#,j1]&,{Ylist,Jlist,decomp,2},n-1][[3]]],_?(Total[#[[1,1]]]==n&)]]
];


dualpairingplot[SNrep[tab_]-> a_.*J[j_]]:=Multicolumn[{Grid[ConstantArray[Framed["  "],#]&/@DeleteCases[tab,0],Spacings->{.1,.1}],Text[Style["\[LeftRightArrow]",Bold,FontSize-> 15]],Text[Style[(a*J[j])/.{k_ J[j1_]:> Superscript[ToString[k]<>"\[Times]"<>"\[ScriptCapitalD]",j1],J[j1_]:> Superscript["\[ScriptCapitalD]",j1] },Bold,FontSize-> 15]]},3,Spacings->{1,1},Appearance->"Horizontal"];

dualpairingplot[SNrep[tab_]-> Plus[A___]]:=Module[{sumlist,nsum,\[CapitalGamma]table,YoungGrid},
sumlist=List@@Plus[A];
\[CapitalGamma]table=sumlist/.{k_ J[j1_]:> Superscript[ToString[k]<>"\[Times]"<>"\[ScriptCapitalD]",j1],J[j1_]:> Superscript["\[ScriptCapitalD]",j1] };
nsum=Length[sumlist];
YoungGrid=Grid[ConstantArray[Framed["  "],#]&/@DeleteCases[tab,0],Spacings->{.1,.1}];
Multicolumn[{YoungGrid,Text[Style["\[LeftRightArrow]",Bold,FontSize-> 15]],Sequence@@(Text[Style[#,Bold,FontSize-> 15]]&/@Riffle[\[CapitalGamma]table,"\[CirclePlus]"])},2nsum+1,Spacings->{.5,.5},Appearance-> "Horizontal"]
];


Options[LieAlgebra]={OperatorBasis:>OperatorBasis[],Basis:>Basis[],LieAlgebraField:>"R"};


LieAlgebra[operators_,args___,opts___Rule]/;(!MatchQ[listcheck[Flatten[{operators}]],listcheck[operators]]):=(Message[LieAlgebra::notQlist];$Failed);


LieAlgebra[operators_,args___,opts___Rule]/;Or@@(Union[OperatorQ/@Flatten[{operators}]]!={True}):=(Message[LieAlgebra::notQ];$Failed);


LieAlgebra[operators_,args___,opts___Rule]/;Or@@((Tr[MatrixRepresentation[#]]!=0)&/@Flatten[{operators}]):=(Message[LieAlgebra::nottraceless];$Failed);


LieAlgebra[opset_,opts___Rule]:=Module[{field,ddots,opbasis,basis,la,lb,setA,setB,comms,commsAB},
opbasis=OperatorBasis/.{opts}/.Options[LieAlgebra];
basis=Basis/.{opts}/.Options[LieAlgebra];
field=LieAlgebraField/.{opts}/.Options[LieAlgebra];
setA=SparseArray/@(MatrixRepresentation[#,basis]&/@opset);
ddots=DownValues[Dot];
Unprotect[Dot];
DownValues[Dot]={};
setB=setA;
la=Length[setA];
lb=Length[setB];
comms=Flatten[Table[{a,b},{a,1,la},{b,a,lb}],1];
commsAB=-I(setA[[#[[1]]]] . setB[[#[[2]]]]-setB[[#[[2]]]] . setA[[#[[1]]]])&/@comms;
setA=LieAlgebraLinIndepOperators[Join[setA,commsAB],field];
la=0;
While[Length[setA]!=la,
setB=setA[[la+1;;]];
la=Length[setA];
lb=Length[setB];
comms=Flatten[Table[{a,b},{a,1,la},{b,1,lb}],1];
commsAB=-I(setA[[#[[1]]]] . setB[[#[[2]]]]-setB[[#[[2]]]] . setA[[#[[1]]]])&/@comms;
setA=LieAlgebraLinIndepOperators[Join[setA,commsAB],field];
];
DownValues[Dot]=ddots;
Protect[Dot];
Simplify[ExpressOperator[#,opbasis]&/@(Operator[#,basis]&/@setA)]
]


LieAlgebraLinIndepOperators[ops_,"R"]:=Module[{rre,dim,j,pivot,pivotpos},
dim=Length[ops];
rre=RowReduce[Transpose[Join[Re[#],Im[#]]&/@Flatten/@ops]];
j=1;
pivot=FirstPosition[rre[[j]],1];
pivotpos={pivot};
While[!MatchQ[pivot,Missing["NotFound"]]\[And]j<dim+1,
j=j+1;
pivot=FirstPosition[rre[[j]],1];
AppendTo[pivotpos,pivot];
];
ops[[Flatten[pivotpos/.{Missing["NotFound"]->Nothing}]]]
]

LieAlgebraLinIndepOperators[ops_,"C"]:=Module[{rre,dim,j,pivot,pivotpos},
dim=Length[ops];
rre=RowReduce[Transpose[Flatten/@ops]];
j=1;
pivot=FirstPosition[rre[[j]],1];
pivotpos={pivot};
While[!MatchQ[pivot,Missing["NotFound"]]\[And]j<dim+1,
j=j+1;
pivot=FirstPosition[rre[[j]],1];
AppendTo[pivotpos,pivot];
];
ops[[Flatten[pivotpos/.{Missing["NotFound"]->Nothing}]]]
]


(*LieAlgebra[opset_,opts___Rule]:=Module[{opbasis,basis,l1,l2,setA,setB,setOB,norm,ddots},
opbasis=OperatorBasis/.{opts}/.{OperatorBasis\[Rule]OperatorBasis[]};
basis=Basis/.{opts}/.{Basis\[Rule]Basis[]};
setA=SparseArray/@(MatrixRepresentation[#,basis]&/@opset);
ddots=DownValues[Dot];
Unprotect[Dot];
ddots=DownValues[Dot];
setB=setA;
l1=0;
l2=1;
While[l1\[NotEqual]l2,
l1=Length[setA];
setB=DeleteCases[Flatten[-I Chop@Outer[#1.#2-#2.#1&,setA,setB,1],1],_?(MatchQ[#["NonzeroPositions"],{}]&)];
setOB=setA;
Table[AppendTo[setOB,
setB\[LeftDoubleBracket]i\[RightDoubleBracket]-Sum[
norm=Chop[Tr[ConjugateTranspose[setOB\[LeftDoubleBracket]j\[RightDoubleBracket]].setOB\[LeftDoubleBracket]j\[RightDoubleBracket]]];
If[norm\[Equal]0,0,setOB\[LeftDoubleBracket]j\[RightDoubleBracket]Tr[ConjugateTranspose[setOB\[LeftDoubleBracket]j\[RightDoubleBracket]].setB\[LeftDoubleBracket]i\[RightDoubleBracket]]/norm],{j,1,Length[setOB]}]],
{i,1,Length[setB]}];
setA=DeleteCases[Chop[setOB],_?(MatchQ[#["NonzeroPositions"],{}]&)];
setB=setA\[LeftDoubleBracket]l1+1;;\[RightDoubleBracket];
l2=Length[setA];
];
DownValues[Dot]=ddots;
Protect[Dot];
Simplify[ExpressOperator[#,opbasis]&/@(Operator[#,basis]&/@setA)]
]*)


LieAlgebra::notQlist="The arguments of LieAlgebra must be a set/list of operators."; 


LieAlgebra::nottraceless="The arguments of LieAlgebra must be traceless."; 


LieAlgebra::notQ="At least one of the arguments is not a valid operator argument."; 


Options[InaccessibleOperatorQ]={OperatorBasis:> OperatorBasis[],Basis:>Basis[]};


(* ::Input::Initialization:: *)
InaccessibleOperatorQ[args___]:=InaccessibleOperatorQ[args,{"1","0"}];


(* ::Input::Initialization:: *)
InaccessibleOperatorQ[Qa_->Qb_,Halg_,opts___Rule,{"1","0"}]:=Which[
MatchQ[{True},DeleteDuplicates@Join[{OperatorQ[Qa],OperatorQ[Qb]},OperatorQ/@Halg]],
InaccessibleOperatorQ[Qa->Qb,Halg,opts,{"2","1"}],
MatchQ[{True},DeleteDuplicates@Join[{OperatorQ[Qa]},OperatorQ/@Flatten[{Qb}],OperatorQ/@Halg]],
InaccessibleOperatorQ[Qa->Qb,Halg,opts,{"2","2"}],
True,Message[InaccessibleOperatorQ::wrongInput];Abort[];
]
InaccessibleOperatorQ[args___,{"1","0"}]:=(Message[InaccessibleOperatorQ::wrongInput];Abort[];)


InaccessibleOperatorQ[Qa_->Qb_,Halg_,opts___Rule,{"2","1"}]:=First@InaccessibleOperatorQ[Qa->{Qb},Halg,opts,{"2","2"}]


InaccessibleOperatorQ[Qa_->Qbset_,Halg:{_?OperatorQ..},opts___Rule,{"2","2"}]:=Module[{ddots,opbasis,basis,field,Halgmats,Qamat,Qbmats,commops,accset,la,lb},
opbasis=OperatorBasis/.{opts}/.Options[LieAlgebra];
basis=Basis/.{opts}/.Options[LieAlgebra];
field=LieAlgebraField/.{opts}/.Options[LieAlgebra];
Halgmats=SparseArray/@(MatrixRepresentation[#,basis]&/@Halg);
Qamat=(MatrixRepresentation[Qa,basis])//Simplify;
Qbmats=(MatrixRepresentation[#,basis]&/@Qbset)//Simplify;
ddots=DownValues[Dot];
Unprotect[Dot];
DownValues[Dot]={};
commops=Join[{Qamat},-I(# . Qamat-Qamat . #)&/@Halgmats];
accset=Simplify[#/Sqrt[Tr[ConjugateTranspose[#] . #]]]&/@commops[[rrefgetpivots[RowReduce[Transpose[Flatten/@commops]]]]];
la=1;
lb=0;
If[Length[accset]==0,
DownValues[Dot]=ddots;
Protect[Dot];
ConstantArray[True,Length[Qbset]],
While[la!=lb,
la=Length[accset];
commops=Flatten[Outer[-I(#2 . #1-#1 . #2)&,Halgmats,accset,1],1];
commops=Join[accset,commops];
accset=Simplify[#/Sqrt[Tr[ConjugateTranspose[#] . #]]]&/@commops[[rrefgetpivots[RowReduce[Transpose[Flatten/@commops]]]]];
lb=Length[accset];
];
DownValues[Dot]=ddots;
Protect[Dot];
MatchQ[Chop[Conjugate[Flatten/@N[accset]] . Flatten[#]],{0..}]&/@Qbmats
]
]


InaccessibleOperatorQ::wrongInput="The provided operator arguments do not match the expected syntax. 

1) InaccessibleOperatorQ[\!\(\*SubscriptBox[\(Q\), \(i\)]\) \[Rule] \!\(\*SubscriptBox[\(Q\), \(f\)]\), {\!\(\*SubscriptBox[\(H\), \(1\)]\),...,\!\(\*SubscriptBox[\(H\), \(N\)]\)}] or

2) InaccessibleOperatorQ[\!\(\*SubscriptBox[\(Q\), \(i\)]\) \[Rule] {\!\(\*SubsuperscriptBox[\(Q\), \(f\), \(1\)]\),\!\(\*SubsuperscriptBox[\(Q\), \(2\), \(f\)]\),...,\!\(\*SubsuperscriptBox[\(Q\), \(n\), \(f\)]\)}, {\!\(\*SubscriptBox[\(H\), \(1\)]\),...,\!\(\*SubscriptBox[\(H\), \(N\)]\)}]
"; 


Options[AbelianSubalgebra]={OperatorBasis:>OperatorBasis[],Basis:>Basis[]};


(* ::Input::Initialization:: *)
AbelianSubalgebra[args___]:=AbelianSubalgebra[args,{"1","0"}];


(* ::Input::Initialization:: *)
AbelianSubalgebra[args_,opts___Rule,{"1","0"}]:=Which[
MatchQ[args,{_?OperatorQ..}],
AbelianSubalgebra[args,opts,{"2","1"}],
MatchQ[args,{{_?OperatorQ..},{_?OperatorQ..}}],
AbelianSubalgebra[args,opts,{"2","2"}],
True,Message[AbelianSubalgebra::notQlist];Abort[];
]
AbelianSubalgebra[args___,{"1","0"}]:=(Message[AbelianSubalgebra::notQlist];Abort[];)


rrefgetpivots[rre_]:=Module[{j,pivot,pivotpos,maxdim},
maxdim=Dimensions[rre][[2]];
j=1;
pivot=FirstPosition[rre[[j]],1];
pivotpos={pivot};
While[!MatchQ[pivot,Missing["NotFound"]]\[And]j<maxdim+1,
j=j+1;
pivot=FirstPosition[rre[[j]],1];
AppendTo[pivotpos,pivot];
];
Flatten[pivotpos/.{Missing["NotFound"]->Nothing}]
]


AbelianSubalgebra[operators:{___},opts___Rule,{"2","1"}]:=Module[{idop,bops,opbasis,abelianalg,nsQ,nsA,nsB,temp,pivots,la,lb},
opbasis=OperatorBasis/.{opts}/.Options[AbelianSubalgebra];
bops=BasisOperators[opbasis];
abelianalg=OperatorVectorRepresentation[#,opbasis]&/@operators;
nsQ=SparseArray@NullSpace[SuperoperatorMatrixRepresentation[CommutationSuperoperator[#],opbasis]]&/@operators;
nsA=SparseArray@If[Length[operators]==1,First[nsQ],Fold[VectorSpaceIntersection[#1,#2]&,First[nsQ],Rest[nsQ]]];
temp=Join[abelianalg,nsA];
pivots=rrefgetpivots[RowReduce[Transpose[temp]]];
la=Length[abelianalg];
lb=Length[pivots];
While[la!=lb,
AppendTo[abelianalg,temp[[pivots[[la+1]]]]];
la=Length[abelianalg];
nsB=SparseArray@NullSpace[SuperoperatorMatrixRepresentation[CommutationSuperoperator[Last[abelianalg] . bops],opbasis]];
nsA=SparseArray@VectorSpaceIntersection[nsA,nsB];
temp=Join[abelianalg,nsA];
pivots=rrefgetpivots[RowReduce[Transpose[temp]]];
lb=Length[nsA]];
idop=OperatorVectorRepresentation[UnityOperator[]/Sqrt[BasisDimension[]],opbasis];
DeleteCases[((#-idop . # idop)&/@abelianalg) . bops//Simplify//Chop,0]
]


AbelianSubalgebra[{operators_,alg_},opts___Rule,{"2","2"}]:=Module[{opbasis,idop,abelianalg,projL,projq,nsQ,nsA,nsB,temp,pivots,la,lb},
opbasis=OperatorBasis/.{opts}/.Options[AbelianSubalgebra];
projL=OperatorVectorRepresentation[#,opbasis]&/@alg//SparseArray//Conjugate;
abelianalg=projL . OperatorVectorRepresentation[#,opbasis]&/@operators;
nsQ=SparseArray@NullSpace[projL . SuperoperatorMatrixRepresentation[CommutationSuperoperator[#],opbasis] . ConjugateTranspose[projL]]&/@operators;
nsA=SparseArray@If[Length[operators]==1,First[nsQ],Fold[VectorSpaceIntersection[#1,#2]&,First[nsQ],Rest[nsQ]]];
temp=Join[abelianalg,nsA];
pivots=rrefgetpivots[RowReduce[Transpose[temp]]];
la=Length[abelianalg];
lb=Length[pivots];
While[la!=lb,
AppendTo[abelianalg,temp[[pivots[[la+1]]]]];
la=Length[abelianalg];
nsB=SparseArray@NullSpace[projL . SuperoperatorMatrixRepresentation[CommutationSuperoperator[Last[abelianalg] . alg],opbasis] . ConjugateTranspose[projL]];
nsA=SparseArray@VectorSpaceIntersection[nsA,nsB];
temp=Join[abelianalg,nsA];
pivots=rrefgetpivots[RowReduce[Transpose[temp]]];
lb=Length[nsA]];
idop=projL . OperatorVectorRepresentation[UnityOperator[]/Sqrt[BasisDimension[]],opbasis];
DeleteCases[((#-idop . # idop)&/@abelianalg) . alg//Simplify//Chop,0]
]


AbelianSubalgebra::notQlist="The arguments of AbelianSubalgebra must be a set/list of operators."; 


Options[MaximalAbelianQ]={OperatorBasis:>OperatorBasis[],Basis:>Basis[]};


(* ::Input::Initialization:: *)
MaximalAbelianQ[args___]:=MaximalAbelianQ[args,{"1","0"}];


(* ::Input::Initialization:: *)
MaximalAbelianQ[args_,opts___Rule,{"1","0"}]:=Which[
MatchQ[args,{_?OperatorQ..}],
MaximalAbelianQ[args,opts,{"2","1"}],
MatchQ[args,{{_?OperatorQ..},{_?OperatorQ..}}],
MaximalAbelianQ[args,opts,{"2","2"}],
True,Message[MaximalAbelianQ::notQlist];Abort[];
]
MaximalAbelianQ[args___,{"1","0"}]:=(Message[MaximalAbelianQ::notQlist];Abort[];)


MaximalAbelianQ[alg_,opts___Rule,{"2","1"}]:=Module[{somats,opbasis,basis,algdim,dim},
opbasis=OperatorBasis/.{opts}/.Options[MaximalAbelianQ];
dim=BasisDimension[];
algdim=Length[alg];
somats=(SuperoperatorMatrixRepresentation[CommutationSuperoperator[#],opbasis]&/@alg);
((dim^2-1)-MatrixRank[RandomReal[{-100,100},algdim] . somats])==algdim
]


MaximalAbelianQ[{operators_,algebra_},opts___Rule,{"2","2"}]:=Module[{projalg,somats,opbasis,algdim,opdim},
opbasis=OperatorBasis/.{opts}/.Options[MaximalAbelianQ];
algdim=Length[algebra];
opdim=Length[operators];
projalg=OperatorVectorRepresentation[#,opbasis]&/@algebra//SparseArray;
somats=(projalg . SuperoperatorMatrixRepresentation[CommutationSuperoperator[#],opbasis] . ConjugateTranspose[projalg]&/@operators);
(algdim-MatrixRank[RandomReal[{-100,100},opdim] . somats])==opdim
]


MaximalAbelianQ::notQlist="The arguments of MaximalAbelianQ must be a set/list of operators."; 


MaximalAbelianQ::nottraceless="The arguments of MaximalAbelianQ must be traceless."; 


MaximalAbelianQ::notQ="At least one of the arguments is not a valid operator argument."; 


(* ::Input::Initialization:: *)
End[];
EndPackage[];



