(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["GroupsAndAlgebras`SpinPermutationGroups`",
{"Global`",
"SpinDynamica`",
"General`UserLevel`",
"QM`SpinOperators`",
"QM`Hilbert`",
"QM`Liouville`",
"GroupsAndAlgebras`Commutant`",
"Tensors`CG`",
"General`Matrices`",
"General`General3D`",
"General`Miscellaneous`"
}];


(* ::Input::Initialization:: *)
SpinPermutationGroup::usage="SpinPermutationGroup may be used to generate a set of operators that represents the specified group in terms of SpinPermutationOperators. The syntax for SpinPermutationGroup follows: SpinPermutationGroup[{\"GroupName\",GroupOrder}], where \"GroupName\" refers to the name of the group as a string and GroupOrder refers to the order of the group as an integer. For example, SpinPermutationGroup[{\"SymmetricGroup\",3}]. A list of supported groups may be found by executing the command \"FiniteGroupData[]\".";


(* ::Input::Initialization:: *)
SpinPermutationGroupOperators::usage ="SpinPermutationGroupOperators is an abstract representation of the SpinPermutationOperators forming a given SpinPermutationGroup.";


(* ::Input::Initialization:: *)
SpinPermutationGroupElements::usage ="SpinPermutationGroupElements may be used to extract the group elements of a given SpinPermutationGroup, for example SpinPermutationGroupElements[SpinPermutationGroup[{\"SymmetricGroup\",3}]].";


(* ::Input::Initialization:: *)
SymmetryAdaptedBasis::usage ="SymmetryAdaptedBasis constructs a symmetry-adapted basis of spin states. 

The syntax SymmetryAdaptedBasis[spinsys, {\"GroupName\", n}, opts] may be used for exact calculations, where \"GroupName\" refers to the name of the group as a string, and n refers to the order of the group. Exact calculations are currently only supported for {\"SymmetricGroup\", \"CyclicGroup\"}. For example, the command SymmetryAdaptedBasis[{{1,1/2},{2,1/2},{3,1/2}}, {\"SymmetricGroup\", 3}, opts] defines a symmetry-adapted basis for three-spin-1/2 particles with respect to the group \!\(\*SubscriptBox[\(S\), \(3\)]\). 

For arbitraty permutation groups the syntax SymmetryAdaptedBasis[spinsys, {{\"GroupName\", n}, {\!\(\*SubscriptBox[\(p\), \(1\)]\),\!\(\*SubscriptBox[\(p\), \(2\)]\),...}},] may be used for numerical calculations. Here, the set {\!\(\*SubscriptBox[\(p\), \(1\)]\),\!\(\*SubscriptBox[\(p\), \(2\)]\),...} represents the corresponding group elements in the form of SpinDynamica spin permutation operators. For example, the command SymmetryAdaptedBasis[{{1,1/2},{2,1/2}}, {{\"AlternatingGroup\", 2},{SpinPermutationOperator[{}],SpinPermutationOperator[{1,2}]}}] defines a symmetry-adapted basis for two-spin-1/2 particles with respect to the group \!\(\*SubscriptBox[\(A\), \(2\)]\).

If the spin system specifications are omitted SymmetryAdaptedBasis will try to work with the currently active spin system.";


SymmetryAdaptedBasisTFM::usage = "Internal SpinDynamica function for the calculation of symmetry-adapted basis functions.";


ConsistentIsotopicPhase::usage = "Internal SpinDynamica function to enforce conistent phase relations between equivalent irreducible representations.";


ConsistentIsotopicPhaseU::usage = "Internal SpinDynamica function to enforce conistent phase relations between equivalent irreducible representations.";


(* ::Input::Initialization:: *)
$Chronology="LeftToRight";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
Options[SpinPermutationGroup]={};


(* ::Input::Initialization:: *)
SpinPermutationGroup[args___]:=SpinPermutationGroup[args,{"1","0"}];


(* ::Input::Initialization:: *)
SpinPermutationGroup[spins___List,gargs_,opts___Rule,{"1","0"}]:=Module[{permgroup},
permgroup=Quiet[FiniteGroupData[gargs,"PermutationRepresentation"]];
If[!MatrixQ[permgroup],
Message[SpinPermutationGroup::WrongInput];Abort[];,
SpinPermutationGroup[spins,{permgroup,Length[First[permgroup]]},SpinPermutationGroup-> gargs,opts,{"1","1"}]]
]


(* ::Input::Initialization:: *)
SpinPermutationGroup[spins_List,{permgroup_,order_},opts___Rule,{"1","1"}]:=SpinPermutationGroup[spins,{permgroup,order},opts,{"1","2"}]
SpinPermutationGroup[{permgroup_,order_},opts___Rule,{"1","1"}]:=SpinPermutationGroup[Range[Length[SpinSystem[]]],{permgroup,order},opts,{"1","2"}]


(* ::Input::Initialization:: *)
SpinPermutationGroup[spins_List,{permgroup_,order_},opts___Rule,{"1","2"}]:=If[
order>Length[DeleteDuplicates@spins]\[Or]Length[spins]>Length[SpinSystem[]],
Message[SpinPermutationGroup::WrongOrder];Abort[];,
SpinPermutationGroup[spins[[Range[order]]],{permgroup,order},opts,{"1","3"}]
]


(* ::Input::Initialization:: *)
SpinPermutationGroup[spins_List,{permgroup_,order_},opts___Rule,{"1","3"}]:=If[
AllTrue[spins,IntegerQ],
SpinPermutationGroup[spins,{permgroup,order},opts,{"1","4"}],
Message[SpinPermutationGroup::SpinIndex];Abort[];
]


(* ::Input::Initialization:: *)
SpinPermutationGroup[spins_List,{permgroup_,order_},opts___Rule,{"1","4"}]:=If[
AllTrue[spins,ValidSpinQ],
SpinPermutationGroup[spins,{permgroup,order},opts,{"1","5"}],
Message[SpinPermutationGroup::SpinInvalid];Abort[];
]


(* ::Input::Initialization:: *)
SpinPermutationGroup[spins_List,{permgroup_,order_},opts___Rule,{"1","5"}]:=If[
Length[DeleteDuplicates[SpinSystem[][[spins]][[All,2]]]]==1,
SpinPermutationGroup[spins,{permgroup,order},opts,{"2","0"}],
Message[SpinPermutationGroup::SpinIvals];Abort[];
]


(* ::Input::Initialization:: *)
SpinPermutationGroup::WrongInput= "The group has not been recognised or is too large to be handled at this stage. Consult \"FiniteGroupData[]\" for an overview of all available groups.";


(* ::Input::Initialization:: *)
SpinPermutationGroup::WrongOrder= "The group order does not agree with the number of spins.";


(* ::Input::Initialization:: *)
SpinPermutationGroup::SpinIndex= "The spin indices with respect to the active spin system should be a list of integers.";


(* ::Input::Initialization:: *)
SpinPermutationGroup::SpinInvalid= "At least one of the spin indices does not represent a valid spin for the current spin system.";


(* ::Input::Initialization:: *)
SpinPermutationGroup::SpinIvals= "SpinPermutationGroup may only be used for spins with identical spin quantum numbers.";


(* ::Input::Initialization:: *)
SpinPermutationGroup[spins_List,{permgroup_,order_},opts___Rule,{"2","0"}]:=Module[{grname,grorder,Gops},
grname=First[SpinPermutationGroup/.{opts}];
grorder=Last[SpinPermutationGroup/.{opts}];
Gops=SpinPermutationOperator/@Sort[(GroupElements[PermutationGroup[permgroup]][[All,1]])/.Thread[Range[order]-> spins]];
SpinPermutationGroupOperators[{{grname,grorder},Gops},spins]
]


(* ::Input::Initialization:: *)
SpinPermutationGroupOperators::WrongIndex="The requested index is out of bounds.";


(* ::Input::Initialization:: *)
SpinPermutationGroupElements::WrongArg="SpinPermutationGroupElements may only be applied to SpinPermutationGroupOperators.";


(* ::Input::Initialization:: *)
Format[SpinPermutationGroupOperators[{{gr_String,n_Integer},Gops_},spins_]]:=
RowBox[{
"\[ScriptCapitalG]["<>ToString[SpinSystem[][[spins]]/.{Rational[a_,b_]:> ToString[a]<>"/"<>ToString[b]}]<>",{"<>gr<>","<>ToString[n]<>"}]"}]//DisplayForm;


(* ::Input::Initialization:: *)
SpinPermutationGroupOperators[{{gr_String,n_Integer},G_},spinsys_][m_Integer]/;(1<=m<=Length[G] ):=G[[m]]
SpinPermutationGroupOperators[{{gr_String,n_Integer},G_},spinsys_][m_Integer]:=(
Message[SpinPermutationGroupOperators::WrongIndex];Abort[]);


(* ::Input::Initialization:: *)
SpinPermutationGroupElements[SpinPermutationGroupOperators[{{gr_String,n_Integer},G_},spinsys_]]:=G;


(* ::Input::Initialization:: *)
SpinPermutationGroupElements[{gr_String,n_Integer}]:=SpinPermutationGroupElements[SpinPermutationGroup[{gr,n}]];


(* ::Input::Initialization:: *)
SpinPermutationGroupElements[a_]:=(Message[SpinPermutationGroupElements::WrongArg];Abort[];)


(* ::Input::Initialization:: *)
SymmetryAdaptedBasis::inconsistentspinsys ="The specified spin system is inconsistent with the active spin system.";


(* ::Input::Initialization:: *)
SymmetryAdaptedBasis::incompatibleI ="The spin angular momentum numbers are not identical for all spins.";


(* ::Input::Initialization:: *)
SymmetryAdaptedBasis::gnotknown ="The specified group is not supported for exact calculations.";


(* ::Input::Initialization:: *)
SymmetryAdaptedBasis::order ="The degree of the group is not consistent with the number of spins.";


(* ::Input::Initialization:: *)
SymmetryAdaptedBasis::gnotq ="The group elements are not in operator form.";


(* ::Input::Initialization:: *)
SymmetryAdaptedBasis::spinsys ="The spin system is invalid.";


(* ::Input::Initialization:: *)
DownValues[DefinedBasisQ]=DownValues[DefinedBasisQ]/.{HoldPattern[DefinedBasisQ[Except[_ZeemanBasis|_AngularMomentumBasis|_SingletTripletBasis|_Eigenbasis|_TransformedBasis|_ProductBasis]]]-> HoldPattern[DefinedBasisQ[Except[_ZeemanBasis|_AngularMomentumBasis|_SingletTripletBasis|_Eigenbasis|_TransformedBasis|_ProductBasis|_SymmetryAdaptedBasis]]]};


(* ::Input::Initialization:: *)
Options[SymmetryAdaptedBasis]={BasisLabels-> Automatic,Ordering-> Automatic};


(* ::Input::Initialization:: *)
SetAttributes[SymmetryAdaptedBasis,NHoldFirst]


(* ::Input::Initialization:: *)
SymmetryAdaptedBasis[Undefined]:=(Message[SpinSystem::notready];Undefined);


(* ::Input::Initialization:: *)
SymmetryAdaptedBasis[opts___Rule]:=With[{n=Length[SpinSystem[]]},SymmetryAdaptedBasis[SpinSystem[],SpinPermutationGroup[{"SymmetricGroup",n}],opts]]


(* ::Input::Initialization:: *)
SymmetryAdaptedBasis[{grlabel_String,order_Integer},opts___Rule]:=If[
MatchQ[grlabel,"CyclicGroup"],
SymmetryAdaptedBasis[SpinSystem[],SpinPermutationGroupOperators[{{grlabel,order},SpinPermutationOperator/@GroupElements[CyclicGroup[order]][[All,1]]},SpinSystem[][[All,1]]],opts],
SymmetryAdaptedBasis[SpinSystem[],SpinPermutationGroup[{grlabel,order}],opts]
]

SymmetryAdaptedBasis[{{grlabel_String,order_Integer},gops_},opts___Rule]:=SymmetryAdaptedBasis[SpinSystem[],SpinPermutationGroupOperators[{{grlabel,order},gops},SpinSystem[][[All,1]]],opts]

SymmetryAdaptedBasis[spinsys_,{grlabel_String,order_Integer},opts___Rule]:=(Which[
Length[spinsys]!=order,Message[SymmetryAdaptedBasis::order];Abort[];,
Length[DeleteDuplicates[spinsys[[All,2]]]]!=1,Message[SymmetryAdaptedBasis::incompatibleI];Abort[];,
ValidSpinQ[spinsys[[All,1]]]!= True,Message[SymmetryAdaptedBasis::inconsistentspinsys ];Abort[];,
MatchQ[grlabel,"CyclicGroup"],
SymmetryAdaptedBasis[spinsys,SpinPermutationGroupOperators[{{grlabel,order},SpinPermutationOperator/@GroupElements[CyclicGroup[order]][[All,1]]},spinsys[[All,1]]],opts],
True==True,
SymmetryAdaptedBasis[spinsys,SpinPermutationGroup[spinsys[[All,1]],{grlabel,order}],opts]
])

SymmetryAdaptedBasis[spinsys_,{{grlabel_String,order_Integer},gops_},opts___Rule]:=Which[
Length[spinsys]!=order,Message[SymmetryAdaptedBasis::order];Abort[];,
Length[DeleteDuplicates[spinsys[[All,2]]]]!=1,Message[SymmetryAdaptedBasis::incompatibleI];Abort[];,
ValidSpinQ[spinsys[[All,1]]]!= True,Message[SymmetryAdaptedBasis::inconsistentspinsys ];Abort[];,
True==True,
SymmetryAdaptedBasis[spinsys,SpinPermutationGroupOperators[{{grlabel,order},gops},spinsys[[All,1]]],opts]
]


(* ::Input::Initialization:: *)
DefinedBasisQ[SymmetryAdaptedBasis[spinsys_?MatrixQ,G_,opts___Rule]]=True;


(* ::Input::Initialization:: *)
BasisDimension[SymmetryAdaptedBasis[spinsys_?MatrixQ,G_,opts___Rule]]:=Times@@((2*#+1)&/@Last[ Transpose[spinsys]]);


(* ::Input::Initialization:: *)
BasisKets[SymmetryAdaptedBasis[spinsys_?MatrixQ,G_,opts___Rule]]:=BasisKets[SymmetryAdaptedBasis[spinsys,G,opts]]=SymmetryAdaptedBasisTFM[SymmetryAdaptedBasis[spinsys,G,opts],ZeemanBasis[spinsys]] . BasisKets[ZeemanBasis[spinsys]]


(* ::Input::Initialization:: *)
BasisBras[SymmetryAdaptedBasis[spinsys_?MatrixQ,G_,opts___Rule]]:=BasisBras[SymmetryAdaptedBasis[spinsys,G,opts]]=
Conjugate[BasisKets[SymmetryAdaptedBasis[spinsys,G,opts]]]/.{Conjugate-> Identity}/.{Ket-> Bra};


(* ::Input::Initialization:: *)
SpinSystem[SymmetryAdaptedBasis[spinsys_?MatrixQ,G_,opts___Rule]]^:=spinsys;


(* ::Input::Initialization:: *)
SymmetryAdaptedBasisTFM[basis2_,basis1:SymmetryAdaptedBasis[args___]]:=(ConjugateTranspose[SymmetryAdaptedBasisTFM[basis1,basis2]]);


(* ::Input::Initialization:: *)
SymmetryAdaptedBasisTFM[SymmetryAdaptedBasis[spinsys_,SpinPermutationGroupOperators[{{"SymmetricGroup",n_},group_},spinlist_],opts___Rule],basis1_]:=
Module[{
spins,
K1,K2,K3,K4,CSCO,G,dimG,
ev,vecs,Gmats,X,Xinv,\[Xi]vec,
G\[CapitalGamma]\[Gamma]mats,\[CapitalGamma]\[Gamma]subspaces,\[CapitalGamma]\[Gamma]order,
vecs\[CapitalGamma]\[Gamma]sorted,X\[CapitalGamma]\[Gamma]sorted,X\[CapitalGamma]\[Gamma]invsorted,\[Xi]vec\[CapitalGamma]\[Gamma]sorted,
\[CapitalGamma]\[Gamma]cuts,\[CapitalGamma]\[Gamma]bounds,\[CapitalGamma]\[Gamma]spaces,
SpacePartition,IsotopicSpaces,truepos,dim\[CapitalGamma]s,
phasetransformations,phasetransformation,
V,K3\[CapitalGamma],K4\[CapitalGamma],dimvec},
spins=First[Transpose[spinsys]];
K1=Sum[SpinPermutationOperator[{spins[[i]],spins[[j]]},spinsys],{i,1,n-1},{j,i+1,n}];
K2=SpinPermutationOperator[spins,spinsys];
K3=Sum[(opI[spins[[i]]]) . (opI[spins[[j]]]),{i,1,n},{j,1,n}];
K4=opI[spins,"z"];
G=(SpinPermutationOperator[If[MatchQ[#,{{__}}],#[[1]],#],spinsys])&/@(Sort[GroupElements[SymmetricGroup[n]][[All,1]]]/.Thread[Range[n]-> spins]);
CSCO={K1,K2,K3,K4};
dimG=Length[G];
{ev,vecs}=Chop@Eigensystem[MatrixRepresentation[RandomInteger[{-100,100},Length[CSCO]] . CSCO,basis1]];
vecs=vecs//Normal//FullSimplify;
vecs=FullSimplify[#/Sqrt[# . Conjugate[#]]]&/@vecs;
Gmats=MatrixRepresentation[#,basis1]&/@G;
X=Transpose[vecs]//SparseArray;
Xinv=ConjugateTranspose[X];
\[Xi]vec=Normal[Xinv . (MatrixRepresentation[CSCO[[1]],basis1]) . X//N//Chop//Diagonal];

G\[CapitalGamma]\[Gamma]mats=Simplify[Chop[Xinv . # . X]]&/@Gmats;
\[CapitalGamma]\[Gamma]subspaces=SortBy[ConnectedComponents[Rule@@@Chop[Total[RandomReal[{-100,100},dimG]*G\[CapitalGamma]\[Gamma]mats]]["NonzeroPositions"]],Length];
\[CapitalGamma]\[Gamma]order=Flatten[\[CapitalGamma]\[Gamma]subspaces];
vecs\[CapitalGamma]\[Gamma]sorted=vecs[[\[CapitalGamma]\[Gamma]order]];
X\[CapitalGamma]\[Gamma]sorted=Transpose[vecs\[CapitalGamma]\[Gamma]sorted]//SparseArray;
X\[CapitalGamma]\[Gamma]invsorted=ConjugateTranspose[vecs\[CapitalGamma]\[Gamma]sorted];
\[Xi]vec\[CapitalGamma]\[Gamma]sorted=\[Xi]vec[[\[CapitalGamma]\[Gamma]order]];

\[CapitalGamma]\[Gamma]cuts=Table[{1+#[[i]],#[[i+1]]},{i,1,Length[#]-1}]&@Join[{0},Accumulate[Length/@GatherBy[\[Xi]vec\[CapitalGamma]\[Gamma]sorted,_?(Chop[#1-#2]==0&)]]];
\[CapitalGamma]\[Gamma]spaces=Flatten[\[CapitalGamma]\[Gamma]subspaces][[#[[1]];;#[[2]]]]&/@\[CapitalGamma]\[Gamma]cuts;
dim\[CapitalGamma]s=Length@\[CapitalGamma]\[Gamma]subspaces[[First@First@Position[\[CapitalGamma]\[Gamma]subspaces,First[#]]]]&/@\[CapitalGamma]\[Gamma]spaces;
IsotopicSpaces=MapThread[Partition[#1,#2]&,{\[CapitalGamma]\[Gamma]spaces,dim\[CapitalGamma]s}];

phasetransformations=ConsistentIsotopicPhase[G\[CapitalGamma]\[Gamma]mats,IsotopicSpaces[[#]],dim\[CapitalGamma]s[[#]],dimG]&/@Range[Length[dim\[CapitalGamma]s]];
phasetransformation=SparseArray@Simplify@Normal@ArrayFlatten[ReleaseHold@DiagonalMatrix[Hold/@phasetransformations]];
V=SparseArray[ConjugateTranspose[(FullSimplify[Abs[#]]Exp[I FullSimplify[Arg[#]]]&/@(X\[CapitalGamma]\[Gamma]sorted . ConjugateTranspose[phasetransformation]))]];

dimvec=Flatten[ConstantArray[dim\[CapitalGamma]s[[#]],Length[Flatten[IsotopicSpaces[[#]]]]]&/@Range[Length[dim\[CapitalGamma]s]]];
{K3\[CapitalGamma],K4\[CapitalGamma]}=Normal@Chop@N@{V . MatrixRepresentation[K3,basis1] . ConjugateTranspose[V],V . MatrixRepresentation[K4,basis1] . ConjugateTranspose[V]};
V[[Ordering[Chop@N@Transpose[{dimvec,Diagonal[K3\[CapitalGamma]],-Diagonal[K4\[CapitalGamma]]}]]]]
]


(* ::Input::Initialization:: *)
SymmetryAdaptedBasisTFM[basis2_,basis1:SymmetryAdaptedBasis[args___]]:=(ConjugateTranspose[SymmetryAdaptedBasisTFM[basis1,basis2]]);


(* ::Input::Initialization:: *)
SymmetryAdaptedBasisTFM[SymmetryAdaptedBasis[spinsys_,SpinPermutationGroupOperators[{{"AlternatingGroup",n_},group_},spins_],opts___Rule],basis1_]:=If[n<=3,
SymmetryAdaptedBasisTFM[SymmetryAdaptedBasis[spinsys,SpinPermutationGroupOperators[{{"SymmetricGroup",n},group},spins],opts],basis1],
SymmetryAdaptedBasisTFM[SymmetryAdaptedBasis[spinsys,SpinPermutationGroupOperators[{{"DummyGroup",n},group},spins],opts],basis1]
];


(* ::Input::Initialization:: *)
SymmetryAdaptedBasisTFM[SymmetryAdaptedBasis[spinsys_,SpinPermutationGroupOperators[{{"CyclicGroup",n_},group_},_],opts___Rule],basis1_]:=Module[{
spins,
K1,K2,K3,K4,CSCO,G,dimG,
ev,vecs,Gmats,X,Xinv,\[Xi]vec,
G\[CapitalGamma]\[Gamma]mats,\[CapitalGamma]\[Gamma]subspaces,\[CapitalGamma]\[Gamma]order,
vecs\[CapitalGamma]\[Gamma]sorted,X\[CapitalGamma]\[Gamma]sorted,X\[CapitalGamma]\[Gamma]invsorted,\[Xi]vec\[CapitalGamma]\[Gamma]sorted,G\[CapitalGamma]\[Gamma]sortedmats,
\[CapitalGamma]\[Gamma]cuts,\[CapitalGamma]\[Gamma]bounds,\[CapitalGamma]\[Gamma]spaces,
SpacePartition,IsotopicSpaces,truepos,dim\[CapitalGamma]s,
phasetransformations,phasetransformation,
V,K2\[CapitalGamma],K3\[CapitalGamma],dimvec},
spins=First[Transpose[spinsys]];
K1=SpinPermutationOperator[spins,spinsys];
K2=Sum[(opI[spins[[i]]]) . (opI[spins[[j]]]),{i,1,n},{j,1,n}];
K3=opI["z"];
G=(SpinPermutationOperator[If[MatchQ[#,{{__}}],#[[1]],#],spinsys])&/@(Sort[GroupElements[CyclicGroup[n]][[All,1]]]/.Thread[Range[n]-> spins]);
CSCO={K1,K2,K3};
dimG=Length[G];

{ev,vecs}=Chop@Eigensystem[MatrixRepresentation[RandomInteger[{-100,100},Length[CSCO]] . CSCO,basis1]];
vecs=#/FullSimplify[Sqrt[# . Conjugate[#]]]&/@vecs;
Gmats=MatrixRepresentation[#,basis1]&/@G;
X=Transpose[vecs]//SparseArray;
Xinv=ConjugateTranspose[X];
\[Xi]vec=Normal[Xinv . (MatrixRepresentation[CSCO[[1]],basis1]) . X//N//Chop//Diagonal];

G\[CapitalGamma]\[Gamma]mats=Simplify[Chop[Xinv . # . X]]&/@Gmats;
\[CapitalGamma]\[Gamma]subspaces=SortBy[ConnectedComponents[Rule@@@Chop[Total[RandomReal[{-100,100},dimG]*G\[CapitalGamma]\[Gamma]mats]]["NonzeroPositions"]],Length];
\[CapitalGamma]\[Gamma]order=Flatten[\[CapitalGamma]\[Gamma]subspaces];
vecs\[CapitalGamma]\[Gamma]sorted=vecs[[\[CapitalGamma]\[Gamma]order]];
X\[CapitalGamma]\[Gamma]sorted=Transpose[vecs\[CapitalGamma]\[Gamma]sorted]//SparseArray;
X\[CapitalGamma]\[Gamma]invsorted=ConjugateTranspose[vecs\[CapitalGamma]\[Gamma]sorted];
\[Xi]vec\[CapitalGamma]\[Gamma]sorted=\[Xi]vec[[\[CapitalGamma]\[Gamma]order]];
G\[CapitalGamma]\[Gamma]sortedmats=G\[CapitalGamma]\[Gamma]mats[[All,\[CapitalGamma]\[Gamma]order,\[CapitalGamma]\[Gamma]order]];
\[CapitalGamma]\[Gamma]cuts=Join[{0},Flatten[SparseArray[Chop[Differences[\[Xi]vec\[CapitalGamma]\[Gamma]sorted]]]["NonzeroPositions"]]];
\[CapitalGamma]\[Gamma]bounds=Partition[Join[Riffle[\[CapitalGamma]\[Gamma]cuts+1,Rest@\[CapitalGamma]\[Gamma]cuts],{Length[ev]}],2];
\[CapitalGamma]\[Gamma]spaces=Range[#[[1]],#[[2]]]&/@\[CapitalGamma]\[Gamma]bounds;

SpacePartition=Table[truepos=Flatten[Position[ContainsAny[i,#]&/@\[CapitalGamma]\[Gamma]subspaces,True]];\[CapitalGamma]\[Gamma]subspaces[[truepos]],{i,\[CapitalGamma]\[Gamma]spaces}];
dim\[CapitalGamma]s=Length/@SpacePartition[[All,1]];
IsotopicSpaces=MapThread[Partition[#1,#2]&,{\[CapitalGamma]\[Gamma]spaces,dim\[CapitalGamma]s}];
phasetransformations=ConsistentIsotopicPhase[G\[CapitalGamma]\[Gamma]sortedmats,IsotopicSpaces[[#]],dim\[CapitalGamma]s[[#]],dimG]&/@Range[Length[dim\[CapitalGamma]s]];
phasetransformation=ArrayFlatten[ReleaseHold@DiagonalMatrix[Hold/@phasetransformations]];
V=SparseArray[ConjugateTranspose[(FullSimplify[Abs[#]]Exp[I FullSimplify[Arg[#]]]&/@(X\[CapitalGamma]\[Gamma]sorted . ConjugateTranspose[phasetransformation]))]];

dimvec=Flatten[ConstantArray[dim\[CapitalGamma]s[[#]],Length[Flatten[IsotopicSpaces[[#]]]]]&/@Range[Length[dim\[CapitalGamma]s]]];
{K2\[CapitalGamma],K3\[CapitalGamma]}=Normal@Chop@N@{V . MatrixRepresentation[K2,basis1] . ConjugateTranspose[V],V . MatrixRepresentation[K3,basis1] . ConjugateTranspose[V]};
V[[Ordering[Chop@N@Transpose[{dimvec,-Diagonal[K2\[CapitalGamma]],-Diagonal[K3\[CapitalGamma]]}]]]]
]


(* ::Input::Initialization:: *)
SymmetryAdaptedBasisTFM[SymmetryAdaptedBasis[spinsys_,SpinPermutationGroupOperators[{{grname_,n_},gops_},_],opts___Rule],basis1_]:=Module[{
spins,nspins,dimG,
PSGZKB,SG,SX,
K1,K2,KC1,KC2,
nspace1,nspace2,nspace,
nops,nopsZKB,nopssym,
ev,vecs,X,
Gmats,Gmats\[Xi],subspaces,
\[Xi]vecs,\[Xi]groupings,\[Xi]remaining,\[Xi]group,\[Xi]perm,\[Xi]dim,
Gmats\[Xi]perm,phaseU,normphaseU
},
spins=First[Transpose[spinsys]];
nspins=Length[spins];
dimG=Length[gops];
Gmats=MatrixRepresentation[#,basis1]&/@gops;

SG=(LeftMultiplicationSuperoperator[#]) . (RightMultiplicationSuperoperator[Adjoint[#]])&/@gops;
PSGZKB=SuperoperatorMatrixRepresentation[Total[SG],ZeemanKetBraOperatorBasis[spinsys]];
SX=OperatorBasisTransformationMatrix[OperatorBasis[],ZeemanKetBraOperatorBasis[spinsys]];

K1=(BasisOperators[OperatorBasis[]]) . (SX . PSGZKB . OperatorVectorRepresentation[opI[spins,"z"],ZeemanKetBraOperatorBasis[spinsys]]);
K2=(BasisOperators[OperatorBasis[]]) . (SX . PSGZKB . OperatorVectorRepresentation[Sum[(opI[i]) . (opI[j]),{i,1,nspins},{j,1,nspins}],ZeemanKetBraOperatorBasis[spinsys]]);

KC1=SX . SuperoperatorMatrixRepresentation[CommutationSuperoperator[K1],ZeemanKetBraOperatorBasis[spinsys]] . ConjugateTranspose[SX]//Simplify;
KC2=SX . SuperoperatorMatrixRepresentation[CommutationSuperoperator[K2],ZeemanKetBraOperatorBasis[spinsys]] . ConjugateTranspose[SX]//Simplify;

nspace1=SparseArray/@NullSpace[KC1];
nspace2=SparseArray/@NullSpace[KC2];
nspace=VectorSpaceIntersection[nspace1,nspace2];

nops=(BasisOperators[OperatorBasis[]]) . #&/@nspace;
nopsZKB=OperatorVectorRepresentation[#,ZeemanKetBraOperatorBasis[spinsys]]&/@nops;
nopssym=ArrayReshape[#,{BasisDimension[ZeemanBasis[spinsys]],BasisDimension[ZeemanBasis[spinsys]]}]&/@Orthogonalize[N[PSGZKB . #&/@nopsZKB]];

{ev,vecs}=Eigensystem[Total[RandomReal[{-100,100},Length[nopssym]]nopssym]]//Chop;
vecs=Orthogonalize[vecs];
X=Transpose[vecs]//Chop//SparseArray;
Gmats\[Xi]=ConjugateTranspose[X] . # . X&/@Gmats//Chop;
subspaces=ConnectedComponents[Rule@@@SparseArray[Chop[RandomReal[{-1,1},dimG] . Gmats\[Xi]]]["NonzeroPositions"]];

\[Xi]vecs=Chop@Table[Tr[gel[[#,#]]]&/@subspaces,{gel,Gmats\[Xi]}]//Transpose;
\[Xi]groupings={};
\[Xi]remaining=Range[Length[subspaces]];
While[\[Xi]remaining!={},
\[Xi]group=\[Xi]remaining[[Flatten[Position[MatchQ[{0},Union[Chop[\[Xi]vecs[[First[\[Xi]remaining]]]-#]]]&/@\[Xi]vecs[[\[Xi]remaining]],True]]]];
AppendTo[\[Xi]groupings,subspaces[[\[Xi]group]]];
\[Xi]remaining=Complement[\[Xi]remaining,\[Xi]group];
];
\[Xi]perm=Flatten[\[Xi]groupings];
\[Xi]dim=Length[First[#]]&/@\[Xi]groupings;

Gmats\[Xi]perm=#[[\[Xi]perm,\[Xi]perm]]&/@Gmats\[Xi];
phaseU=ArrayFlatten[ReleaseHold@DiagonalMatrix[Hold/@(SparseArray@ConsistentIsotopicPhase[Gmats\[Xi],\[Xi]groupings[[#]],\[Xi]dim[[#]],dimG]&/@Range[1,Length[\[Xi]groupings]])]];
normphaseU=SparseArray@DiagonalMatrix[1/Normal@Sqrt[Diagonal[ConjugateTranspose[phaseU] . phaseU]]];
phaseU=phaseU . normphaseU;
Conjugate[Transpose[(X . ConjugateTranspose[phaseU[[InversePermutation[\[Xi]perm],InversePermutation[\[Xi]perm]]]])][[\[Xi]perm]]]//SparseArray//Chop
]


ConsistentIsotopicPhase[Gmats_,IsotopicSpaces_,1,dimG_]:=Module[{ReferenceSpace,ReferenceRep},
IdentityMatrix[Length[IsotopicSpaces],SparseArray]
];
ConsistentIsotopicPhase[Gmats_,IsotopicSpaces_,dim\[CapitalGamma]_,dimG_]:=Module[{ReferenceSpace,ReferenceRep,Scollection},
If[Length[IsotopicSpaces]==1,
IdentityMatrix[dim\[CapitalGamma],SparseArray],
ReferenceSpace=IsotopicSpaces[[1]];
ReferenceRep=Normal[Gmats[[All,ReferenceSpace,ReferenceSpace]]]//Simplify;
Scollection=ConsistentIsotopicPhaseU[ReferenceRep,Gmats[[All,#,#]],dim\[CapitalGamma],dimG]&/@Rest[IsotopicSpaces];
ArrayFlatten[ReleaseHold@DiagonalMatrix[Hold/@Join[{IdentityMatrix[dim\[CapitalGamma],SparseArray]},Scollection]]]
]
];


ConsistentIsotopicPhaseU[\[Phi]_,\[Theta]_,dim\[CapitalGamma]_,dimG_]:=Module[{S,i$,k},
i$=1;
S=ConstantArray[0,{dim\[CapitalGamma],dim\[CapitalGamma]},SparseArray];
While[MatchQ[S["NonzeroPositions"],{}],
S=Table[dim\[CapitalGamma]/dimG \[Phi][[All,1,a]] . Conjugate[\[Theta][[All,i$,b]]],{a,1,dim\[CapitalGamma]},{b,1,dim\[CapitalGamma]}]//Chop//SparseArray;
i$=i$+1;
];
S=Conjugate[S]
]


(* ::Input::Initialization:: *)
End[];
EndPackage[];



