(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["Tensors`IST`",{"Global`","SpinDynamica`","General`Matrices`","General`Miscellaneous`"}];


(* ::Input::Initialization:: *)
SphericalTensor::usage="SphericalTensor[\[Lambda],elements] is an irreducible spherical tensor of rank \[Lambda] with 2\[Lambda]+1 elements given by the list elements, arranged with the m-value in descending order from m=+\[Lambda] to m=-\[Lambda]. The element with index m may be accessed using the syntax SphericalTensor[\[Lambda],elements][m] or SphericalTensor[{\[Lambda],m},elements]. A SphericalTensor may be transformed between reference frames using the routine TransformSphericalTensor.";


(* ::Input::Initialization:: *)
TransformSphericalTensor::usage=
"TransformSphericalTensor[sphericaltensor,eulerangles] transforms the spherical tensor, written in a reference frame 1 to a new reference frame 2, where frame 1 may be rotated into frame 2 by the Euler angles eulerangles. For example, if SphericalTensor[\[Lambda],elements] specifies a spherical tensor in its principal axis frame, then TransformSphericalTensor[SphericalTensor[\[Lambda],elements],{\[Alpha]PL,\[Beta]PL,\[Gamma]PL}] specifies the same spherical tensor in the lab frame, where {\[Alpha]PL,\[Beta]PL,\[Gamma]PL} represents the Euler angles which align the principal axis frame P with the lab frame L. The Euler angles may in turn be derived through AxesToEuler[Paxes,Laxes], where Paxes and Laxes are sets of 3-dimensional axes, generated by AxisSystem. The Euler angles eulerangles may also be specified as a chain of transformations, for example {{\[Alpha]PF,\[Beta]PF,\[Gamma]PF},{\[Alpha]FL,\[Beta]FL,\[Gamma]FL}}..}. 
";


(* ::Input::Initialization:: *)
CartesianTensor::usage="?";


(* ::Input::Initialization:: *)
SphericalToCartesian::usage="SphericalToCartesian[spheric] converts a spherical tensor object with integer rank \[Lambda] \[LessEqual] 2 into rank-2 cartesian tensor form. The output of SphericalToCartesian is a 3\[Times]3 matrix.
";


(* ::Input::Initialization:: *)
CartesianToSpherical::usage="CartesianToSpherical[\[Lambda],cart] converts a scalar, cartesian vector or 3\[Times]3 matrix into spherical tensor form. For rank \[Lambda]=0, the argument cart may be a number (scalar), or a 3\[Times]3 matrix. For rank \[Lambda]=1, the argument cart may be a 3-element Cartesian vector, or a 3\[Times]3 matrix. For rank \[Lambda]=2, the argument cart must be a 3\[Times]3 matrix.
The output of CartesianToSpherical is a SphericalTensor object. 
The syntax CartesianToSpherical[{\[Lambda]1,\[Lambda]2},cart] generates a list of SphericalTensor objects. 
The syntax CartesianToSpherical[cart] generates a list of all SphericalTensor objects compatible with the argument cart. 
";


(* ::Input::Initialization:: *)
Begin["`Private`"]; 


(* ::Input::Initialization:: *)
Options[SphericalTensor]={};


(* ::Input::Initialization:: *)
SphericalTensor[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
SphericalTensor[\[Lambda]_?NumericQ,elements_List,more___,opts___Rule]/;!IntegerQ[2\[Lambda]]:=(Message[SphericalTensor::bad\[Lambda]];$Failed);


(* ::Input::Initialization:: *)
SphericalTensor[\[Lambda]_?(IntegerQ[2#]&),elements_List,more___,opts___Rule]/;\[Lambda]<0:=(Message[SphericalTensor::bad\[Lambda]];$Failed);


(* ::Input::Initialization:: *)
SphericalTensor[\[Lambda]_?(IntegerQ[2#]&),elements_List,more___,opts___Rule]/;Length[elements]!=2\[Lambda]+1:=(Message[SphericalTensor::badellen];$Failed);


(* ::Input::Initialization:: *)
SphericalTensor[\[Lambda]_Integer|{\[Lambda]_Integer,_},elements_List,more___,opts___Rule]/;IntegerQ[2\[Lambda]]&&(\[Lambda]!=1)&&(elements!=Reverse@Conjugate@(Table[(-1)^(\[Lambda]-m),{m,\[Lambda],-\[Lambda],-1}]*elements)):=
(Message[SphericalTensor::badsymm];$Failed);


(* ::Input::Initialization:: *)
SphericalTensor[\[Lambda]:Except[_List],elements_,more___,opts___Rule][m_]:=SphericalTensor[{\[Lambda],m},elements,more,opts];


(* ::Input::Initialization:: *)
SphericalTensor[{\[Lambda]_?(IntegerQ[2#]&),m_},elements_List,opts___Rule]:=
If[MemberQ[Range[-\[Lambda],+\[Lambda],+1],m],
elements[[+\[Lambda]-m+1]],
(Message[SphericalTensor::badm,m,\[Lambda]];$Failed)
];


(* ::Input::Initialization:: *)
SphericalTensor[\[Lambda]:Except[_List],
elements_List,\[CapitalOmega]:Except[_List]|{Except[_List],Except[_List],Except[_List]}|{{Except[_List],Except[_List],Except[_List]}..},opts___Rule]:=
SphericalTensor[\[Lambda],
elements . WignerD[\[Lambda]][\[CapitalOmega]],
opts
];


(* ::Input::Initialization:: *)
SphericalTensor[{\[Lambda]_,\[Mu]_},
elements_List,\[CapitalOmega]:Except[_List]|{Except[_List],Except[_List],Except[_List]}|{{Except[_List],Except[_List],Except[_List]}..},opts___Rule]:=
SphericalTensor[{\[Lambda],\[Mu]},
elements . WignerD[\[Lambda]][\[CapitalOmega]],
opts
];


(* ::Input::Initialization:: *)
TransformSphericalTensor[SphericalTensor[\[Lambda]:Except[_List],elements_List,opts1___Rule],\[CapitalOmega]:Except[_List]|{Except[_List],Except[_List],Except[_List]}|{{Except[_List],Except[_List],Except[_List]}..},opts2___Rule]:=SphericalTensor[\[Lambda],
elements . WignerD[\[Lambda]][\[CapitalOmega]],
opts1,opts2
];


(* ::Input::Initialization:: *)
SphericalTensor/:Adjoint@SphericalTensor[\[Lambda]:Except[_List],
elements_List,opts___Rule]:=SphericalTensor[\[Lambda],Table[(-1)^m,{m,+\[Lambda],-\[Lambda],-1}]*Reverse[elements],opts];


(* ::Input::Initialization:: *)
SphericalTensor/:Dot[st1:SphericalTensor[\[Lambda]1_,els1_,___Rule],st2:SphericalTensor[\[Lambda]2_,els2_,___Rule]]/;\[Lambda]1!=\[Lambda]2:=
(Message[SphericalTensor::incomp\[Lambda]];$Failed);


(* ::Input::Initialization:: *)
SphericalTensor/:Dot[st1:SphericalTensor[\[Lambda]_,els1_,___Rule],st2:SphericalTensor[\[Lambda]_,els2_,___Rule]]:=
(Table[(-1)^m,{m,+\[Lambda],-\[Lambda],-1}]*els1) . els2;


(* ::Input::Initialization:: *)
SphericalTensor/:Norm[SphericalTensor[rank_,elements_List,___Rule]]:=Sqrt[Plus@@(Abs[#]^2&/@elements)]


(* ::Input::Initialization:: *)
SphericalTensor::badellen="The length of the element list is inappropriate for the rank.";


(* ::Input::Initialization:: *)
SphericalTensor::bad\[Lambda]="The rank must be zero, a positive integer or half-integer.";


(* ::Input::Initialization:: *)
SphericalTensor::badsymm="The list of elements does not have the correct symmetry.";


(* ::Input::Initialization:: *)
SphericalTensor::badm="The index `1` is not appropriate for rank `2`";


(* ::Input::Initialization:: *)
SphericalTensor::incomp\[Lambda]="The dot product may only be taken between spherical tensors of the same rank";


(* ::Input::Initialization:: *)
Options[CartesianToSpherical]={};


(* ::Input::Initialization:: *)
CartesianToSpherical[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
CartesianToSpherical[\[Lambda]_?NumericQ,cart_,opts___Rule]/;!IntegerQ[\[Lambda]]:=(Message[CartesianToSpherical::bad\[Lambda]];$Failed);


(* ::Input::Initialization:: *)
CartesianToSpherical[\[Lambda]_Integer,cart_,opts___Rule]/;!(0<=\[Lambda]<=2):=(Message[CartesianToSpherical::bad\[Lambda]];$Failed);


(* ::Input::Initialization:: *)
CartesianToSpherical[\[Lambda]_Integer,scalar:Except[_List|_SparseArray],opts___Rule]/;\[Lambda]!=0:=(Message[CartesianToSpherical::\[Lambda]gt0];$Failed);


(* ::Input::Initialization:: *)
CartesianToSpherical[\[Lambda]_Integer,scalar:Except[_List|_SparseArray],opts___Rule]/;scalar!=Conjugate[scalar]:=(Message[CartesianToSpherical::scalnotreal];$Failed);


(* ::Input::Initialization:: *)
CartesianToSpherical[\[Lambda]_Integer,vec_?VectorQ,opts___Rule]/;\[Lambda]>1:=(Message[CartesianToSpherical::\[Lambda]gt1];$Failed);


(* ::Input::Initialization:: *)
CartesianToSpherical[\[Lambda]_Integer,vec_?VectorQ,opts___Rule]/;Length[vec]!=3:=(Message[CartesianToSpherical::badveclen];$Failed);


(* ::Input::Initialization:: *)
CartesianToSpherical[\[Lambda]_Integer,vec_?NumericQ,opts___Rule]/;vec!=Conjugate[vec]:=(Message[CartesianToSpherical::vecnotreal];$Failed);


(* ::Input::Initialization:: *)
CartesianToSpherical[\[Lambda]_Integer,mat_?MatrixQ,opts___Rule]/;\[Lambda]>2:=(Message[CartesianToSpherical::\[Lambda]gt2];$Failed);


(* ::Input::Initialization:: *)
CartesianToSpherical[\[Lambda]_Integer,mat_?MatrixQ,opts___Rule]/;Dimensions[mat]!={3,3}:=
(Message[CartesianToSpherical::badmatdim];$Failed);


(* ::Input::Initialization:: *)
CartesianToSpherical[\[Lambda]_Integer,mat_?NumericQ,opts___Rule]/;mat!=Conjugate[mat]:=
(Message[CartesianToSpherical::matnotreal];$Failed);


(* ::Input::Initialization:: *)
CartesianToSpherical[\[Lambda]vals_List,args_,opts___Rule]:=CartesianToSpherical[#,args,opts]&/@\[Lambda]vals;


(* ::Input::Initialization:: *)
CartesianToSpherical[scalar:Except[_List|_SparseArray],opts___Rule]:=CartesianToSpherical[{0},scalar,opts];


(* ::Input::Initialization:: *)
CartesianToSpherical[vec_?VectorQ,opts___Rule]:=CartesianToSpherical[{0,1},vec,opts];


(* ::Input::Initialization:: *)
CartesianToSpherical[mat_?MatrixQ,opts___Rule]:=CartesianToSpherical[{0,1,2},mat,opts];


(* ::Input::Initialization:: *)
CartesianToSpherical[0,scalar:Except[_List|_SparseArray],opts___Rule]:=SphericalTensor[0,{scalar},opts];


(* ::Input::Initialization:: *)
CartesianToSpherical[0,vec_?VectorQ,opts___Rule]:=SphericalTensor[0,{Plus@@vec/3},opts];


(* ::Input::Initialization:: *)
CartesianToSpherical[1,vec_?VectorQ,opts___Rule]:=Module[{x,y,z},
{x,y,z}=vec;
SphericalTensor[1,
{-(1/Sqrt[2])(x+I y),
z,
+(1/Sqrt[2])(x-I y)
},
opts
]];


(* ::Input::Initialization:: *)
CartesianToSpherical[0,mat_?MatrixQ,opts___Rule]:=SphericalTensor[0,{-(1/Sqrt[3])Plus@@Diagonal[mat]},opts];


(* ::Input::Initialization:: *)
CartesianToSpherical[1,
mat_?MatrixQ,
opts___Rule]:=Module[{xx,xy,xz,yx,yy,yz,zx,zy,zz},
{xx,xy,xz,yx,yy,yz,zx,zy,zz}=Flatten[mat];
SphericalTensor[1,
{-(1/2)(zx-xz+I(zy-yz)),
-(1/Sqrt[2])I(xy-yx),
-(1/2)(zx-xz-I(zy-yz))
},
opts
]]


(* ::Input::Initialization:: *)
CartesianToSpherical[2,
mat_?MatrixQ,
opts___Rule]:=Module[{xx,xy,xz,yx,yy,yz,zx,zy,zz},
{xx,xy,xz,yx,yy,yz,zx,zy,zz}=Flatten[mat];
SphericalTensor[2,
{(1/2)(xx-yy+I(xy+yx)),
-(1/2)(xz+zx+I(yz+zy)),
(1/Sqrt[6])(3zz-(xx+yy+zz)),
+(1/2)(xz+zx-I(yz+zy)),
(1/2)(xx-yy-I(xy+yx))
},
opts
]];


(* ::Input::Initialization:: *)
CartesianToSpherical::bad\[Lambda]="The rank \[Lambda] must be an integer \[LessEqual] 2";


(* ::Input::Initialization:: *)
CartesianToSpherical::\[Lambda]gt0="The rank \[Lambda] must be zero for a scalar argument.";


(* ::Input::Initialization:: *)
CartesianToSpherical::\[Lambda]gt1="The rank \[Lambda] cannot be greater than 1 for a vector argument.";


(* ::Input::Initialization:: *)
CartesianToSpherical::\[Lambda]gt2="The rank \[Lambda] cannot be greater than 2 for a matrix argument.";


(* ::Input::Initialization:: *)
CartesianToSpherical::badveclen="The Cartesian vector must have 3 elements."; 


(* ::Input::Initialization:: *)
CartesianToSpherical::badmatdim="The Cartesian matrix must be 3\[Times]3."; 


(* ::Input::Initialization:: *)
CartesianToSpherical::scalnotreal="The scalar must be real."; 


(* ::Input::Initialization:: *)
CartesianToSpherical::vecnotreal="The Cartesian vector must have real elements."; 


(* ::Input::Initialization:: *)
CartesianToSpherical::matnotreal="The Cartesian matrix must have real elements."; 


(* ::Input::Initialization:: *)
Options[SphericalToCartesian]={};


(* ::Input::Initialization:: *)
SphericalToCartesian[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
SphericalToCartesian[args:{(_List|_SphericalTensor)..},opts___Rule]:=Plus@@(SphericalToCartesian[#,opts]&/@args);


(* ::Input::Initialization:: *)
SphericalToCartesian[vec:{(_Symbol|_?NumericQ)..},opts___Rule]/;!MatchQ[Length[vec],1|3|5]:=(Message[SphericalToCartesian::bad\[Lambda]];$Failed);


(* ::Input::Initialization:: *)
SphericalToCartesian[vec:{(_Symbol|_?NumericQ)..},opts___Rule]:=SphericalToCartesian[SphericalTensor[(Length[vec]-1)/2,vec]];


(* ::Input::Initialization:: *)
SphericalToCartesian[SphericalTensor[0,vec_List],symb___,opts___Rule]:=Module[{array,iso,id,diag},
array=Chop@SparseArray[Simplify@ArrayReshape[BT . Join[vec,ConstantArray[0,8]],{3,3}]];
diag=Diagonal[array];
id=SparseArray[{i_,i_}:> 1,{3,3}];
iso=1/3*Total[diag];
Normal@Simplify[Chop[iso*id]]
];


(* ::Input::Initialization:: *)
SphericalToCartesian[SphericalTensor[1,vec_List],opts___Rule]:=Module[{array,upper,lower},
array=Chop@SparseArray[Simplify@ArrayReshape[BT . Join[ConstantArray[0,1],vec,ConstantArray[0,5]],{3,3}]];
upper=UpperTriangularize[array,1];
lower=LowerTriangularize[array,-1];
Normal@Simplify[1/2*(upper-Transpose[lower]+lower-Transpose[upper])]
];


(* ::Input::Initialization:: *)
SphericalToCartesian[SphericalTensor[2,vec_List],opts___Rule]:=Module[{array,iso,id,diag,upper,lower},
array=Chop@SparseArray[Simplify@ArrayReshape[BT . Join[ConstantArray[0,4],vec],{3,3}]];
diag=Diagonal[array];
upper=UpperTriangularize[array,1];
lower=LowerTriangularize[array,-1];
id=SparseArray[{i_,i_}:> 1,{3,3}];
iso=1/3*Total[diag];
Normal@Simplify[1/2*(upper+Transpose[lower]+lower+Transpose[upper])+DiagonalMatrix[diag]-iso*id]
]


(* ::Input::Initialization:: *)
BT={{-(1/Sqrt[3]),0,0,0,1/2,0,-(1/Sqrt[6]),0,1/2},{0,0,I/Sqrt[2],0,-(I/2),0,0,0,I/2},{0,1/2,0,1/2,0,-(1/2),0,1/2,0},{0,0,-(I/Sqrt[2]),0,-(I/2),0,0,0,I/2},{-(1/Sqrt[3]),0,0,0,-(1/2),0,-(1/Sqrt[6]),0,-(1/2)},{0,-(I/2),0,I/2,0,I/2,0,I/2,0},{0,-(1/2),0,-(1/2),0,-(1/2),0,1/2,0},{0,I/2,0,-(I/2),0,I/2,0,I/2,0},{-(1/Sqrt[3]),0,0,0,0,0,Sqrt[2/3],0,0}}


(* ::Input::Initialization:: *)
SphericalToCartesian::bad\[Lambda]="SphericalToCartesian can only handle spherical tensors of rank 0, 1 or 2.";


(* ::Input::Initialization:: *)
SphericalToCartesian::vecnn="The Spherical Tensor components are non-numeric."; 


(* ::Input::Initialization:: *)
SphericalToCartesian::badsymm="The Spherical Tensor components do not meet the correct symmetry properties (\!\(\*SubscriptBox[\(T\), \(\[Lambda]\[Mu]\)]\)\!\(\*SuperscriptBox[\()\), \(\[Dagger]\)]\) = (-1\!\(\*SuperscriptBox[\()\), \(\[Mu]\)]\)\!\(\*SubscriptBox[\(T\), \(\[Lambda] - \[Mu]\)]\)."; 


(* ::Input::Initialization:: *)
End[]; 
EndPackage[]; 



