(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["QM`ExtendedLiouville`",
{"Global`",
"SpinDynamica`",
"QM`Liouville`",
"QM`SpinOperators`",
"QM`Hilbert`",
"General`Miscellaneous`",
"General`Matrices`"
}];


(* ::Input::Initialization:: *)
Sites::usage="Sites[] returns the  site labels for the current ExtendedOperatorBasis";


(* ::Input::Initialization:: *)
SetSites::usage="SetSites[{i,j,...}] defines the  site labels for a system in chemical exchange (or other applications of ExtendedOperatorBasis). The syntax SetSites[n] is equivalent to SetSites[{1,2..n}].";


(* ::Input::Initialization:: *)
SetExtendedOperatorBasis::usage="SetExtendedOperatorBasis[sites,opbasis] sets the current extended operator basis to the basis ExtendedOperatorBasis[sites,opbasis]";


(* ::Input::Initialization:: *)
ExtendedOperatorBasis::usage="ExtendedOperatorBasis[sites,opbasis] refers to an operator basis duplicated several times, according to the elements in the list sites.
ExtendedOperatorBasis[] returns the current extended operator basis.;
";


(* ::Input::Initialization:: *)
SiteDependentOperator::usage=
"SiteDependentOperator[{{i,opi},{j,opj}..}] defines an operator which depends on the site indices {i,j..}. The set of sites {i,j..} must be a subset of Sites[]. The syntax SiteDependentOperator[{i,opi}] defines an operator which applies to just one of the sites. The syntax SiteDependentOperator[op] assumes that the operator applies to all sites. ";


(* ::Input::Initialization:: *)
ExtendedOperatorVectorRepresentation::usage="ExtendedOperatorVectorRepresentation[<sdop>,<xopb>] derives the vector representation of a SiteDependentOperator <sdop> in the ExtendedOperatorBasis <xopb>. If <xopb> is omitted, the current ExtendedOperatorBasis is used.
";


(* ::Input::Initialization:: *)
SiteDependentSuperoperator::usage=
"SiteDependentSuperoperator[{{i,superopi},{j,superopj}..}] defines a superoperator which depends on the site indices {i,j..}. The set of sites {i,j..} must be a subset of Sites[]. The syntax SiteDependentSuperoperator[{i,superopi}] defines a superoperator which applies to just one of the sites. The syntax SiteDependentSuperoperator[op] assumes that the superoperator applies to all sites. ";


(* ::Input::Initialization:: *)
ExtendedSuperoperatorMatrixRepresentation::usage="ExtendedSuperoperatorMatrixRepresentation[<sdsop>,<xopb>] derives the matrix representation of a SiteDependentSuperoperator <sdop> in the ExtendedOperatorBasis <xopb>. If <xopb> is omitted, the current ExtendedOperatorBasis is used.";


(* ::Input::Initialization:: *)
KineticExchangeMatrix::usage=
"KineticExchangeMatrix[{i,j..},K,options] defines a kinetic exchange matrix for dynamic exchange between the sites {i,j..}. The argument K may be be one of the following: (1) A square matrix of dimension equal to the number of exchanging sites, with elements given by the kinetic rate constants; (2) A list of the form {{i\[Rule]j,kji},{l\[Rule]m,kml}..} in which the rate constant kji for the conversion of site i into site j is specified explicitly, and similarly for the other rate constants. If the list contains an element of the form {i\[Rule]j,kji}, but no element for the opposite transformation {j\[Rule]i,kij}, the routine assumes kij=kji, i.e. symmetrical rate constants between sites i and j. Asymmetrical rate constants between i and j are defined by including elements of both forms {i\[Rule]j,kji} and {j\[Rule]i,kij}. 
If the sites {i,j..} are omitted, the sites are taken from the current Sites[].\nThe options may include ImposeDetailedBalance\[Rule]True may be used to impose detailed balance automatically by adjustment of the diagonal elements. The default is ImposeDetailedBalance\[Rule]True.
The output of KineticExchangeMatrix has the form KineticExchangeMatrix[{i,j..},matrix,options] where matrix is the resulting kinetic exchange matrix (as a SparseArray object). 
The raw kinetic matrix may be extracted by applying Expand to the result.";


(* ::Input::Initialization:: *)
ImposeDetailedBalance::usage="ImposeDetailedBalance is an option value for KineticExchangeMatrix. If ImposeDetailedBalance\[Rule]True, detailed kinetic balance is automatically imposed by adjusting the diagonal elements of the kinetic exchange matrix.";


(* ::Input::Initialization:: *)
DetailedBalance::usage="DetailedBalance is an option value for KineticExchangeMatrix. It is set to True when the KineticExchangeMatrix possesses detailed balance.";


(* ::Input::Initialization:: *)
KineticExchangeSuperoperator::usage="KineticExchangeSuperoperator[{i,j..},K,options] defines a kinetic exchange superoperator for dynamic exchange between the sites {i,j..}. The argument K may be be one of the following: (1) A square matrix of dimension equal to the number of exchanging sites, with elements given by the kinetic rate constants; (2) A list of the form {{i\[Rule]j,kji},{l\[Rule]m,kml}..} in which the rate constant kji for the conversion of site i into site j is specified explicitly, and similarly for the other rate constants. If the list contains an element of the form {i\[Rule]j,kji}, but no element for the opposite transformation {j\[Rule]i,kij}, the routine assumes kij=kji, i.e. symmetrical rate constants between sites i and j. Asymmetrical rate constants between i and j are defined by including elements of both forms {i\[Rule]j,kji} and {j\[Rule]i,kij}.
If the sites {i,j..} are omitted, the sites are taken from the current Sites[]. \nThe options may include ImposeDetailedBalance\[Rule]True may be used to impose detailed balance automatically by adjustment of the diagonal elements. The default is ImposeDetailedBalance\[Rule]True.
The raw kinetic matrix may be extracted by applying KineticExchangeMatrix to the result.";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
Options[Sites]={Sites->Undefined};


(* ::Input::Initialization:: *)
Sites[opts___Rule]:=Sites/.{opts}/.Options[Sites];


(* ::Input::Initialization:: *)
Sites::notunq="All site labels must be unique.";


(* ::Input::Initialization:: *)
SetSites[n_Integer,opts___Rule]/;(n>0):=SetSites[Range[1,n],opts];


(* ::Input::Initialization:: *)
SetSites[sites_List,opts___Rule]/;MatchQ[Sites[],Undefined]:=
If[DuplicateFreeQ[sites],
(SetOptions[Sites,Sites->sites];
Message[SetSites::setsites,sites]),
(Message[Sites::notunq];$Failed)
];


(* ::Input::Initialization:: *)
SetSites[sites_List,opts___Rule]/;MatchQ[sites,Sites[]]:=Message[SetSites::alreadyset,sites];


(* ::Input::Initialization:: *)
SetSites[sites_List,opts___Rule]/;MatchQ[SpinSystem[],Undefined]:=
If[DuplicateFreeQ[sites],
(SetOptions[Sites,Sites->sites];
Message[SetSites::setsites,sites]),
(Message[Sites::notunq];$Failed)
];


(* ::Input::Initialization:: *)
SetSites[sites_List,opts___Rule]/;(!MatchQ[SpinSystem[],Undefined])&&(!MatchQ[sites,Sites[ExtendedOperatorBasis[]]]):=
If[DuplicateFreeQ[sites],
(SetOptions[Sites,Sites->sites];
Message[SetSites::setsites,sites];
SetExtendedOperatorBasis[sites]
),
(Message[Sites::notunq];$Failed)
];


(* ::Input::Initialization:: *)
SetSites::alreadyset="The set of exchanging sites is already set to `1`. No action has been taken.";


(* ::Input::Initialization:: *)
SetSites::setsites="The set of exchanging sites has been set to `1`";


(* ::Input::Initialization:: *)
SetExtendedOperatorBasis[___]/;MatchQ[SpinSystem[],Undefined]:=(Message[SetExtendedOperatorBasis::undefspinsys];$Failed);


(* ::Input::Initialization:: *)
SetExtendedOperatorBasis[___]/;MatchQ[Sites[],Undefined]:=(Message[SetExtendedOperatorBasis::undefsites];$Failed);


(* ::Input::Initialization:: *)
SetExtendedOperatorBasis[opts___Rule]:=SetExtendedOperatorBasis[Sites[],opts];


(* ::Input::Initialization:: *)
SetExtendedOperatorBasis[sites_List,opts___Rule]:=(If[MatchQ[OperatorBasis[],Undefined],SetOperatorBasis[]];
SetExtendedOperatorBasis[sites,OperatorBasis[],opts]);


(* ::Input::Initialization:: *)
SetExtendedOperatorBasis[opb_?DefinedOperatorBasisQ,opts___Rule]:=SetExtendedOperatorBasis[Sites[],opb,opts];


(* ::Input::Initialization:: *)
SetExtendedOperatorBasis[sites_List,opb_?DefinedOperatorBasisQ,opts___Rule]:=
If[DuplicateFreeQ[sites],
SetExtendedOperatorBasis[
ExtendedOperatorBasis[sites,opb,opts],
opts
],
(Message[Sites::notunq];$Failed)
];


(* ::Input::Initialization:: *)
SetExtendedOperatorBasis[xopb_ExtendedOperatorBasis,___Rule]/;MatchQ[ExtendedOperatorBasis/.Options[ExtendedOperatorBasis],xopb]:=(Message[SetExtendedOperatorBasis::alreadyset,xopb]);


(* ::Input::Initialization:: *)
SetExtendedOperatorBasis[xopb_ExtendedOperatorBasis,___Rule]:=
(SetOptions[ExtendedOperatorBasis,ExtendedOperatorBasis->xopb];
Message[SetExtendedOperatorBasis::set,xopb];
xopb
);


(* ::Input::Initialization:: *)
SetExtendedOperatorBasis::undefspinsys="The spin system is undefined. Set the spin system using SetSpinSystem[..]";


(* ::Input::Initialization:: *)
SetExtendedOperatorBasis::undefsites="The list of exchanging sites is undefined. Set the sites using SetSites[..]";


(* ::Input::Initialization:: *)
SetExtendedOperatorBasis::alreadyset="The extended operator basis is already set to `1`. No action has been taken.";


(* ::Input::Initialization:: *)
SetExtendedOperatorBasis::set="The extended operator basis has been set to `1`.";


(* ::Input::Initialization:: *)
Options[ExtendedOperatorBasis]={ExtendedOperatorBasis->Undefined};


(* ::Input::Initialization:: *)
ExtendedOperatorBasis[___]/;MatchQ[SpinSystem[],Undefined]:=(Message[ExtendedOperatorBasis::undefspinsys];Undefined);


(* ::Input::Initialization:: *)
ExtendedOperatorBasis[___]/;MatchQ[Sites[],Undefined]:=(Message[ExtendedOperatorBasis::undefsites];Undefined);


(* ::Input::Initialization:: *)
ExtendedOperatorBasis[opts___Rule]/;MatchQ[ExtendedOperatorBasis/.Options[ExtendedOperatorBasis],Undefined]&&!MatchQ[Sites[],Undefined]&&!MatchQ[SpinSystem[],Undefined]:=
(
SetExtendedOperatorBasis[opts];
ExtendedOperatorBasis[opts]);


(* ::Input::Initialization:: *)
ExtendedOperatorBasis[opts___Rule]:=
Module[{xopb,opb,spinsys,sites},(
Message[ExtendedOperatorBasis::inappspinsys];
SetExtendedOperatorBasis[opts];
ExtendedOperatorBasis[opts];
)/;(
xopb=ExtendedOperatorBasis/.Options[ExtendedOperatorBasis];
spinsys=SpinSystem[];
sites=Sites[];
!MatchQ[spinsys,SpinSystem[xopb]]||!MatchQ[sites,Sites[xopb]]
)
];


(* ::Input::Initialization:: *)
ExtendedOperatorBasis[opts___Rule]:=ExtendedOperatorBasis/.{opts}/.Options[ExtendedOperatorBasis];


(* ::Input::Initialization:: *)
HoldPattern@Sites[ExtendedOperatorBasis[sites_List,opb_,___Rule],___Rule]:=sites;


(* ::Input::Initialization:: *)
HoldPattern@OperatorBasis[ExtendedOperatorBasis[sites_List,opb_,___Rule],___Rule]:=opb;


(* ::Input::Initialization:: *)
HoldPattern@SpinSystem[ExtendedOperatorBasis[sites_List,opb_,___Rule],___Rule]:=SpinSystem@opb;


(* ::Input::Initialization:: *)
HoldPattern@BasisOperators[ExtendedOperatorBasis[sites_List,opb_,___Rule],___Rule]:=BasisOperators@opb;


(* ::Input::Initialization:: *)
ExtendedOperatorBasis::undefspinsys="The spin system is undefined. Set the spin system using SetSpinSystem[..]";


(* ::Input::Initialization:: *)
ExtendedOperatorBasis::undefsites="The list of exchanging sites is undefined. Set the sites using SetSites[..]";


(* ::Input::Initialization:: *)
ExtendedOperatorBasis::inappspinsys="The SpinSystem of the current ExtendedOperatorBasis is inappropriate.";


(* ::Input::Initialization:: *)
ExtendedOperatorBasis::inappsites="The Sites of the current ExtendedOperatorBasis are inappropriate.";


(* ::Input::Initialization:: *)
SiteDependentOperator[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
SiteDependentOperator[op_?OperatorQ,opts___Rule]:=SiteDependentOperator[{op},opts];


(* ::Input::Initialization:: *)
SiteDependentOperator[notop:Except[_?OperatorQ|_List],opts___Rule]:=
(Message[SiteDependentOperator::invalarg];$Failed);


(* ::Input::Initialization:: *)
SiteDependentOperator[{op_?OperatorQ},opts___Rule]:=SiteDependentOperator[Table[op,{Length@Sites[]}],opts];


(* ::Input::Initialization:: *)
SiteDependentOperator[ops:{_?OperatorQ...},opts___Rule]:=SiteDependentOperator[Sites[],ops,opts];


(* ::Input::Initialization:: *)
SiteDependentOperator[Undefined,ops:{_?OperatorQ...},opts___Rule]:=(Message[SiteDependentOperator::undefsites];$Failed);


(* ::Input::Initialization:: *)
SiteDependentOperator[sites_List,op_?OperatorQ,opts___Rule]:=SiteDependentOperator[sites,Table[op,{Length[sites]}],opts];


(* ::Input::Initialization:: *)
SiteDependentOperator[sites_List,ops:{_?OperatorQ...},opts___Rule]/;Length[ops]!=Length@sites:=(Message[SiteDependentOperator::badlen];$Failed);


(* ::Input::Initialization:: *)
SiteDependentOperator[sites_List,ops:{_?OperatorQ...},opts___Rule]:=
SiteDependentOperator[Transpose[{sites,ops}],opts];


(* ::Input::Initialization:: *)
SiteDependentOperator[{i_,opi_?OperatorQ},opts___Rule]:=SiteDependentOperator[{{i,opi}},opts];


(* ::Input::Initialization:: *)
SiteDependentOperator[siteoplist:{{_,_}..},opts___Rule]/;MatchQ[Sites[],Undefined]:=(SetSites[First/@siteoplist];SiteDependentOperator[siteoplist,opts]);


(* ::Input::Initialization:: *)
SiteDependentOperator[siteoplist:{{_,_}..},opts___Rule]:=
Module[{sites},(
Message[SiteDependentOperator::badsites,sites,Sites[]];
$Failed
)/;(
sites=First/@siteoplist;
!ContainsAll[Sites[],sites]
)];


(* ::Input::Initialization:: *)
Sites[SiteDependentOperator[siteoplist:{{_,_}..},opts___Rule]]:=First/@siteoplist;


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Times[a___,
n:(_Symbol|_?NumericQ),
SiteDependentOperator[siteoplist:{{_,_}..},opts___Rule],
b___]:=
Module[{sites,ops},(
{sites,ops}=Transpose@siteoplist;
Times[a,
SiteDependentOperator[
Transpose[{sites,n*ops}],
opts
],
b
]
)
];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Times[a___,
sdop_SiteDependentOperator,
n:(_Symbol|_?NumericQ),
b___]:=Times[a,n,sdop,b];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Times[a___,sdop1_SiteDependentOperator,op_,b___]/;OperatorQ[op]||MatchQ[op,_SiteDependentOperator]:=(Message[SiteDependentOperator::badtimes];$Failed);


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Times[a___,op_,sdop1_SiteDependentOperator,b___]/;OperatorQ[op]||MatchQ[op,_SiteDependentOperator]:=
(Message[SiteDependentOperator::badtimes];$Failed);


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Dot[a___,
n:(_?NumericQ|_Symbol),
SiteDependentOperator[siteoplist:{{_,_}..},opts___Rule],
b___]:=
Module[{sites,ops},(
{sites,ops}=Transpose@siteoplist;
Dot[a,
SiteDependentOperator[
Transpose[{sites,n*ops}],
opts
],
b
]
)
];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Dot[a___,
sdop_SiteDependentOperator,
n:(_?NumericQ|_Symbol),
b___]:=Dot[a,n,sdop,b];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Dot[a___,
SiteDependentOperator[siteoplist1:{{_,_}..},opts1___Rule],
SiteDependentOperator[siteoplist2:{{_,_}..},opts2___Rule],
b___]:=
Module[{sites1,ops1,sites2,ops2},(
{sites1,ops1}=Transpose@siteoplist1;
{sites2,ops2}=Transpose@siteoplist2;
If[!MatchQ[sites1,sites2],
(Message[SiteDependentOperator::incompatsites];$Failed),
Dot[a,
SiteDependentOperator[
Transpose[{sites1,Inner[Dot,ops1,ops2,List]}],
Evaluate@SimplifyRules[
opts1,opts2
]
],b]
]
)];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Dot[a___,
op_?OperatorQ,
SiteDependentOperator[siteoplist:{{_,_}..},opts___Rule],
b___]:=
Module[{sites,ops},(
{sites,ops}=Transpose@siteoplist;
Dot[a,
SiteDependentOperator[
Transpose[{sites,Dot[op,#]&/@ops}],
opts
],
b
]
)
];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Dot[a___,
SiteDependentOperator[siteoplist:{{_,_}..},opts___Rule],
op_?OperatorQ,
b___]:=
Module[{sites,ops},(
{sites,ops}=Transpose@siteoplist;
Dot[a,
SiteDependentOperator[
Transpose[{sites,Dot[#,op]&/@ops}],
opts
],
b
]
)
];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Plus[a___,
n:(_?NumericQ|_Symbol),
sdop_SiteDependentOperator,
b___]:=
Plus[a,n*UnityOperator[],sdop,b];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Dot[a___,
sdop_SiteDependentOperator,
n:(_?NumericQ|_Symbol),
b___]:=Plus[a,n,sdop,b];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Plus[a___,
SiteDependentOperator[siteoplist1:{{_,_}..},opts1___Rule],
SiteDependentOperator[siteoplist2:{{_,_}..},opts2___Rule],
b___]:=
Module[{sites1,ops1,sites2,ops2},(
{sites1,ops1}=Transpose@siteoplist1;
{sites2,ops2}=Transpose@siteoplist2;
If[!MatchQ[sites1,sites2],
(Message[SiteDependentOperator::incompatsites];$Failed),
Plus[a,
SiteDependentOperator[
Transpose[{sites1,Inner[Plus,ops1,ops2,List]}],
Evaluate@SimplifyRules[
opts1,opts2
]
],b]
]
)];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Plus[a___,
op_?OperatorQ,
SiteDependentOperator[siteoplist:{{_,_}..},opts___Rule],
b___]:=
Module[{sites,ops},(
{sites,ops}=Transpose@siteoplist;
Plus[a,
SiteDependentOperator[
Transpose[{sites,Plus[op,#]&/@ops}],
opts
],
b
]
)
];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Plus[a___,
SiteDependentOperator[siteoplist:{{_,_}..},opts___Rule],
op_?OperatorQ,
b___]:=
Module[{sites,ops},(
{sites,ops}=Transpose@siteoplist;
Plus[a,
SiteDependentOperator[
Transpose[{sites,Plus[#,op]&/@ops}],
opts
],
b
]
)
];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Exp[SiteDependentOperator[siteoplist:{{_,_}..},opts___Rule]]:=
Module[{sites,ops},(
{sites,ops}=Transpose@siteoplist;
SiteDependentOperator[
Transpose[{sites,Exp/@ops}],
opts
]
)];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Power[SiteDependentOperator[siteoplist:{{_,_}..},opts___Rule],n_]:=
Module[{sites,ops},(
{sites,ops}=Transpose@siteoplist;
SiteDependentOperator[
Transpose[{sites,Power[#,n]&/@ops}],
opts
]
)];


(* ::Input::Initialization:: *)
SiteDependentOperator/:
HoldPattern@Power[n_,SiteDependentOperator[siteoplist:{{_,_}..},opts___Rule]]:=
Module[{sites,ops},(
{sites,ops}=Transpose@siteoplist;
SiteDependentOperator[
Transpose[{sites,Power[n,#]&/@ops}],
opts
]
)];


(* ::Input::Initialization:: *)
CommutationSuperoperator[SiteDependentOperator[siteoplist:{{_,_}..},opts1___Rule],opts2___Rule]:=
Module[{sites,ops},(
{sites,ops}=Transpose@siteoplist;
SiteDependentSuperoperator[
Transpose@{sites,CommutationSuperoperator[#,opts1]&/@ops},
opts2
]
)];


(* ::Input::Initialization:: *)
DoubleCommutationSuperoperator[
SiteDependentOperator[siteoplist:{{_,_}..},opts1___Rule],
op_?OperatorQ,
opts2___Rule
]:=
Module[{sites,ops},(
{sites,ops}=Transpose@siteoplist;
SiteDependentSuperoperator[
Transpose@{sites,
DoubleCommutationSuperoperator[#,op,opts1]&/@ops
},
opts2
]
)];


(* ::Input::Initialization:: *)
DoubleCommutationSuperoperator[
op_?OperatorQ,
SiteDependentOperator[siteoplist:{{_,_}..},opts1___Rule],
opts2___Rule
]:=
Module[{sites,ops},(
{sites,ops}=Transpose@siteoplist;
SiteDependentSuperoperator[
Transpose@{sites,
DoubleCommutationSuperoperator[op,#,opts1]&/@ops
},
opts2
]
)];


(* ::Input::Initialization:: *)
DoubleCommutationSuperoperator[
SiteDependentOperator[siteoplist1:{{_,_}..},opts1___Rule],
SiteDependentOperator[siteoplist2:{{_,_}..},opts2___Rule],
opts3___Rule
]:=
Module[{sites1,ops1,sites2,ops2},(
{sites1,ops1}=Transpose@siteoplist1;
{sites2,ops2}=Transpose@siteoplist2;
If[!MatchQ[sites1,sites2],
(Message[SiteDependentOperator::incompatsites];$Failed),
SiteDependentSuperoperator[
Transpose@{sites1,
Inner[
DoubleCommutationSuperoperator[#1,#2,opts3]&,
ops1,ops2,
List
]
},
opts1,opts2
]
]
)];


(* ::Input::Initialization:: *)
SiteDependentOperator::badlen="The number of sites in SiteDependentOperator must be the same as the number of operators.";


(* ::Input::Initialization:: *)
SiteDependentOperator::undefsites="The set of exchanging sites must be defined by using SetSites.";


(* ::Input::Initialization:: *)
SiteDependentOperator::badsites="One or more of the sites `1` is not a member of the current set of sites `2`";


(* ::Input::Initialization:: *)
SiteDependentOperator::invalarg="The first argument of SiteDependentOperator must be an operator or a List.";


(* ::Input::Initialization:: *)
SiteDependentOperator::incompatsites="Two SiteDependentOperator objects may only be combined if they use the same set of sites.";


(* ::Input::Initialization:: *)
SiteDependentOperator::badtimes="Dot must be used to multiply SiteDependentOperator with another SiteDependentOperator or with an operator.";


(* ::Input::Initialization:: *)
ExtendedOperatorVectorRepresentation[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
ExtendedOperatorVectorRepresentation[arg:Except[_Rule],opts___Rule]:=ExtendedOperatorVectorRepresentation[arg,ExtendedOperatorBasis[],opts];


(* ::Input::Initialization:: *)
ExtendedOperatorVectorRepresentation[num:(_?NumericQ|_Symbol),xopb_ExtendedOperatorBasis,opts___Rule]:=
ExtendedOperatorVectorRepresentation[num*UnityOperator[],xopb,opts];


(* ::Input::Initialization:: *)
ExtendedOperatorVectorRepresentation[op_?OperatorQ,xopb_ExtendedOperatorBasis,opts___Rule]:=
ExtendedOperatorVectorRepresentation[
SiteDependentOperator[Sites[xopb],op],xopb,opts
];


(* ::Input::Initialization:: *)
ExtendedOperatorVectorRepresentation[sdop_SiteDependentOperator,xopb_ExtendedOperatorBasis,opts___Rule]/;!ContainsAll[Sites[xopb],Sites[sdop]]:=
(Message[ExtendedOperatorVectorRepresentation::incompatsites];$Failed);


(* ::Input::Initialization:: *)
ExtendedOperatorVectorRepresentation[sdop_SiteDependentOperator,xopb_ExtendedOperatorBasis,opts___Rule]:=Module[{sdopsites,xopbsites,sdops,uniqueops,ops,uniqueoppos,uniqueopvecreps,opbasis},(
{sdopsites,sdops}=Transpose@First@sdop;
xopbsites=Sites[xopb];
opbasis=OperatorBasis[xopb];
uniqueops=First/@Tally[Append[sdops,NullOperator[]]];
ops=Flatten[
Function[site,
If[MemberQ[sdopsites,site],
Pick[sdops,sdopsites,site],
NullOperator[]
]
]/@xopbsites
];
uniqueoppos=Flatten[Position[uniqueops,#]&/@ops];
uniqueopvecreps=OperatorVectorRepresentation[#,opbasis]&/@uniqueops;
Join@@uniqueopvecreps[[uniqueoppos]]
)];


(* ::Input::Initialization:: *)
ExtendedOperatorVectorRepresentation::incompatsites="The sites used in the SiteDependentOperator must all be members of the sites used in the ExtendedOperatorBasis.";


(* ::Input::Initialization:: *)
SiteDependentSuperoperator[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
SiteDependentSuperoperator[sop_?SuperoperatorQ,opts___Rule]:=SiteDependentSuperoperator[{sop},opts];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator[notsop:Except[_?SuperoperatorQ|_List],opts___Rule]:=
(Message[SiteDependentSuperoperator::invalarg];$Failed);


(* ::Input::Initialization:: *)
SiteDependentSuperoperator[{sop_?SuperoperatorQ},opts___Rule]:=SiteDependentSuperoperator[Table[sop,{Length@Sites[]}],opts];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator[sops:{_?SuperoperatorQ...},opts___Rule]:=SiteDependentSuperoperator[Sites[],sops,opts];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator[Undefined,sops:{_?SuperoperatorQ...},opts___Rule]:=(Message[SiteDependentSuperoperator::undefsites];$Failed);


(* ::Input::Initialization:: *)
SiteDependentSuperoperator[sites_List,sop_?SuperoperatorQ,opts___Rule]:=SiteDependentSuperoperator[sites,Table[sop,{Length[sites]}],opts];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator[sites_List,sops:{_?SuperoperatorQ...},opts___Rule]/;Length[sops]!=Length@sites:=(Message[SiteDependentSuperoperator::badlen];$Failed);


(* ::Input::Initialization:: *)
SiteDependentSuperoperator[sites_List,sops:{_?SuperoperatorQ...},opts___Rule]:=
SiteDependentSuperoperator[Transpose[{sites,sops}],opts];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator[{i_,sopi_?SuperoperatorQ},opts___Rule]:=SiteDependentSuperoperator[{{i,sopi}},opts];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator[sitesoplist:{{_,_}..},opts___Rule]/;MatchQ[Sites[],Undefined]:=(SetSites[First/@sitesoplist];SiteDependentSuperoperator[sitesoplist,opts]);


(* ::Input::Initialization:: *)
SiteDependentSuperoperator[sitesoplist:{{_,_}..},opts___Rule]:=
Module[{sites},(
Message[SiteDependentSuperoperator::badsites,sites,Sites[]];
$Failed
)/;(
sites=First/@sitesoplist;
!ContainsAll[Sites[],sites]
)];


(* ::Input::Initialization:: *)
Sites[SiteDependentSuperoperator[sitesoplist:{{_,_}..},opts___Rule]]:=First/@sitesoplist;


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Times[a___,
n:(_Symbol|_?NumericQ),
SiteDependentSuperoperator[sitesoplist:{{_,_}..},opts___Rule],
b___]:=
Module[{sites,sops},(
{sites,sops}=Transpose@sitesoplist;
Times[a,
SiteDependentSuperoperator[
Transpose[{sites,n*sops}],
opts
],
b
]
)
];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Times[a___,
sdsop_SiteDependentSuperoperator,
n:(_Symbol|_?NumericQ),
b___]:=Times[a,n,sdsop,b];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Times[a___,sdsop_SiteDependentSuperoperator,sop_,b___]/;SuperoperatorQ[sop]||MatchQ[sop,_SiteDependentSuperoperator]:=(Message[SiteDependentSuperoperator::badtimes];$Failed);


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Times[a___,sop_,sdsop_SiteDependentSuperoperator,b___]/;SuperoperatorQ[sop]||MatchQ[sop,_SiteDependentSuperoperator]:=(Message[SiteDependentSuperoperator::badtimes];$Failed);


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Dot[a___,
n:(_?NumericQ|_Symbol),
SiteDependentSuperoperator[sitesoplist:{{_,_}..},opts___Rule],
b___]:=
Module[{sites,sops},(
{sites,sops}=Transpose@sitesoplist;
Dot[a,
SiteDependentSuperoperator[
Transpose[{sites,n*sops}],
opts
],
b
]
)
];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Dot[a___,
sdsop_SiteDependentSuperoperator,
n:(_?NumericQ|_Symbol),
b___]:=Dot[a,n,sdsop,b];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Dot[a___,
SiteDependentSuperoperator[sitesoplist1:{{_,_}..},opts1___Rule],
SiteDependentSuperoperator[sitesoplist2:{{_,_}..},opts2___Rule],
b___]:=
Module[{sites1,sops1,sites2,sops2},(
{sites1,sops1}=Transpose@sitesoplist1;
{sites2,sops2}=Transpose@sitesoplist2;
If[!MatchQ[sites1,sites2],
(Message[SiteDependentSuperoperator::incompatsites];$Failed),
Dot[a,
SiteDependentSuperoperator[
Transpose[{sites1,Inner[Dot,sops1,sops2,List]}],
Evaluate@SimplifyRules[
opts1,opts2
]
],b]
]
)];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Dot[a___,
sop_?SuperoperatorQ,
SiteDependentSuperoperator[sitesoplist:{{_,_}..},opts___Rule],
b___]:=
Module[{sites,sops},(
{sites,sops}=Transpose@sitesoplist;
Dot[a,
SiteDependentSuperoperator[
Transpose[{sites,Dot[sop,#]&/@sops}],
opts
],
b
]
)
];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Dot[a___,
SiteDependentSuperoperator[sitesoplist:{{_,_}..},opts___Rule],
sop_?SuperoperatorQ,
b___]:=
Module[{sites,sops},(
{sites,sops}=Transpose@sitesoplist;
Dot[a,
SiteDependentSuperoperator[
Transpose[{sites,Dot[#,sop]&/@sops}],
opts
],
b
]
)
];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Plus[a___,
n:(_?NumericQ|_Symbol),
sdsop_SiteDependentSuperoperator,
b___]:=
Plus[a,n*UnityOperator[],sdsop,b];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Dot[a___,
sdsop_SiteDependentSuperoperator,
n:(_?NumericQ|_Symbol),
b___]:=Plus[a,n,sdsop,b];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Plus[a___,
SiteDependentSuperoperator[sitesoplist1:{{_,_}..},opts1___Rule],
SiteDependentSuperoperator[sitesoplist2:{{_,_}..},opts2___Rule],
b___]:=
Module[{sites1,sops1,sites2,sops2},(
{sites1,sops1}=Transpose@sitesoplist1;
{sites2,sops2}=Transpose@sitesoplist2;
If[!MatchQ[sites1,sites2],
(Message[SiteDependentSuperoperator::incompatsites];$Failed),
Plus[a,
SiteDependentSuperoperator[
Transpose[{sites1,Inner[Plus,sops1,sops2,List]}],
Evaluate@SimplifyRules[
opts1,opts2
]
],b]
]
)];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Plus[a___,
sop_?SuperoperatorQ,
SiteDependentSuperoperator[sitesoplist:{{_,_}..},opts___Rule],
b___]:=
Module[{sites,sops},(
{sites,sops}=Transpose@sitesoplist;
Plus[a,
SiteDependentSuperoperator[
Transpose[{sites,Plus[sop,#]&/@sops}],
opts
],
b
]
)
];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Plus[a___,
SiteDependentSuperoperator[sitesoplist:{{_,_}..},opts___Rule],
sop_?SuperoperatorQ,
b___]:=
Module[{sites,sops},(
{sites,sops}=Transpose@sitesoplist;
Plus[a,
SiteDependentSuperoperator[
Transpose[{sites,Plus[#,sop]&/@sops}],
opts
],
b
]
)
];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Exp[SiteDependentSuperoperator[sitesoplist:{{_,_}..},opts___Rule]]:=
Module[{sites,sops},(
{sites,sops}=Transpose@sitesoplist;
SiteDependentSuperoperator[
Transpose[{sites,Exp/@sops}],
opts
]
)];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Power[SiteDependentSuperoperator[sitesoplist:{{_,_}..},opts___Rule],n_]:=
Module[{sites,sops},(
{sites,sops}=Transpose@sitesoplist;
SiteDependentSuperoperator[
Transpose[{sites,Power[#,n]&/@sops}],
opts
]
)];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator/:
HoldPattern@Power[n_,SiteDependentSuperoperator[sitesoplist:{{_,_}..},opts___Rule]]:=
Module[{sites,sops},(
{sites,sops}=Transpose@sitesoplist;
SiteDependentSuperoperator[
Transpose[{sites,Power[n,#]&/@sops}],
opts
]
)];


(* ::Input::Initialization:: *)
SiteDependentSuperoperator::badlen="The number of sites in SiteDependentSuperoperator must be the same as the number of superoperators.";


(* ::Input::Initialization:: *)
SiteDependentSuperoperator::undefsites="The set of exchanging sites must be defined by using SetSites.";


(* ::Input::Initialization:: *)
SiteDependentSuperoperator::badsites="One or more of the sites `1` is not a member of the current set of sites `2`";


(* ::Input::Initialization:: *)
SiteDependentSuperoperator::invalarg="The first argument of SiteDependentSuperoperator must be a superoperator or a List.";


(* ::Input::Initialization:: *)
SiteDependentSuperoperator::incompatsites="The product of two SiteDependentSuperoperator objects is only defined for the same set of sites.";


(* ::Input::Initialization:: *)
SiteDependentSuperoperator::badtimes="Dot must be used to multiply SiteDependentSuperoperator with another SiteDependentSuperoperator or with a superoperator.";


(* ::Input::Initialization:: *)
ExtendedSuperoperatorMatrixRepresentation[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
ExtendedSuperoperatorMatrixRepresentation[arg:Except[_Rule],opts___Rule]:=ExtendedSuperoperatorMatrixRepresentation[arg,ExtendedOperatorBasis[],opts];


(* ::Input::Initialization:: *)
ExtendedSuperoperatorMatrixRepresentation[num:(_?NumericQ|_Symbol),xopb_ExtendedOperatorBasis,opts___Rule]:=
ExtendedSuperoperatorMatrixRepresentation[num*UnitySuperoperator[],xopb,opts];


(* ::Input::Initialization:: *)
ExtendedSuperoperatorMatrixRepresentation[sop_?SuperoperatorQ,xopb_ExtendedOperatorBasis,opts___Rule]:=
ExtendedSuperoperatorMatrixRepresentation[
SiteDependentSuperoperator[Sites[xopb],sop],xopb,opts
];


(* ::Input::Initialization:: *)
ExtendedSuperoperatorMatrixRepresentation[sdsop_SiteDependentSuperoperator,xopb_ExtendedOperatorBasis,opts___Rule]/;!ContainsAll[Sites[xopb],Sites[sdsop]]:=
(Message[ExtendedSuperoperatorMatrixRepresentation::incompatsites];$Failed);


(* ::Input::Initialization:: *)
ExtendedSuperoperatorMatrixRepresentation[sdsop_SiteDependentSuperoperator,xopb_ExtendedOperatorBasis,opts___Rule]:=Module[{sdsopsites,xopbsites,sdsops,uniquesops,sops,uniquesoppos,uniquesopmatreps,sopmatreps,opbasis,nsite,nL},(
{sdsopsites,sdsops}=Transpose@First@sdsop;
xopbsites=Sites[xopb];
opbasis=OperatorBasis[xopb];
nsite=Length@xopbsites;
nL=OperatorBasisDimension[opbasis];
uniquesops=First/@Tally[Append[sdsops,NullSuperoperator[]]];
sops=Flatten[
Function[site,
If[MemberQ[sdsopsites,site],
Pick[sdsops,sdsopsites,site],
NullSuperoperator[]
]
]/@xopbsites
];
uniquesoppos=Flatten[Position[uniquesops,#]&/@sops];
uniquesopmatreps=SuperoperatorMatrixRepresentation[#,opbasis]&/@uniquesops;
sopmatreps=uniquesopmatreps[[uniquesoppos]];
Join@@Table[
ArrayPad[sopmatreps[[i]],{0,{(i-1)*nL,(nsite-i)*nL}}],
{i,1,nsite}
]
)];


(* ::Input::Initialization:: *)
ExtendedSuperoperatorMatrixRepresentation::incompatsites="The sites used in the SiteDependentSuperoperator must all be members of the sites used in the ExtendedOperatorBasis.";


(* ::Input::Initialization:: *)
Options[KineticExchangeMatrix]={ImposeDetailedBalance->True,DetailedBalance->False};


(* ::Input::Initialization:: *)
KineticExchangeMatrix[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
KineticExchangeMatrix[sites___,rulekval:{_Rule,_},opts___Rule]:=KineticExchangeMatrix[sites,{rulekval},opts];


(* ::Input::Initialization:: *)
KineticExchangeMatrix[rulekvallist:{{_Rule,_}...},opts___Rule]:=KineticExchangeMatrix[Sites[],rulekvallist,opts];


(* ::Input::Initialization:: *)
KineticExchangeMatrix[Undefined,rulekvallist:{{_Rule,_}...},opts___Rule]:=(Message[KineticExchangeMatrix::undefsites];$Failed);


(* ::Input::Initialization:: *)
KineticExchangeMatrix[sites_List,rulekvallist:{{_Rule,_}...},opts___Rule]:=
Module[{rules,kvals},(
Message[KineticExchangeMatrix::duprules];$Failed
)/;(
{rules,kvals}=Transpose@rulekvallist;
!DuplicateFreeQ[rules]
)];


(* ::Input::Initialization:: *)
KineticExchangeMatrix[sites_List,rulekvallist:{{_Rule,_}...},opts___Rule]:=
Module[{rules,kvals,invalrules},(
invalrules=Select[rulekvallist,!ContainsAll[sites,List@@(First@#)]&];
Message[KineticExchangeMatrix::invalspecs,invalrules];
$Failed
)/;(
{rules,kvals}=Transpose@rulekvallist;
!ContainsAll[sites,Apply[Sequence,rules,1]]
)];


(* ::Input::Initialization:: *)
KineticExchangeMatrix[sites_List,rulekvallist:{{_Rule,_}...},opts___Rule]:=
Module[{rules,kvals,symmrulekvallist},(
KineticExchangeMatrix[sites,symmrulekvallist,opts]
)/;(
{rules,kvals}=Transpose@rulekvallist;
symmrulekvallist=First/@GatherBy[
Join[rulekvallist,Transpose[{Reverse/@rules,kvals}]],First];
!MatchQ[Sort[First/@symmrulekvallist],Sort[First/@rulekvallist]]
)];


(* ::Input::Initialization:: *)
KineticExchangeMatrix[Kmat:(_SparseArray|{{Except[_Rule]...}...}),opts___Rule]:=KineticExchangeMatrix[Sites[],Kmat,opts];


(* ::Input::Initialization:: *)
KineticExchangeMatrix[Undefined,Kmat:(_SparseArray|{{Except[_Rule]...}...}),opts___Rule]:=(Message[KineticExchangeMatrix::undefsites];$Failed);


(* ::Input::Initialization:: *)
KineticExchangeMatrix[sites_List,Kmat:(_SparseArray|{{Except[_Rule]...}...}),opts___Rule]/;Dimensions[Kmat]!={Length@sites,Length@sites}:=(Message[KineticExchangeMatrix::baddims];$Failed);


(* ::Input::Initialization:: *)
KineticExchangeMatrix[sites_List,rulekvallist:{{_Rule,_}...},opts___Rule]:=
Module[{rules,kvals,Kmat,n,matpos},(
n=Length[sites];
{rules,kvals}=Transpose@rulekvallist;
matpos=Function[rule,Reverse@Flatten[Position[sites,#]&/@(List@@rule)]]/@rules;
KineticExchangeMatrix[
sites,
ReplacePart[
SparseArray[{_,_}->0,{n,n}],
Apply[Rule,Transpose[{matpos,kvals}],1]
],
opts
]
)];


(* ::Input::Initialization:: *)
KineticExchangeMatrix[sites_List,Kmat:(_SparseArray|{{Except[_Rule]...}...}),opts___Rule]/;MatchQ[{ImposeDetailedBalance,DetailedBalance}/.{opts}/.Options[KineticExchangeMatrix],
{True,False}]:=
Module[{},(
KineticExchangeMatrix[sites,
SparseArray@Transpose@Table[
Which[
Plus@@Kmat[[All,col]]==0,
	Kmat[[All,col]],
Kmat[[col,col]]==0,
	ReplacePart[Kmat[[All,col]],col->-Plus@@Kmat[[All,col]]],
True,
	(Message[KineticExchangeMatrix::detbalerr];$Failed)
],
{col,1,Length[sites]}
],
SimplifyRules[
DetailedBalance->True,
opts
]
]
)];


(* ::Input::Initialization:: *)
KineticExchangeMatrix/:Expand[KineticExchangeMatrix[sites_List,Kmat:(_SparseArray|{{Except[_Rule]...}...}),opts___Rule]]:=Kmat;


(* ::Input::Initialization:: *)
KineticExchangeMatrix::undefsites="The set of exchanging sites must be defined by using SetSites.";


(* ::Input::Initialization:: *)
KineticExchangeMatrix::baddims="The kinetic exchange matrix must be a square matrix with dimension equal to the number of sites.";


(* ::Input::Initialization:: *)
KineticExchangeMatrix::duprules="The rule defining a kinetic rate constant may only appear once.";


(* ::Input::Initialization:: *)
KineticExchangeMatrix::invalspecs="The following rate specifications refer to sites that are not members of the current set of exchanging sites, as defined by SetSites[..]: `1`";


(* ::Input::Initialization:: *)
KineticExchangeMatrix::detbalerr="A conflict has been encountered while imposing detailed balance.";


(* ::Input::Initialization:: *)
Options[KineticExchangeSuperoperator]={ImposeDetailedBalance->True,DetailedBalance->False};


(* ::Input::Initialization:: *)
KineticExchangeSuperoperator[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
KineticExchangeSuperoperator[K:Except[_Rule],opts___Rule]:=KineticExchangeSuperoperator[Sites[],K,opts];


(* ::Input::Initialization:: *)
KineticExchangeSuperoperator[Undefined,K:Except[_Rule],opts___Rule]:=(Message[KineticExchangeSuperoperator::undefsites];$Failed);


(* ::Input::Initialization:: *)
KineticExchangeSuperoperator[sites_List, K:Except[_Rule],opts___Rule]:=KineticExchangeSuperoperator[False,sites, K,opts];


(* ::Input::Initialization:: *)
KineticExchangeSuperoperator[False,sites_List,K:Except[_Rule|_KineticExchangeMatrix],opts___Rule]:=
KineticExchangeSuperoperator[False,sites,
KineticExchangeMatrix[sites,K,
Sequence@@SimplifyRules[
FilterRules[Join[{opts},Options[KineticExchangeSuperoperator]],
Options[KineticExchangeMatrix]]
]
],
opts
];


(* ::Input::Initialization:: *)
KineticExchangeSuperoperator[False,sites1_List,
KineticExchangeMatrix[sites2_List,mat_?MatrixQ,kxmopts___Rule],
opts___Rule]/;(sites1!=sites2):=
(Message[KineticExchangeSuperoperator::mismatchsites];$Failed);


(* ::Input::Initialization:: *)
KineticExchangeSuperoperator[False,sites_List,
KineticExchangeMatrix[sites_List,mat_?MatrixQ,kxmopts___Rule],
opts___Rule]:=
(If[!(DetailedBalance/.{kxmopts}/.Options[KineticExchangeMatrix]),
Message[KineticExchangeSuperoperator::notdetbal]];
KineticExchangeSuperoperator[True,sites,mat,
Sequence@@(SimplifyRules@FilterRules[{kxmopts,opts},{DetailedBalance->_}])
]);


(* ::Input::Initialization:: *)
Sites[KineticExchangeSuperoperator[True,sites_List,mat_?MatrixQ,opts___Rule]]^:=sites;


(* ::Input::Initialization:: *)
KineticExchangeMatrix[KineticExchangeSuperoperator[True,sites_List,Kmat_?MatrixQ,opts___Rule]]^:=Kmat;


(* ::Input::Initialization:: *)
KineticExchangeSuperoperator/:
SuperoperatorMatrixRepresentation[
Ksop_KineticExchangeSuperoperator,
opb_?DefinedOperatorBasisQ,opts___Rule]:=
ExtendedSuperoperatorMatrixRepresentation[Ksop,
ExtendedOperatorBasis[Sites[Ksop],Ksop],
opts];


(* ::Input::Initialization:: *)
KineticExchangeSuperoperator/:
ExtendedSuperoperatorMatrixRepresentation[
KineticExchangeSuperoperator[True,sites_List,Kmat_?MatrixQ,opts___Rule],
xopb_ExtendedOperatorBasis
]:=
SparseArray@DirectProduct[
Kmat,
SuperoperatorMatrixRepresentation[
UnitySuperoperator[],
OperatorBasis[xopb]
]
];


(* ::Input::Initialization:: *)
KineticExchangeSuperoperator::undefsites="The set of exchanging sites must be defined by using SetSites.";


(* ::Input::Initialization:: *)
KineticExchangeSuperoperator::mismatchsites="The specified sites for KineticExchangeSuperoperator and KineticExchangeMatrix must match.";


(* ::Input::Initialization:: *)
KineticExchangeSuperoperator::notdetbal="The specified kinetic exchange matrix does not display detailed balance.";


(* ::Input::Initialization:: *)
End[];
EndPackage[];
