(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["SD`SpinDensityOperators`",
{"Global`",
"SpinDynamica`",
"General`UserLevel`",
"General`Matrices`",
"General`Miscellaneous`",
"QM`Hilbert`",
"QM`SpinOperators`",
"QM`Liouville`",
"SD`Generators`",
"Rotations`Wigner`",
"Units`",
"General`PhysicalConstants`"
}];


(* ::Input::Initialization:: *)
Temperature::usage="Temperature is an option for ThermalEquilibriumDensityOperator and ThermalizeSuperoperator. The default is Temperature\[Rule]Infinity in which case thermalization has no effect.";


(* ::Input::Initialization:: *)
HighTemperatureApproximation::usage="HighTemperatureApproximation is an option for ThermalEquilibriumDensityOperator and ThermalizeSuperoperator. The default is HighTemperatureApproximation\[Rule]True in which case high-order thermal terms are ignored.";


(* ::Input::Initialization:: *)
HighTemperatureApproximationWarningThreshold::usage="HighTemperatureApproximationWarningThreshold is an option for ThermalEquilibriumDensityOperator and ThermalizeSuperoperator. The default is HighTemperatureApproximationWarningThreshold\[Rule]0.9. A warning is given if HighTemperatureApproximation\[Rule]True and one of the exponential factors in the Boltzmann distribution is less than this number. The warning may be disabled using HighTemperatureApproximationWarningThreshold\[Rule]0.";


(* ::Input::Initialization:: *)
ThermalEquilibriumDensityOperator::usage="ThermalEquilibriumDensityOperator[Hlab, Temperature,options] sets up a thermal equilibrium density operator under the laboratory frame Hamiltonian Hlab at the specified temperature. The syntax ThermalEquilibriumDensityOperator[{Hlab, Temperature},options] may also be used.
The options may include HighTemperatureApproximation\[Rule]False or HighTemperatureApproximation\[Rule]True.";


(* ::Input::Initialization:: *)
PolarizedDensityOperator::usage=
"PolarizedDensityOperator[<args>] sets up a density operator in which one, or several spins, are polarized along an arbitrary axis. In general the polarization levels and polarization directions may be defined individually for each spin. 
One special case of the syntax is PolarizedDensityOperator[{p,\"z\"}] which generates a density operator with polarization level p along the z-axis for all spins in the current SpinSystem[]. Similarly, PolarizedDensityOperator[{j,k,l},{p,\"z\"}] generates a density operator with polarization level p along the z-axis for spins {j,k,l}. 
The most general syntax is PolarizedDensityOperator[{{j,{polj,axisj}},{k,{polk,axisk}}..},spinsystem] which constructs a density operator for spinsystem, corresponding to polarization polj for spins j along the axis axisj, and similarly for spins k, etc. The polarizations {polj,polk..} are in the range -1 to +1, with -1 indicating complete negative polarization, and +1 indicating complete positive polarization. If a polarization argument is omitted, a value of +1 is assumed.
If spinsystem is omitted, the current SpinSystem[] is assumed. 
The spin labels {j,k..} must be members of spinsystem and cannot be duplicated.
The axis arguments may take values \"x\",\"y\", \"z\", or a number \[Phi], or a pair of polar angles {\[Theta],\[Phi]}. The phase \[Phi] denotes an axis in the transverse plane. The polar angles {\[Theta],\[Phi]} may be used to define an arbitrary direction. If an axis argument is omitted, the axis \"z\" is assumed. 
The syntax PolarizedDensityOperator[{j,k..},{pol,axis},spinsystem] assumes all spins {j,k..} have polarization level pol along axis. 
The syntax PolarizedDensityOperator[{j,k..},pol,spinsystem] assumes all spins {j,k..} have polarization level pol along the z-axis.
The syntax PolarizedDensityOperator[pol, spinsystem] assumes all spins in the spinsystem have polarization level pol along the z-axis.
The syntax PolarizedDensityOperator[axis, spinsystem] assumes all spins in the spinsystem have polarization level +1 along axis.
";


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator::usage=
"SingletPolarizedDensityOperator[<args>] sets up a density operator in which one spin pair, or several spin pairs, exhibit singlet polarization. In general the polarization levels and polarization directions may be defined individually for each spin pair.
In the case where the current SpinSystem[] is a spin-1/2 pair, SingletPolarizedDensityOperator[p] generates a density operator with singlet polarization p. 
If the current SpinSystem[] contains more than two spins-1/2, the syntax SingletPolarizedDensityOperator[{j,k},p] generates a density operator with singlet polarization p for the spin pair {j,k}, and the syntax SingletPolarizedDensityOperator[{{j,k},{l,m}},p] generates a density operator with singlet polarization p for the spin pairs {j,k} and {l,m}. 
The most general syntax is SingletPolarizedDensityOperator[{{{j,k},pjk},{{l,m},plm}..},spinsystem] which allows individual singlet polarization levels for distinct spin pairs. If spinsystem is omitted, the current SpinSystem[] is assumed.
";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
Options[ThermalEquilibriumDensityOperator]={HighTemperatureApproximation->True,HighTemperatureApproximationWarningThreshold->0.9,
Temperature->Infinity
};


(* ::Input::Initialization:: *)
ThermalEquilibriumDensityOperator[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
ThermalEquilibriumDensityOperator[H\[CapitalTheta]_?OperatorQ,opts___Rule]:=ThermalEquilibriumDensityOperator[H\[CapitalTheta],
Temperature/.{opts}/.Options[ThermalEquilibriumDensityOperator],
opts
];


(* ::Input::Initialization:: *)
ThermalEquilibriumDensityOperator[H\[CapitalTheta]_?OperatorQ,T:Except[_Rule],opts___Rule]:=ThermalEquilibriumDensityOperator[{H\[CapitalTheta],T},opts];


(* ::Input::Initialization:: *)
ThermalEquilibriumDensityOperator[{H\[CapitalTheta]_?OperatorQ,T_?NumericQ},opts___Rule]/;MatchQ[UnassignedSymbols[{H\[CapitalTheta],T},PermittedSymbols->{\[HBar],kB}],{}]:=
Module[{H\[Theta]mat,H\[Theta]evals,H\[Theta]evecs,expfacs,Z,htapprox,htapproxwth,numericH\[Theta]mat,X,Xinv},
{htapprox,htapproxwth}={HighTemperatureApproximation,HighTemperatureApproximationWarningThreshold}/.{opts}/.Options[ThermalEquilibriumDensityOperator];
H\[Theta]mat=MatrixRepresentation[H\[CapitalTheta],ZeemanBasis[]]/.PhysicalConstantValues;
{H\[Theta]evals,H\[Theta]evecs}=Eigensystem[H\[Theta]mat];
expfacs=If[htapprox,
(( 1+(-(\[HBar]*#)/(kB*T)))&/@H\[Theta]evals),
(Exp[-(\[HBar]*#)/(kB*T)]&/@H\[Theta]evals)
]/.PhysicalConstantValues;
If[((Or@@((#<htapproxwth)&/@expfacs))&&htapprox),Message[ThermalEquilibriumDensityOperator::highTapproxwarning]
];
Z=Plus@@expfacs;
X=SparseArray[Transpose[Normalize/@H\[Theta]evecs]];
Xinv=ConjugateTranspose[X];
Operator[
X . SparseArray[Band[{1,1}]->expfacs/Z] . Xinv,
ZeemanBasis[]
]];


(* ::Input::Initialization:: *)
ThermalEquilibriumDensityOperator[{H\[CapitalTheta]_?OperatorQ,T_},opts___Rule]/;!MatchQ[UnassignedSymbols[{H\[CapitalTheta],T},PermittedSymbols->{\[HBar],kB}],{}]&&
TrueQ[HighTemperatureApproximation/.{opts}/.Options[ThermalEquilibriumDensityOperator]]:=
Module[{Z},(
Message[ThermalEquilibriumDensityOperator::highTapprox];
If[UserLevel[]<3,Message[ThermalEquilibriumDensityOperator::symblowul]];
Z=BasisDimension[Basis[]]^-1;
Z(UnityOperator[]-\[HBar] H\[CapitalTheta]/(kB*T))
)];


(* ::Input::Initialization:: *)
ThermalEquilibriumDensityOperator[{H\[CapitalTheta]_?OperatorQ,T_},opts___Rule]/;!MatchQ[UnassignedSymbols[{H\[CapitalTheta],T},PermittedSymbols->{\[HBar],kB}],{}]&&
!TrueQ[HighTemperatureApproximation/.{opts}/.Options[ThermalEquilibriumDensityOperator]]:=
Module[{Z,expfacs},(
If[UserLevel[]<3,Message[ThermalEquilibriumDensityOperator::symblowul]];
Exp[-\[HBar] H\[CapitalTheta]/(kB*T)]/Plus@@Diagonal[MatrixRepresentation[Exp[-\[HBar] H\[CapitalTheta]/(kB*T)]]]
)];


(* ::Input::Initialization:: *)
ThermalEquilibriumDensityOperator::highTapproxwarning="The high-temperature approximation may not be valid. The option HighTemperatureApproximation\[Rule]False is recommended.";


(* ::Input::Initialization:: *)
ThermalEquilibriumDensityOperator::highTapprox="The high-temperature approximation will be assumed. Disable this, if desired, by using HighTemperatureApproximation\[Rule]False.";


(* ::Input::Initialization:: *)
ThermalEquilibriumDensityOperator::symblowul="A UserLevel of at least 3 is recommended when using ThermalEquilibriumDensityOperator with symbolic arguments. Execution with the current UserLevel may be slow. Execute SetUserLevel[3] to increase the UserLevel.";


(* ::Input::Initialization:: *)
PolarizedDensityOperator[args___]:=(Message[SpinSystem::notready];Abort[])/;MatchQ[SpinSystem/.Options[SpinSystem],Undefined];


(* ::Input::Initialization:: *)
PolarizedDensityOperator[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
PolarizedDensityOperator[]:=PolarizedDensityOperator[All];


(* ::Input::Initialization:: *)
PolarizedDensityOperator[arg_]:=PolarizedDensityOperator[arg,SpinSystem[]];


(* ::Input::Initialization:: *)
PolarizedDensityOperator[args__]/;!MatrixQ[Last@{args}]:=PolarizedDensityOperator[args,SpinSystem[]];


(* ::Input::Initialization:: *)
PolarizedDensityOperator[All,spinsys_?MatrixQ]:=PolarizedDensityOperator[First/@spinsys,spinsys];


(* ::Input::Initialization:: *)
PolarizedDensityOperator[pol:Except[_List|_String|All],spinsys_?MatrixQ]:=PolarizedDensityOperator[First/@spinsys,pol,spinsys];


(* ::Input::Initialization:: *)
PolarizedDensityOperator[spins:{Except[_List]..},spinsys_?MatrixQ]:=PolarizedDensityOperator[First/@spinsys,spinsys];


(* ::Input::Initialization:: *)
PolarizedDensityOperator[spins:{Except[_List]..},spinsys_?MatrixQ]/;ValidSpinQ[spins,spinsys]:=PolarizedDensityOperator[spins,{1,"z"},spinsys];


(* ::Input::Initialization:: *)
PolarizedDensityOperator[axis_?ValidAxisSpecificationQ,spinsys_?MatrixQ]:=PolarizedDensityOperator[First/@spinsys,{1,axis},spinsys];


(* ::Input::Initialization:: *)
 PolarizedDensityOperator[{pol:(_?NumericQ|_Symbol),axis_?ValidAxisSpecificationQ},spinsys_?MatrixQ]:=
PolarizedDensityOperator[First/@spinsys,{pol,axis},spinsys]; 


(* ::Input::Initialization:: *)
PolarizedDensityOperator[j:Except[_List],axis_?ValidAxisSpecificationQ,spinsys_?MatrixQ]/;ValidSpinQ[j,spinsys]:=PolarizedDensityOperator[j,{1,axis},spinsys];


(* ::Input::Initialization:: *)
PolarizedDensityOperator[j:Except[_List],{pol_,axis_?ValidAxisSpecificationQ},spinsys_?MatrixQ]/;ValidSpinQ[j,spinsys]:=PolarizedDensityOperator[{j},{pol,axis},spinsys];


(* ::Input::Initialization:: *)
PolarizedDensityOperator[spins:{Except[_List]..},pol:(_?NumericQ|_Symbol),spinsys_?MatrixQ]:=PolarizedDensityOperator[spins,{pol,"z"},spinsys];


(* ::Input::Initialization:: *)
PolarizedDensityOperator[spins:{Except[_List]..},axis_?ValidAxisSpecificationQ,spinsys_?MatrixQ]:=PolarizedDensityOperator[spins,{1,axis},spinsys];


(* ::Input::Initialization:: *)
PolarizedDensityOperator[spins:{Except[_List]..},{pol_,axis_?ValidAxisSpecificationQ},spinsys_?MatrixQ]:=
(PolarizedDensityOperator[{#,{pol,axis}}&/@spins,spinsys]);


(* ::Input::Initialization:: *)
PolarizedDensityOperator[polspecs:{{_,{_,_}}..},spinsys_?MatrixQ]:=
If[
FreeQ[#,$Failed],
(*PolarizedDensityOperator[polspecs,spinsys]=*)Simplify@Expand[#],
$Failed]&@
Module[{dim},(
dim=BasisDimension[ZeemanBasis[spinsys]];
dim^(Length[polspecs]-1)*
Apply[Dot,SingleSpinPolarizedDensityOperator[#,spinsys]&/@polspecs]
)];


(* ::Input::Initialization:: *)
SingleSpinPolarizedDensityOperator[{j:Except[_List],{pol_,axis_}},spinsys_]/;SpinQuantumNumber[j,spinsys]!=1/2:=(Message[PolarizedDensityOperator::notspinhf,j];$Failed)


(* ::Input::Initialization:: *)
SingleSpinPolarizedDensityOperator[{j:Except[_List],{pol_,axis_}},spinsys_]/;!ValidAxisSpecificationQ[axis]:=
(Message[PolarizedDensityOperator::badaxis];$Failed);


(* ::Input::Initialization:: *)
SingleSpinPolarizedDensityOperator[{j:Except[_List],{pol_,axis_}},spinsys_]/;TrueQ[pol>1]:=(Message[PolarizedDensityOperator::polgt1];$Failed);


(* ::Input::Initialization:: *)
SingleSpinPolarizedDensityOperator[{j:Except[_List],{pol_,axis_}},spinsys_]/;TrueQ[pol<-1]:=(Message[PolarizedDensityOperator::polltneg1];$Failed);


(* ::Input::Initialization:: *)
SingleSpinPolarizedDensityOperator[{j:Except[_List],{pol_,axis_}},spinsys_]/;!ValidSpinQ[j,spinsys]:=(Message[SpinSystem::invspin,j];$Failed);


(* ::Input::Initialization:: *)
SingleSpinPolarizedDensityOperator[{j_,{pol_,axis_}},spinsys_?MatrixQ]:=
Module[{dim},(
dim=BasisDimension[ZeemanBasis[spinsys]];
(*SingleSpinPolarizedDensityOperator[{j,pol,axis},spinsys]=*)dim^-1(UnityOperator[]+2 pol opI[j,axis])
)];


(* ::Input::Initialization:: *)
PolarizedDensityOperator::badaxis="Cannot interpret polarization axis specification.";


(* ::Input::Initialization:: *)
PolarizedDensityOperator::polgt1="The polarization level cannot be greater than 1.";


(* ::Input::Initialization:: *)
PolarizedDensityOperator::polltneg1="The polarization level cannot be less than -1.";


(* ::Input::Initialization:: *)
PolarizedDensityOperator::notspinhf="At the moment PolarizedDensityOperator cannot be used for spin quantum numbers I\[NotEqual]1/2.";


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[args___]:=(Message[SpinSystem::notready];Abort[])/;MatchQ[SpinSystem/.Options[SpinSystem],Undefined];


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[]:=
Module[{spinsys},(
spinsys=SpinSystem[];
If[MatchQ[spinsys,{{_,1/2},{_,1/2}}],SingletPolarizedDensityOperator[First/@spinsys],
(Message[SingletPolarizedDensityOperator::notspinpair];$Failed)
]
)];


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[args_]:=SingletPolarizedDensityOperator[args,SpinSystem[]];


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[args__]/;!MatrixQ[Last@{args}]:=SingletPolarizedDensityOperator[args,SpinSystem[]];


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[{{j:Except[_List],k:Except[_List]}},pol:Except[_List]]:=SingletPolarizedDensityOperator[{{j,k}},pol,SpinSystem[]];


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[spinpairs:({Except[_List],Except[_List]}|{{Except[_List],Except[_List]}..}),spinsys_?MatrixQ]:=SingletPolarizedDensityOperator[spinpairs,1,spinsys];


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[pol:Except[_List],spinsys_?MatrixQ]/;MatchQ[spinsys,{{_,1/2},{_,1/2}}]:=SingletPolarizedDensityOperator[First/@spinsys,pol,spinsys];


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[{j:Except[_List],k:Except[_List]},pol:Except[_List],spinsys_?MatrixQ]:=SingletPolarizedDensityOperator[{{j,k},pol},spinsys];


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[spinpairs:{{_,_}..},pol:Except[_List],spinsys_?MatrixQ]:=
SingletPolarizedDensityOperator[{#,pol}&/@spinpairs,spinsys];


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[polpairs:{{{Except[_List],Except[_List]},Except[_List]}..},spinsys_]:=
Module[{spinpairs},(
Message[SingletPolarizedDensityOperator::sharedspins];
$Failed
)/;(
spinpairs=First/@polpairs;
(Length[spinpairs]>1)&&(!Intersection[Sequence@@spinpairs]=={})
)
];


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[polpairs:{{{Except[_List],Except[_List]},_}..},spinsys_?MatrixQ]:=
If[
FreeQ[#,$Failed],
SingletPolarizedDensityOperator[polpairs,spinsys]=Simplify@Expand[#],
$Failed]&@
Module[{dim},(
dim=BasisDimension[ZeemanBasis[spinsys]];
SingletPolarizedDensityOperator[polpairs,spinsys]=Simplify[dim^(Length[polpairs]-1)*
Apply[Dot,SingletPolarizedDensityOperator[#,spinsys]&/@polpairs]
]
)];


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[{{j:Except[_List],k:Except[_List]},pol:Except[_List]},spinsys_]/;!ValidSpinQ[j,spinsys]:=(Message[SpinSystem::invspin,j];$Failed);


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[{{j:Except[_List],k:Except[_List]},pol:Except[_List]},spinsys_]/;!ValidSpinQ[k,spinsys]:=(Message[SpinSystem::invspin,k];$Failed);


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[{{j:Except[_List],k:Except[_List]},pol:Except[_List]},spinsys_]/;(SpinQuantumNumber[j,spinsys]!=1/2):=(Message[SingletPolarizedDensityOperator::notspinhf,j];$Failed);


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[{{j:Except[_List],k:Except[_List]},pol:Except[_List]},spinsys_]/;(SpinQuantumNumber[k,spinsys]!=1/2):=(Message[SingletPolarizedDensityOperator::notspinhf,k];$Failed);


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[{{j_,j_},pol:Except[_List]},spinsys_]:=(Message[SingletPolarizedDensityOperator::invalpair,{j,j}];$Failed);


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[{{j:Except[_List],k:Except[_List]},pol:Except[_List]},spinsys_]/;(pol>1):=(Message[SingletPolarizedDensityOperator::toobigpol];$Failed)


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[{{j:Except[_List],k:Except[_List]},pol:Except[_List]},spinsys_]/;(pol<-1/3):=(Message[SingletPolarizedDensityOperator::toonegpol];$Failed)


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator[{{j:Except[_List],k:Except[_List]},pol:Except[_List]},spinsys_?MatrixQ]:=
Module[{dim},(
dim=BasisDimension[ZeemanBasis[spinsys]];
SingletPolarizedDensityOperator[{{j,k},pol},spinsys]=Simplify[(4/dim)((1/4)UnityOperator[]- pol opI[j] . opI[k])]
)];


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator::notspinhf="Spin `1` is not spin-1/2.";


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator::invalpair="The spin pair `1` is invalid.";


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator::toobigpol="The singlet polarization cannot be larger than 1.";


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator::toonegpol="The singlet polarization cannot be less than -1/3.";


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator::sharedspins="Spins may not be shared between different pairs.";


(* ::Input::Initialization:: *)
SingletPolarizedDensityOperator::notspinpair="The current SpinSystem[] is not a spin-1/2 pair. The singlet spin pair must be specified explicitly.";


(* ::Input::Initialization:: *)
End[];
EndPackage[];



