(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["Rotations`Wigner`",
{"Global`",
"General`UserLevel`",
"SpinDynamica`",
"General`Miscellaneous`"}];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[WignerD,Infinity,
(
Unprotect[WignerD];
Off[WignerD::list];
Off[WignerD::argbu];
SyntaxInformation[WignerD]={"ArgumentsPattern"->{_,{_,_}...,OptionsPattern[]}};
Protect[WignerD];
)];


(* ::Input::Initialization:: *)
Unprotect[WignerD];


(* ::Input::Initialization:: *)
Wignerd::usage=
	"Wignerd[J][\[Beta]] is the reduced Wigner matrix (J integral or half-integral). Wignerd[J,{m2,m1}][\[Beta]] is the reduced Wigner function (element of the reduced Wigner matrix). Wignerd[J,{m}][\[Beta]] is the mth row of the reduced Wigner matrix; Wignerd[J,{{m}}][\[Beta]] is the mth column of the reduced Wigner matrix. In all cases the row and column indices run from +J to -J in descending order.";


(* ::Input::Initialization:: *)
WignerD::usage=
"WignerD is a built-in function in Mathematica 2.0 but has been given enhanced functionality in SpinDynamica, in order to maintain compatibility with previous code. The SpinDynamica definitions are as follows:
WignerD[J][{\[Alpha],\[Beta],\[Gamma]}] is the three-angle Wigner matrix for integral or half-integral J. WignerD[J]{{\[Alpha]2,\[Beta]2,\[Gamma]2},{\[Alpha]1,\[Beta]1,\[Gamma]1}..}] is the Wigner matrix for the overall rotation corresponding to the specified sequence of Euler rotations. WignerD[J,{m2,m1}][{\[Alpha],\[Beta],\[Gamma]}] is a three-angle Wigner function (Wigner matrix element). WignerD[J,{m}][{\[Alpha],\[Beta],\[Gamma]}] is the mth row of the Wigner matrix; WignerD[J,{{m}}][{\[Alpha],\[Beta],\[Gamma]}] is the mth column of the Wigner matrix. In all cases the row and column indices run from +J to -J in descending order.";


(* ::Input::Initialization:: *)
TensorElement::usage=
	"TensorElement[\[Lambda], \[Mu]][tensor] accesses the component \[Mu] of the rank \[Lambda] tensor (written as a list of length 2\[Lambda]+1).";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
FirstCallToWignerD=True;


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[WignerD,Infinity,(
Unprotect[WignerD];WignerD[args___]/;TrueQ[FirstCallToWignerD]&&($KernelID==0):=
(
Message[WignerD::mod];
Print[Button["For ?WignerD click <here>",Print[Style[WignerD::usage,"Usage"]]]//DisplayForm];
FirstCallToWignerD=False;
Protect[WignerD];
WignerD[args]
);
Protect[WignerD]
)];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[WignerD,Infinity,(
Unprotect[WignerD];
HoldPattern@WignerD[\[Lambda]_,{\[Mu]2_,\[Mu]1_}][{\[Alpha]:Except[_List],\[Beta]:Except[_List],\[Gamma]:Except[_List]}]:=0/;IntegerQ[2\[Lambda]]&&IntegerQ[2\[Mu]2]&&IntegerQ[2\[Mu]1]&&((Abs[2\[Mu]2]>2\[Lambda])||(Abs[2\[Mu]1]>2\[Lambda]));
Protect[WignerD]
)];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[WignerD,Infinity,(
Unprotect[WignerD];
HoldPattern@WignerD[\[Lambda]_,{\[Mu]2_,\[Mu]1_}][{\[Alpha]:Except[_List],\[Beta]:Except[_List],\[Gamma]:Except[_List]}]/;IntegerQ[2\[Lambda]]&&IntegerQ[2\[Mu]2]&&IntegerQ[2\[Mu]1]:=TrigExpand@WignerD[{\[Lambda],-\[Mu]2,-\[Mu]1},\[Alpha],\[Beta],\[Gamma]];
Protect[WignerD]
)];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[WignerD,Infinity,(
Unprotect[WignerD];
HoldPattern@WignerD[\[Lambda]_][{\[Alpha]:Except[_List],\[Beta]:Except[_List],\[Gamma]:Except[_List]}]:=Table[WignerD[\[Lambda],{\[Mu]2,\[Mu]1}][{\[Alpha],\[Beta],\[Gamma]}],{\[Mu]2,+\[Lambda],-\[Lambda],-1},{\[Mu]1,+\[Lambda],-\[Lambda],-1}]/;IntegerQ[2\[Lambda]];
Protect[WignerD]
)];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[WignerD,Infinity,(
Unprotect[WignerD];
HoldPattern@WignerD[\[Lambda]_,{\[Mu]2_}][\[CapitalOmega]_]:=Table[WignerD[\[Lambda],{\[Mu]2,\[Mu]1}][\[CapitalOmega]],{\[Mu]1,+\[Lambda],-\[Lambda],-1}];
Protect[WignerD]
)];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[WignerD,Infinity,(
Unprotect[WignerD];
HoldPattern@WignerD[\[Lambda]_,{{\[Mu]1_}}][\[CapitalOmega]_]:=Table[WignerD[\[Lambda],{\[Mu]2,\[Mu]1}][\[CapitalOmega]],{\[Mu]2,+\[Lambda],-\[Lambda],-1}];
Protect[WignerD]
)];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[WignerD,Infinity,(
Unprotect[WignerD];
HoldPattern@WignerD[J_][rot:{{Except[_List],Except[_List],Except[_List]}}]:=WignerD[J][First@rot];
Protect[WignerD]
)];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[WignerD,Infinity,(
Unprotect[WignerD];
HoldPattern@WignerD[J_][{rots:{Except[_List],Except[_List],Except[_List]}..,rot1:{Except[_List],Except[_List],Except[_List]}}]:=WignerD[J][{rots}] . WignerD[J][rot1];
Protect[WignerD]
)];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[WignerD,Infinity,(
Unprotect[WignerD];
HoldPattern@WignerD[J_,{m2_,m1_}][rot:{{Except[_List],Except[_List],Except[_List]}}]:=WignerD[J,{m2,m1}][First@rot];
Protect[WignerD]
)];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[WignerD,Infinity,(
Unprotect[WignerD];
HoldPattern@WignerD[J_,{m2_,m1_}][{rots:{Except[_List],Except[_List],Except[_List]}..,rot1:{Except[_List],Except[_List],Except[_List]}}]:=Sum[WignerD[J,{m2,m21}][{rots}]*WignerD[J,{m21,m1}][rot1],{m21,-J,+J}];
Protect[WignerD]
)];


(* ::Input::Initialization:: *)
Unprotect[WignerD];WignerD::mod="The built-in function WignerD has been given extra functionality in SpinDynamica. Execute ?WignerD for more information.";
Protect[WignerD];


(* ::Input::Initialization:: *)
Wignerd[\[Lambda]_,{\[Mu]2_,\[Mu]1_}][\[Beta]_]:=0/;IntegerQ[2\[Lambda]]&&IntegerQ[2\[Mu]2]&&IntegerQ[2\[Mu]1]&&((Abs[2\[Mu]2]>2\[Lambda])||(Abs[2\[Mu]1]>2\[Lambda]));


(* ::Input::Initialization:: *)
Wignerd[\[Lambda]_,{\[Mu]2_,\[Mu]1_}][\[Beta]_]/;IntegerQ[2\[Lambda]]&&IntegerQ[2\[Mu]2]&&IntegerQ[2\[Mu]1]:=TrigExpand@WignerD[{\[Lambda],-\[Mu]2,-\[Mu]1},0,\[Beta],0];


(* ::Input::Initialization:: *)
HoldPattern@Wignerd[\[Lambda]_][\[Beta]:Except[_List]]:=Table[Wignerd[\[Lambda],{\[Mu]2,\[Mu]1}][\[Beta]],{\[Mu]2,+\[Lambda],-\[Lambda],-1},{\[Mu]1,+\[Lambda],-\[Lambda],-1}]/;IntegerQ[2\[Lambda]];


(* ::Input::Initialization:: *)
Wignerd[J_,{m2_?NumericQ}][\[Beta]_]/; (-J<=m2<=J):= 
Table[Wignerd[J,{m2,m1}][\[Beta]],{m1,+J,-J,-1}];


(* ::Input::Initialization:: *)
Wignerd[J_,{{m1_?NumericQ}}][\[Beta]_]/; (-J<=m1<=J):= 
Table[Wignerd[J,{m2,m1}][\[Beta]],{m2,+J,-J,-1}];


(* ::Input::Initialization:: *)
TensorElement[\[Lambda]_, \[Mu]_][tensor_List]:=tensor[[ \[Lambda]+1-\[Mu]]] /;( Dimensions[tensor]=={2\[Lambda]+1})&&(-\[Lambda]<=\[Mu]<=\[Lambda]);


(* ::Input::Initialization:: *)
End[];
EndPackage[];
