(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage[ "Graphics`Ovaloid`",	
	{	"Global`",
		"SpinDynamica`",
		"Tensors`IST`",
		"Tensors`CG`",
		"General`Miscellaneous`"
	}	
];


(* ::Input::Initialization:: *)
Ovaloid::usage="\!\(\*
StyleBox[\"Ovaloid\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"[\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"r\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\",\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"tensor\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\",\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"opts\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"]\",\nFontSlant->\"Italic\"]\) generates a \!\(\*
StyleBox[\"Graphics3D\",\nFontSlant->\"Italic\"]\) object representing a rank-2 spherical tensor, centred  at position \!\(\*
StyleBox[\"r\",\nFontSlant->\"Italic\"]\). The \!\(\*
StyleBox[\"tensor\",\nFontSlant->\"Italic\"]\) may be a \!\(\*
StyleBox[\"SphericalTensor\",\nFontSlant->\"Italic\"]\) object of rank 2, or a 3\[Times]3 real matrix. In the case of a 3\[Times]3 real matrix, the traceless symmetric part of the matrix is extracted in order to define the rank-2 spherical tensor. If the vector \!\(\*
StyleBox[\"r\",\nFontSlant->\"Italic\"]\) is omitted, the value \!\(\*
StyleBox[\"r\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\" \",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"=\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\" \",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"{\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"0\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\",\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"0\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\",\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"0\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"}\",\nFontSlant->\"Italic\"]\) is assumed. The options may include rules for \!\(\*
StyleBox[\"OvaloidScale\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\",\",\nFontSlant->\"Italic\"]\) \!\(\*
StyleBox[\"OvaloidColors\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\",\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\" \",\nFontSlant->\"Italic\"]\)and\!\(\*
StyleBox[\" \",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"OvaloidIsotropicComponent\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\".\",\nFontSlant->\"Italic\"]\) The option \!\(\*
StyleBox[\"OvaloidIsotropicComponent\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"\[Rule]\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"iso\",\nFontSlant->\"Italic\"]\), incorporates an isotropic component in the graphical depiction of the tensor. See the usage messages for these options. The ovaloid graphical representation is described by Len Mueller in https://doi.org/10.1002/mrc.4793 and used in his program TensorView, https://sites.google.com/ucr.edu/Mueller/home/tensorview
";


(* ::Input::Initialization:: *)
OvaloidScale::usage="\!\(\*
StyleBox[\"OvaloidScale\",\nFontSlant->\"Italic\"]\) defines the ratio between the graphical coordinates and the tensor values in the \!\(\*
StyleBox[\"Ovaloid\",\nFontSlant->\"Italic\"]\) representation of a second-rank spherical tensor.  For example, if the coordinates of a molecule are specified in units of \[CapitalARing], and the tensor is specified in units of ppm, then \!\(\*
StyleBox[\"OvaloidScale\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"->\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"0.1\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\" \",\nFontSlant->\"Italic\"]\)would generate an ovaloid with a tensor value of 10ppm stretching a distance of 1\[CapitalARing] from the centre of the ovaloid. 
";


(* ::Input::Initialization:: *)
OvaloidColors::usage="\!\(\*
StyleBox[\"OvaloidColors\",\nFontSlant->\"Italic\"]\) defines the colouring of the \!\(\*
StyleBox[\"OvaloidGraphics\",\nFontSlant->\"Italic\"]\) representation of a 3\[Times]3 Cartesian matrix. \!\(\*
StyleBox[\"OvaloidColors\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"\[Rule]\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"{\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"poscolor\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\",\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"negcolor\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"}\",\nFontSlant->\"Italic\"]\) uses \!\(\*
StyleBox[\"poscolor\",\nFontSlant->\"Italic\"]\) for the colour of the positive lobes and \!\(\*
StyleBox[\"negcolor\",\nFontSlant->\"Italic\"]\) for the colour of the negative lobes. \!\(\*
StyleBox[\"OvaloidColors\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"\[Rule]\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"color\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\" \",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"uses\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\" \",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"color\",\nFontSlant->\"Italic\"]\) for both lobes.";


(* ::Input::Initialization:: *)
OvaloidIsotropicComponent::usage="\!\(\*
StyleBox[\"OvaloidIsotropicComponent\",\nFontSlant->\"Italic\"]\) is an option for \!\(\*
StyleBox[\"Ovaloid\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\".\",\nFontSlant->\"Italic\"]\) The default is \!\(\*
StyleBox[\"OvaloidIsotropicComponent\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"\[Rule]\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"False\",\nFontSlant->\"Italic\"]\), in which case no isotropic component is included in the graphical representation. If \!\(\*
StyleBox[\"OvaloidIsotropicComponent\",\nFontSlant->\"Italic\"]\) equals a number, that number is added to the second-rank tensor when calculating the graphical representation. If \!\(\*
StyleBox[\"OvaloidIsotropicComponent\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"\[Rule]\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"Automatic\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\",\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\" \",\nFontSlant->\"Italic\"]\)and the second-rank tensor is specified by a 3\[Times]3 Cartesian matrix, the isotropic component of the matrix is used.";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
Options[Ovaloid]={
OvaloidScale->1,
OvaloidColors->{Directive[Opacity[0.5],Orange],Directive[Opacity[0.5],Blue]},
Mesh->False,
OvaloidIsotropicComponent->False
};


(* ::Input::Initialization:: *)
Ovaloid[tensor_,opts___Rule]:=Ovaloid[{0,0,0},tensor,opts];


(* ::Input::Initialization:: *)
Ovaloid[r_,tensor_,opts___Rule]/;!MatchQ[r,{_?NumericQ,_?NumericQ,_?NumericQ}]:=(Message[Ovaloid::badr];$Failed);


(* ::Input::Initialization:: *)
Ovaloid[r_,tensor_,opts___Rule]/;!MatchQ[tensor,_SphericalTensor|{{_?NumericQ,_?NumericQ,_?NumericQ},{_?NumericQ,_?NumericQ,_?NumericQ},{_?NumericQ,_?NumericQ,_?NumericQ}}]:=
(Message[Ovaloid::badtensor];$Failed);


(* ::Input::Initialization:: *)
Ovaloid[r_,tensor_SphericalTensor,opts___Rule]/;!MatchQ[tensor,SphericalTensor[2,___]]:=
(Message[Ovaloid::badrank];$Failed);


(* ::Input::Initialization:: *)
Ovaloid[r_,mat_?MatrixQ,opts___Rule]:=
Module[{oic,iso},(
oic=OvaloidIsotropicComponent/.{opts}/.Options[Ovaloid];
iso=Switch[oic,Automatic|True,Plus@@Diagonal[mat]/3,_?NumericQ,oic,_,0];
Ovaloid[r,CartesianToSpherical[2,mat],
Sequence@@SimplifyRules[{OvaloidIsotropicComponent->iso,opts}]]
)];


(* ::Input::Initialization:: *)
Ovaloid[r_,tensor_SphericalTensor,opts___Rule]:=
Module[{oic},(
Ovaloid[r,tensor,Sequence@@SimplifyRules[{OvaloidIsotropicComponent->0,opts}]]
)/;(
oic=OvaloidIsotropicComponent/.{opts}/.Options[Ovaloid];
!MatchQ[oic,_?NumericQ]
)];


(* ::Input::Initialization:: *)
Ovaloid[r_,\[Sigma]2_SphericalTensor,opts___Rule]:=
Module[{\[Sigma]iso,radius,scale,poscolor,negcolor,colorfunc,iso},(
scale=OvaloidScale/.{opts}/.Options[Ovaloid];
{poscolor,negcolor}=If[MatchQ[#],Except[_List],{#,#},#]&@(OvaloidColors/.{opts}/.Options[Ovaloid]);
\[Sigma]iso=OvaloidIsotropicComponent/.{opts}/.Options[Ovaloid];
radius[\[Theta]_,\[Phi]_]=
scale*(
\[Sigma]iso+
Sum[\[Sigma]2[m1]WignerD[2,{m1,m2}][{\[Phi],\[Theta],0}] CG[{2,m2},{1,0},{1,0}],{m1,-2,2},{m2,-2,2}])//ExpToTrig//Simplify;
colorfunc=Function[{\[Theta],\[Phi]},
Evaluate@If[Chop[radius[\[Theta],\[Phi]]]>0,poscolor,negcolor]];
Graphics3D[
Translate[
First@SphericalPlot3D[
Evaluate[radius[\[Theta],\[Phi]]],{\[Theta],0,\[Pi]},{\[Phi],0,2\[Pi]},
Evaluate[Sequence@@FilterRules[
Join[{opts},
{ColorFunction->(colorfunc[#4,#5]&),
ColorFunctionScaling->False},
Options[Ovaloid]
],
Options[SphericalPlot3D]
]]
],
r
],
Evaluate[Sequence@@FilterRules[Join[{opts},Options[Ovaloid]],Options[Graphics3D]]]
]
)];


(* ::Input::Initialization:: *)
Ovaloid::badr="The centre of the ovaloid must be specified by a 3-vector.";


Ovaloid::badtensor="The tensor argument of Ovaloid must be a SphericalTensor of rank 2, or a 3\[Times]3 Cartesian matrix.";


(* ::Input::Initialization:: *)
Ovaloid::badrank="The rank of the SphericalTensor must be 2";


(* ::Input::Initialization:: *)
End[];


(* ::Input::Initialization:: *)
EndPackage[];
