(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["Simulations`Optimization`",
{"Global`",
"SpinDynamica`",
"General`UserLevel`",
"QM`Hilbert`",
"QM`SpinOperators`",
"QM`Liouville`",
"SD`Generators`",
"SD`Approximations`",
"SD`Propagation`",
"Events`Events`",
"Events`PulseSequence`",
"Interactions`Interactions`",
"Interactions`Hamiltonians`",
"Interactions`Relaxation`",
"Simulations`Polarization`",
"Signals`Signal`",
"Ensemble`EnsembleAverage`",
"General`Matrices`",
"General`Miscellaneous`",
"Rotations`Wigner`",
"Units`",
"General`PhysicalConstants`",
"Simulations`Simulations`"
}];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude::usage="MaximizeTransformationAmplitude[\[Rho]ini\[Rule]obs,events,{{p1,p1ini},{p2,p2ini}..}, opts] numerically optimizes a TransformationAmplitude quantity with respect to parameters {p1,p2..}, starting from initial parameter values {p1ini,p2ini..}. 
The option rules opts may include BackgroundGenerator and any of the other usual option specifications for TransformationAmplitude. The values specified in opts may depend on the parameters {p1,p2..}.\nThe option rules opts may include the directive ConstrainPositive\[Rule]True which constrains all parameters {p1,p2..} to positive values. The syntax ConstrainPositive\[Rule]{p1,p2..} may be used to constrain only a subset of parameters to positive values. This is frequently required for pulse sequence delays, etc., which cannot take negative values. 
More general constraints may be implemented by using MaximizeTransformationAmplitude[\[Rho]ini\[Rule]obs,events,{{p1,p1ini,{p1min,p1max}}..}, opts] subjects the parameter p1 to the constraint p1min\[NonBreakingSpace]\[LessEqual]\[NonBreakingSpace]p1\[NonBreakingSpace]\[LessEqual]\[NonBreakingSpace]p1max. If the maximum value p1max is omitted, there is no upper constraint. Any of the parameters {p1,p2..} may be constrained in this way.  
Constrained optimization is often computationally more intensive than unconstrained optimization.
MaximizeTransformationAmplitude deploys the Mathematica routine FindMinimum to find a local minimum of the negative transformation amplitude, starting from a specified point. The rules specified in opts may include specifications for FindMinimum, including a value for the Method option (see the documentation for FindMinimum).\nThe output of MaximizeTransformationAmplitude has the form {maxval,rules} where maxval is the optimized value of the TransformationAmplitude and rules specify the values of the optimized parameters. ";


(* ::Input::Initialization:: *)
ConstrainPositive::usage="ConstrainPositive is an option for MaximizeTransformationAmplitude. If ConstrainPositive\[Rule]True or ConstrainPositive\[Rule]All, all variable parameters of  MaximizeTransformationAmplitude are constrained to positive values. This is frequently required for pulse sequence delays, etc., which cannot take negative values. The syntax ConstrainPositive\[Rule]{p1,p2..} may be used to constrain only a subset of parameters to positive values.";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
Options[MaximizeTransformationAmplitude]={Method->Automatic,ConstrainPositive->Automatic};


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[\[Rho]ini_->obs_List,more___]:=
(MaximizeTransformationAmplitude::multobs;$Failed);


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,events_,
{v:Except[_List],vini:Except[_List]},more___
]:=MaximizeTransformationAmplitude[
\[Rho]ini->obs,events,
{{v,vini}},more
];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,events_,
{v:Except[_List],vini:Except[_List],vconstr_},more___
]:=MaximizeTransformationAmplitude[
\[Rho]ini->obs,events,
{{v,vini,vconstr}},more
];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,events_,vars_List,more:Except[(_Rule|_RuleDelayed)]...,
opts___Rule
]:=Module[{constrpos},(
MaximizeTransformationAmplitude[
\[Rho]ini->obs,events,vars,more,
SimplifyRules[ConstrainPositive->All,opts]
]
)/;(
constrpos=ConstrainPositive/.{opts}/.Options[MaximizeTransformationAmplitude];
MatchQ[constrpos,True]
)];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,events_,varspecs:{{Except[_List],Except[_List]}..},more:Except[(_Rule|_RuleDelayed)]...,
opts___Rule
]:=Module[{constrpos,vars,varinivals},(
{vars,varinivals}=Transpose[varspecs];
MaximizeTransformationAmplitude[
\[Rho]ini->obs,events,varspecs,more,
SimplifyRules[ConstrainPositive->vars,opts]
]
)/;(
constrpos=ConstrainPositive/.{opts}/.Options[MaximizeTransformationAmplitude];
MatchQ[constrpos,All]
)];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,events_,varspecs:{{Except[_List],Except[_List]}..},more:Except[(_Rule|_RuleDelayed)]...,opts___Rule]:=
Module[{constrpos},(
MaximizeTransformationAmplitude[
\[Rho]ini->obs,events,varspecs,more,
SimplifyRules[ConstrainPositive->{constrpos},opts]
]
)/;(
constrpos=ConstrainPositive/.{opts}/.Options[MaximizeTransformationAmplitude];
!MatchQ[constrpos,_List|All|False|True|Automatic]
)];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,events_,varspecs:{{Except[_List],Except[_List]}..},more:Except[(_Rule|_RuleDelayed)]...,
opts___Rule
]:=Module[{constrpos,constrposvars},(
constrposvars=constrpos;
If[
!SubsetQ[First/@varspecs,constrposvars],
(Message[
MaximizeTransformationAmplitude::badconstrvar,constrposvars];
$Failed
),
MaximizeTransformationAmplitude[
\[Rho]ini->obs,events,
varspecs/.(({#1,inival_}:>{#1,inival,{0}})&/@constrposvars),
more,
SimplifyRules[ConstrainPositive->Automatic,opts]
]
])/;(
constrpos=ConstrainPositive/.{opts}/.Options[MaximizeTransformationAmplitude];
MatchQ[constrpos,{_Symbol..}]
)];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,events_,varspecs:{___,{Except[_List],Except[_List],_},___},more:Except[(_Rule|_RuleDelayed)]...,
opts___Rule
]:=Module[{constrpos,constrposvars},(
Message[MaximizeTransformationAmplitude::constrposconf,constrpos];
MaximizeTransformationAmplitude[
\[Rho]ini->obs,events,
varspecs,
more,
SimplifyRules[ConstrainPositive->Automatic,opts]
]
)/;(
constrpos=ConstrainPositive/.{opts}/.Options[MaximizeTransformationAmplitude];
!MatchQ[constrpos,Automatic]
)];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,events_,varspecs:{{Except[_List],Except[_List]}..},
more:Except[(_Rule|_RuleDelayed)]...,
opts___Rule
]:=Module[{constrpos,constrposvars},(
constrposvars=constrpos;
MaximizeTransformationAmplitude[
\[Rho]ini->obs,events,
varspecs,more,
SimplifyRules[ConstrainPositive->False,opts]
]
)/;(
constrpos=ConstrainPositive/.{opts}/.Options[MaximizeTransformationAmplitude];
MatchQ[constrpos,Automatic]
)];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,events_,
{va___,{vb:Except[_List],vbini:Except[_List],vbmin:Except[_List]},vc___},more___
]:=MaximizeTransformationAmplitude[
\[Rho]ini->obs,events,
{va,{vb,vbini,{vbmin}},vc},more
];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,events_,
{va___,{vb:Except[_List],vbini:Except[_List],{vbmin:Except[_List]}},vc___},more___
]:=MaximizeTransformationAmplitude[
\[Rho]ini->obs,events,
{va,{vb,vbini,{vbmin,Infinity}},vc},more
];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,events_,
{va___,{vb:Except[_List],vbini:Except[_List]},vc___,vd:{Except[_List],Except[_List],{Except[_List],Except[_List]}},ve___},more___
]:=MaximizeTransformationAmplitude[
\[Rho]ini->obs,events,
{va,{vb,vbini,{-Infinity,Infinity}},vc,vd,ve},more
];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,events_,
{va___,vb:{Except[_List],Except[_List],{Except[_List],Except[_List]}},vc___,{vd:Except[_List],vdini:Except[_List]},ve___},more___
]:=MaximizeTransformationAmplitude[
\[Rho]ini->obs,events,
{va,vb,vc,{vd,vdini,{-Infinity,Infinity}},ve},more
];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,
events_,
varspecs:{{_,_}..},
opts:(_Rule|_RuleDelayed)...
]:=
Module[{negta,minval,varrules,vars,varinivals,nvar,method,constrpos},(
{vars,varinivals}=Transpose[varspecs];
nvar=Length[vars];
negta[Repeated[_?NumericQ,{nvar}]]:=
-TransformationAmplitude[\[Rho]ini->obs,
events,
Evaluate[Sequence@@FilterRules[{opts},Options[TransformationAmplitude]]]
];
Message[MaximizeTransformationAmplitude::unconstr];
method=
Method/.{opts}/.Options[MaximizeTransformationAmplitude]/.{Automatic->"InteriorPoint"};
If[!MatchQ[method,Automatic],Message[MaximizeTransformationAmplitude::meth,method]];
Check[
({minval,varrules}=
FindMinimum[
negta[Sequence@@vars],
varspecs,
Evaluate[Sequence@@FilterRules [
Join[
{Method->method,opts},
Options[MaximizeTransformationAmplitude]
],
Options[FindMinimum]
]
]
];
{-minval,varrules}),
(Message[MaximizeTransformationAmplitude::fail];
$Failed),
{Event::negdur,Delay::negdur,Pulse::inval\[Beta],Pulse::inval\[Phi],Pulse::neg\[Tau],ShapedPulse::invaldur,FindMinimum::nrnum}
]
)/;(
constrpos=ConstrainPositive/.{opts}/.Options[MaximizeTransformationAmplitude];
MatchQ[constrpos,False]
)];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude[
\[Rho]ini_->obs_,
events_,
varspecs:{{_,_,{_,_}}..},
opts:(_Rule|_RuleDelayed)...
]:=
Module[{negta,minval,varrules,vars,varinivals,nvar,method,varbounds,varminvals,varmaxvals,constraints},(
{vars,varinivals,varbounds}=Transpose[varspecs];
{varminvals,varmaxvals}=Transpose[varbounds];
constraints=And@@MapThread[(#1<=#2<=#3)&,{varminvals,vars,varmaxvals}];
Message[MaximizeTransformationAmplitude::constr,constraints];nvar=Length[vars];
negta[vars:Repeated[_?NumericQ,{nvar}]]:=
Module[{varvals,reflvarvals},(
varvals={vars};
reflvarvals=MapThread[
Which[
#1>#2,#1+Abs[#2-#1],
#2>#3,#3-Abs[#2-#3],
True,#2]&,
{varminvals,varvals,varmaxvals}
];
-TransformationAmplitude[\[Rho]ini->obs,
events,
Evaluate[Sequence@@FilterRules[{opts},Options[TransformationAmplitude]]]
]/.MapThread[(#1->#2)&,{{vars},reflvarvals}]
)];
method=
Method/.{opts}/.Options[MaximizeTransformationAmplitude];
If[!MatchQ[method,Automatic],Message[MaximizeTransformationAmplitude::meth,method]];
Check[
({minval,varrules}=
FindMinimum[
{negta[Sequence@@vars],constraints},
Transpose[{vars,varinivals}],
Evaluate[Sequence@@FilterRules[
Join[
{Method->method,opts},
Options[MaximizeTransformationAmplitude]
],
Options[FindMinimum]
]
]
];
{-minval,varrules}),
(Message[MaximizeTransformationAmplitude::fail];
$Failed),
{Event::negdur,Delay::negdur,Pulse::inval\[Beta],Pulse::inval\[Phi],Pulse::neg\[Tau],ShapedPulse::invaldur,FindMinimum::nrnum}
]
)];


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude::fail="An event duration, or pulse flip angle, has transgressed into an unphysical region, causing MaximizeTransformationAmplitude to fail. Try again with a different starting point, or incorporate constraints on the parameters (see usage message for MaximizeTransformationAmplitude).";


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude::multobs="Only a single target observable may be specified.";


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude::constr="Deploying FindMinimum with constraints `1`.";


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude::unconstr="Deploying FindMinimum without constraints.";


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude::meth="Executing FindMinimum using Method \[Rule] \"`1`\". See the usage message for FindMinimum for other possible values of Method. ";


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude::constrposconf="Explicit constraints take precedence. The directive ConstrainPositive\[Rule]`1` has been ignored.";


(* ::Input::Initialization:: *)
MaximizeTransformationAmplitude::badconstrvar="One or more of the constrained variables `1` are inappropriate.";


(* ::Input::Initialization:: *)
End[];
EndPackage[];
