(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["Simulations`Polarization`",
{"Global`",
"SpinDynamica`",
"General`UserLevel`",
"QM`Hilbert`",
"QM`SpinOperators`",
"QM`Liouville`"
}];


(* ::Input::Initialization:: *)
PolarizationLevelOperator::usage=
"PolarizationLevelOperator is an operator for the polarization level of the spin system. For example OperatorAmplitude[\[Rho]\[Rule]PolarizationLevelOperator[{1,2},\"z\"]] extracts the mean polarization level of spins 1 and 2 along the z-axis, for the density operator \[Rho].
PolarizationLevelOperator[\"z\"] is the operator for the mean level of polarization along the z-axis. 
PolarizationLevelOperator[{1,2},\"z\"] is the operator for the the mean level of polarization of spins 1 and 2 along the z-axis. 
The general syntax is PolarizationLevelOperator[{j,k...},axis] where {j,k..} is the set of spins to be analyzed and axis defines the direction of the polarization. 
PolarizationLevelOperator may be used as an observable in simulation routines (Trajectory, TransformationAmplitude, etc.) in order to simulate the polarization level of the spin system. 
The operator PolarizationLevelOperator is distinct from the \"polarization operator\" used by Ernst and co-workers, which refers to the projection operator onto the Zeeman eigenstates of a spin-1/2, and whose functionality is covered in SpinDynamica by the syntax opI[j,\"\[Alpha]\"] and opI[j,\"\[Beta]\"].
";


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator::usage=
"SingletPolarizationLevelOperator is an operator for the polarization level of the spin system. For example OperatorAmplitude[\[Rho]\[Rule]SingletPolarizationLevelOperator[{1,2}]] extracts the mean singlet polarization level of spins 1 and 2, for the density operator \[Rho].
SingletPolarizationLevelOperator[{{j1,k1},{j2,k2}..}] is the operator for the mean level of singlet polarization for the specified spin pairs.
SingletPolarizationLevelOperator may be used as an observable in simulation routines (Trajectory, TransformationAmplitude, etc.) in order to simulate the singlet polarization level of the spin system. 
";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
PolarizationLevelOperator[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
PolarizationLevelOperator[args___]:=(Message[SpinSystem::notready];Abort[])/;TrueQ[(SpinSystem/.Options[SpinSystem])==Undefined];


(* ::Input::Initialization:: *)
PolarizationLevelOperator[]:=PolarizationLevelOperator[All];


(* ::Input::Initialization:: *)
PolarizationLevelOperator[args__]/;!MatrixQ@Last[{args}]:=PolarizationLevelOperator[args,SpinSystem[]];


(* ::Input::Initialization:: *)
PolarizationLevelOperator[j:Except[_List],spinsys_?MatrixQ]/;ValidSpinQ[j,spinsys]:=PolarizationLevelOperator[j,"z",spinsys];


(* ::Input::Initialization:: *)
PolarizationLevelOperator[All,spinsys_?MatrixQ]:=PolarizationLevelOperator[First/@spinsys,spinsys];


(* ::Input::Initialization:: *)
PolarizationLevelOperator[spins_List,spinsys_?MatrixQ]/;And@@(ValidSpinQ[#,spinsys]&/@spins):=PolarizationLevelOperator[spins,"z",spinsys];


(* ::Input::Initialization:: *)
PolarizationLevelOperator[axis_?ValidAxisSpecificationQ,spinsys_?MatrixQ]:=PolarizationLevelOperator[All,axis,spinsys];


(* ::Input::Initialization:: *)
PolarizationLevelOperator[All,axis_,spinsys_?MatrixQ]:=PolarizationLevelOperator[First/@spinsys,axis,spinsys];


(* ::Input::Initialization:: *)
PolarizationLevelOperator[spins_,axis_,spinsys_?MatrixQ]/;!ValidAxisSpecificationQ[axis]:=
(Message[PolarizationLevelOperator::badaxis];$Failed);


(* ::Input::Initialization:: *)
PolarizationLevelOperator[spins_List]/;!DuplicateFreeQ[spins]:=(Message[PolarizationLevelOperator::dupspins,spins];$Failed);


(* ::Input::Initialization:: *)
PolarizationLevelOperator[spins_List,axis_,spinsys_]:=
If[FreeQ[#,$Failed],
PolarizationLevelOperator[axis,spins,spinsys]=Simplify[#],
$Failed
]&@
Apply[Plus,PolarizationLevelOperator[#,axis,spinsys]&/@spins];


(* ::Input::Initialization:: *)
PolarizationLevelOperator[j:Except[_List],axis_,spinsys_]/;!ValidSpinQ[j,spinsys]:=(Message[SpinSystem::invspin,j];$Failed);


(* ::Input::Initialization:: *)
PolarizationLevelOperator[j:Except[_List],axis_?ValidAxisSpecificationQ,spinsys_]:=
(PolarizationLevelOperator[axis,j,spinsys]=
Module[{Ij,dim},(
Ij=SpinQuantumNumber[j,spinsys];
dim=BasisDimension[ZeemanBasis[spinsys]];
Simplify[3/((Ij+1)*dim)*opI[j,axis]]
)]
);


(* ::Input::Initialization:: *)
PolarizationLevelOperator::dupspins="The specified list of spins `1` should not contain duplicates.";


(* ::Input::Initialization:: *)
PolarizationLevelOperator::badaxis="Cannot interpret polarization axis specification.";


(* ::Input::Initialization:: *)
PolarizationLevelOperator::inval\[Rho]="PolarizationLevelOperator has been used with a non-rigorous density operator (trace not equal to 1). Polarization levels are unreliable in this case.";


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator[args___]:=(Message[SpinSystem::notready];Abort[])/;MatchQ[SpinSystem/.Options[SpinSystem],Undefined];


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator[]:=
Module[{spinsys},(
spinsys=SpinSystem[];
If[MatchQ[spinsys,{{_,1/2},{_,1/2}}],SingletPolarizationLevelOperator[First/@spinsys],
(Message[SingletPolarizationLevelOperator::notspinpair];$Failed)
]
)];


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator[args_]:=SingletPolarizationLevelOperator[args,SpinSystem[]];


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator[spinpairs:{{_,_}..},spinsys_]:=
Module[{},(
Message[SingletPolarizationLevelOperator::sharedspins];
$Failed
)/;(
(Length[spinpairs]>1)&&And@@Apply[DisjointQ, Subsets[spinpairs,{2}],{1}]
)
];


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator[spinpairs:{{_,_}..},spinsys_]:=
If[FreeQ[#,$Failed],
SingletPolarizationLevelOperator[spinpairs,spinsys]=#,
$Failed
]&@
Simplify[Plus@@(SingletPolarizationLevelOperator[#,spinsys]&/@spinpairs)];


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator[{j:Except[_List],k:Except[_List]},spinsys_]/;!ValidSpinQ[j,spinsys]:=(Message[SpinSystem::invspin,j];$Failed);


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator[{j:Except[_List],k:Except[_List]},spinsys_]/;!ValidSpinQ[k,spinsys]:=(Message[SpinSystem::invspin,k];$Failed);


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator[{j:Except[_List],k:Except[_List]},spinsys_]/;(SpinQuantumNumber[j,spinsys]!=1/2):=(Message[SingletPolarizationLevelOperator::notspinhf,j];$Failed);


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator[{j:Except[_List],k:Except[_List]},spinsys_]/;(SpinQuantumNumber[k,spinsys]!=1/2):=(Message[SingletPolarizationLevelOperator::notspinhf,k];$Failed);


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator[{j_,j_},spinsys_]:=(Message[SingletPolarizationLevelOperator::invalpair,{j,j}];$Failed);


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator[{j_,k_},spinsys_]:=
SingletPolarizationLevelOperator[{j,k},spinsys]=-(4/BasisDimension[ZeemanBasis[spinsys]])opI[j] . opI[k];


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator::notspinhf="Spin `1` is not spin-1/2.";


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator::invalpair="The spin pair `1` is invalid.";


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator::sharedspins="Spins may not be shared between different pairs.";  


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator::notspinpair="The current SpinSystem[] is not a spin-1/2 pair. The singlet spin pair must be specified explicitly.";


(* ::Input::Initialization:: *)
SingletPolarizationLevelOperator::inval\[Rho]="SingletPolarizationLevelOperator has been used with a non-rigorous density operator (trace not equal to 1). Polarization levels are unreliable in this case.";


(* ::Input::Initialization:: *)
End[];
EndPackage[];



