(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["Events`PulseSequence`",
{"Global`",
"SpinDynamica`",
"General`UserLevel`",
"General`Matrices`",
"General`Miscellaneous`",
"QM`Hilbert`",
"QM`SpinOperators`",
"QM`Liouville`",
"SD`Generators`",
"Events`Events`",
"Rotations`Wigner`",
"Units`",
"General`PhysicalConstants`"}];


(* ::Input::Initialization:: *)
PulseSequence::usage="PulseSequence[spins, {element1, element2..}, options] generates a pulse sequence object which may be used in SpinDynamica calculations. Each element may be a Delay, a Pulse, a ShapedPulse, a CoherenceOrderFiltration instruction, or another PulseSequence. 
The spins argument determines which spins the pulse sequence elements apply to. If spins is omitted, all spins in the current SpinSystem[] are assumed.
The form PulseSequence[spins, \[Tau], {element1, element2..}, options] adjusts the durations of any Delay[Automatic..] elements so as to ensure a total pulse sequence duration \[Tau].  
The options provide values for any of the internal elements, including the Pulse options NutationFrequency, and AmplitudeFactor. These options apply to all of the internal elements, unless those elements themselves have options, which then take precedence. The option PhaseShift specifies a phase shift of all contained pulse sequence elements. 
Expand may be applied to a PulseSequence object, in order to convert it into a list of explicit events.  
";


(* ::Input::Initialization:: *)
PhaseShift::usage="PhaseShift is an option for PulseSequence, Pulse, and ShapedPulse, specifying an additional phase shift of all elements.";


(* ::Input::Initialization:: *)
PulseSequenceQ::usage="PulseSequenceQ[args] returns True if args contains a PulseSequence object or any defined PulseSequence element.
";


(* ::Input::Initialization:: *)
Delay::usage="Delay[\[Tau]] specifies an interval of fixed duration \[Tau] without any radio-frequency fields. 
Delay[\[Tau], evgen] species an interval of fixed duration \[Tau] with an additional evolution generator applied to the spin system. The evgen argument may be a Hamiltonian operator, a relaxation superoperator, or one of the Function, PeriodicFunction or PeriodicGeneratorFunction arguments used to specify a time-dependent evolution generator.
Delay[Automatic] and Delay[Automatic, evgen] define flexible delays which are automatically adjusted so that the enclosing PulseSequence has the specified duration. If the PulseSequence contains several Delay[Automatic..] objects, the syntax PulseSequence[{.. Delay[{Automatic,x1}..]..Delay[{Automatic,x2}..]..}..] adjusts the delays so as to maintain the specified ratio between the x-parameters. For example, PulseSequence[\[Tau],{Delay[{Automatic,1}],Delay[{Automatic,2}]}] generates PulseSequence[\[Tau],{Delay[\[Tau]/3],Delay[2\[Tau]/3]}].
Expand may be applied to a Delay object, in order to convert it into an explicit event.  
";


(* ::Input::Initialization:: *)
Pulse::usage="Pulse[spins,{\[Beta],\[Phi]},options] specifies a rectangular pulse of flip angle \[Beta] and phase \[Phi] applied to spins. The flip angle \[Beta] and phase \[Phi] are both specified in radians. The arguments \"x\", \"y\",\"-x\",\"-y\" may also be used for the phase argument. 
The option NutationFrequency may be used to specify the rf field amplitude, expressed as a nutation frequency. If NutationFrequency and \[Beta] are both specified, the duration of the pulse is adjusted accordingly. 
The option PulseDuration may be used to specify the duration of the pulse in seconds. If PulseDuration and \[Beta] are both specified, the nutation frequency of the pulse is adjusted accordingly. 
If neither NutationFrequency nor PulseDuration are specified, the pulse is assumed to be infinitesimally short. 
The option AmplitudeFactor may be used to specify the rf field amplitude relative to a nominal value. This may be used to simulate the effect of rf inhomogeneity. AmplitudeFactor\[Rule]1 indicates a rf field amplitude equal to the nominal value. If the value of AmplitudeFactor is less than 1, the simulated rf field is weaker than the nominal value (no corresponding adjustment to the pulse duration is made). 
Expand may be applied to a Pulse object, in order to convert it into an explicit event.  
";



(* ::Input::Initialization:: *)
NutationFrequency::usage="NutationFrequency is an optional argument for Pulse and ShapedPulse objects, specifying the rf field amplitude as a nutation frequency in the rotating reference frame.";  


(* ::Input::Initialization:: *)
PulseDuration::usage="PulseDuration is an optional argument for Pulse, specifying the pulse duration.";  


(* ::Input::Initialization:: *)
AmplitudeFactor::usage="AmplitudeFactor is an optional argument for Pulse and ShapedPulse objects, specifying the strength of the radiofrequency field relative to its nominal value. The default is AmplitudeFactor\[Rule]1.";


(* ::Input::Initialization:: *)
ShapedPulse::usage="ShapedPulse[spins,\[Tau]p,{\[Tau],{amplitude,phase,frequency}},options] specifies a continuously shaped radiofrequency pulse of duration \[Tau]p applied to spins spins. The amplitude, phase and frequency arguments are arbitrary functions of \[Tau], with the origin of the local time variable \[Tau] being in the centre of the pulse, by default (for other options, see below). The amplitude argument specifies the nutation frequency for the selected spins as a function of \[Tau]. The phase argument specifies the phase of the radiofrequency field in the rotating frame. The frequency argument specifies the frequency offset of the shaped radiofrequency field. 
If the spins argument is missing, all spins in the current spin system are assumed. 
If the frequency argument is missing, zero frequency offset is assumed. If the phase argument is also missing, zero phase is assumed. 
The syntax ShapedPulse[spins,\[Tau]p,{\[Tau],amplitude},options] assumes an amplitude-modulated rf field as a function of local time variable \[Tau]. For example, ShapedPulse[spins,\[Tau]p,{\[Tau],\[Omega]nutmax Cos[\[Omega]mod t]}] specifies a cosine-modulated pulse with maximum nutation frequency \[Omega]nutmax and modulation frequency \[Omega]mod.
Syntax of the form ShapedPulse[spins,\[Tau]p,{{\[Tau],x}, {amplitude,phase,frequency}},options] indicates that the local time variable \[Tau] has a time origin located at a point which is a fraction x of the pulse duration from the start of the pulse. A value of x=0 indicates a time origin at the beginning of the pulse; a value of x=1 indicates a time origin at the end of the pulse. The default is x=1/2 (time origin at the centre of the pulse).  
The options may contain rules for AmplitudeFactor and PhaseShift. AmplitudeFactor is used to specify the rf field amplitude relative to a nominal value, allowing simulation of the effect of rf inhomogeneity. For example AmplitudeFactor\[Rule]0.9 indicates a rf field amplitude which is 10% less than the nominal value. The PhaseShift\[Rule]\[CapitalPhi] option may be used to impose a constant phase shift \[CapitalPhi] on the pulse shape. Both of these options may be passed down from the enclosing PulseSequence object.
Expand may be applied to a ShapedPulse object, in order to convert it into an explicit event.";


(* ::Input::Initialization:: *)
RepeatPulseSequence::usage="RepeatPulseSequence[pulseseq,n,options] repeats a PulseSequence pulseseq n times. This routine is implemented automatically when Repeat is applied to pulse sequence objects.";


(* ::Input::Initialization:: *)
CoherenceOrderFiltration::usage=
"CoherenceOrderFiltration[{order1, order2...}] implements filtration through a set of coherence orders (all orders in the set {order1, order2...} being allowed, with other orders disallowed). 
CoherenceOrderFiltration[spins,{order1, order2...}] implements filtration through a set of coherence orders of spins (all orders of spins not included in {order1, order2...} are suppressed, while all orders for spins not included in spins are allowed).
CoherenceOrderFiltration[{spins1,{order1, order2...},{spins2,{order3, order4...}..}] filters successively through {order1, order2...} for spins1, orders {order3, order4...} for spins2, etc. 
Examples: After SetSpinSystem[4], CoherenceOrderFiltration[0] or CoherenceOrderFiltration[{0}] suppresses all coherences which are not zero-quantum for all four spins. CoherenceOrderFiltration[{1,2},0] suppresses all coherences which are not zero-quantum for spins {1,2}, but permits all coherences for spins {3,4}. CoherenceOrderFiltration[{{1,2},0},{{3,4},0}] suppresses all terms that are not zero-quantum for both sets of spins {1,2} and {3,4}. 
Expand may be applied to a CoherenceOrderFiltration object, in order to convert it into an explicit event.  
";


(* ::Input::Initialization:: *)
$Chronology="LeftToRight";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
IndicativePulseSequenceElementTypes={PulseSequence,Delay,Pulse,ShapedPulse,CoherenceOrderFiltration,RepeatPulseSequence};


(* ::Input::Initialization:: *)
PulseSequenceElementTypes=Join[IndicativePulseSequenceElementTypes,{}];


(* ::Input::Initialization:: *)
PulseSequenceElementPatterns=Append[Blank/@PulseSequenceElementTypes,_?ValidEventSpecificationQ];


(* ::Input::Initialization:: *)
PulseSequenceElementPattern=Alternatives@@PulseSequenceElementPatterns;


(* ::Input::Initialization:: *)
SetOptions[EventSpecifications,FurtherEventSpecificationPatterns->PulseSequenceElementPatterns];


(* ::Input::Initialization:: *)
SimplifyPulseSequenceElementRules[opts___Rule]:=
Module[{\[CapitalPhi]opts,\[CapitalPhi]tot},(
\[CapitalPhi]opts=Cases[{opts},HoldPattern[PhaseShift->_]];
\[CapitalPhi]tot=If[Length[\[CapitalPhi]opts]>=1,Plus@@(Last/@\[CapitalPhi]opts),0];
SimplifyRules[PhaseShift->\[CapitalPhi]tot,opts]
)];


(* ::Input::Initialization:: *)
FilterPulseSequenceElementOptions[el_?ValidEventSpecificationQ][opts___Rule]:=opts;


(* ::Input::Initialization:: *)
FilterPulseSequenceElementOptions[(type:(Alternatives@@PulseSequenceElementTypes))][opts___Rule]:=
Module[{othertypes,otheroptionpars,badoptionpars},(
othertypes=Complement[PulseSequenceElementTypes,{type}];
otheroptionpars=If[Length[#]==0,{},Union[First/@#]]&@Flatten[Options/@othertypes];
badoptionpars=If[Length[#]==0,otheroptionpars,Complement[otheroptionpars,First/@#]]&@Options[type];
SimplifyRules[Sequence@@FilterRules[{opts},Except[(Alternatives@@badoptionpars)->_]]
]
)
];


(* ::Input::Initialization:: *)
FilterOptionsOnInterpretation[el_?ValidEventSpecificationQ][opts___Rule]:=opts;


(* ::Input::Initialization:: *)
FilterOptionsOnInterpretation[(type:(Alternatives@@PulseSequenceElementTypes))][opts___Rule]:=
Module[{eloptions,optionpars},(
eloptions=Options[type];
optionpars=If[Length[eloptions]==0,{},First/@eloptions];
Sequence@@SimplifyRules[
FilterRules[{opts},Except[(Alternatives@@optionpars)->_]]
]
)];


(* ::Input::Initialization:: *)
PulseSequenceQ[args___]:=!FreeQ[{args},Alternatives@@IndicativePulseSequenceElementTypes];


(* ::Input::Initialization:: *)
UserLevelDependentDefinition[
Duration,Infinity,
Duration[evspecs:{PulseSequenceElementPattern..}]/;!MatchQ[evspecs,_?ValidEventSpecificationQ]:=
Plus@@(Duration/@evspecs)
];


(* ::Input::Initialization:: *)
Options[Delay]={};


(* ::Input::Initialization:: *)
Delay[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
Delay[\[Tau]_,opts___Rule]:=Delay[\[Tau],None,opts];


(* ::Input::Initialization:: *)
Delay[\[Tau]_,evgen:Except[_Rule],opts___Rule]/;!ValidGeneratorQ[evgen]:=(Message[Delay::invalgen];$Failed);


(* ::Input::Initialization:: *)
Delay[\[Tau]_,evgen_,opts___Rule]/;TrueQ[\[Tau]<0]:=(Message[Delay::negdur];$Failed);


(* ::Input::Initialization:: *)
Delay[Automatic,evgen_,opts___Rule]:=Delay[{Automatic,1},evgen,opts];


(* ::Input::Initialization:: *)
Delay[\[Tau]_List,evgen_,opts___Rule]/;!MatchQ[\[Tau],{Automatic,Except[_List]}]:=(Message[Delay::bad\[Tau]];$Failed);


(* ::Input::Initialization:: *)
Delay[{Automatic,x_},evgen_,opts___Rule]/;TrueQ[x<0]:=(Message[Delay::negx];$Failed);


(* ::Input::Initialization:: *)
Delay/:InvolvedSpins[Delay[\[Tau]_,evgen_,dopts___Rule]]:={};


(* ::Input::Initialization:: *)
Delay/:Duration[Delay[\[Tau]_,evgen_,dopts___Rule]]:=\[Tau];


(* ::Input::Initialization:: *)
StandardizeEventSpecification[
Delay[\[Tau]_,evgen_,dopts___Rule],
opts___Rule]/;FreeQ[\[Tau],Automatic]:=
EventSpecifications[
{evgen,\[Tau],FilterOptionsOnInterpretation[Delay][dopts,opts]}
];


(* ::Input::Initialization:: *)
Delay/:Expand[delay_Delay,opts___Rule]:=EventSpecifications[delay,opts][[2,1]];


(* ::Input::Initialization:: *)
Delay::invalgen="The second argument to Delay must be a valid evolution generator.";


(* ::Input::Initialization:: *)
Delay::negdur="Delay may not have a negative duration.";


(* ::Input::Initialization:: *)
Delay::bad\[Tau]="Inappropriate duration argument for Delay.";


(* ::Input::Initialization:: *)
Delay::bad\[Tau]="The fractional timing argument x in the form Delay[{Automatic,x}..] must be zero or positive.";


(* ::Input::Initialization:: *)
Options[Pulse]={NutationFrequency->Automatic,PulseDuration->Automatic,AmplitudeFactor->1,PhaseShift->0};


(* ::Input::Initialization:: *)
Pulse[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
Pulse[angles_List,opts___Rule]:=Pulse[Automatic,angles,opts];


(* ::Input::Initialization:: *)
Pulse[spin:Except[_List|Automatic|All],angles_List,opts___Rule]:=Pulse[{spin},angles,opts];


(* ::Input::Initialization:: *)
Pulse[All,angles_List,opts___Rule]:=Pulse[First/@SpinSystem[],angles, opts];


(* ::Input::Initialization:: *)
Pulse[spins_List,angles_List,opts___Rule]/;!ValidSpinQ[spins,SpinSystem[]]:=(Message[PulseSequence::invalspins,spins];$Failed);


(* ::Input::Initialization:: *)
Pulse[spins_List,{\[Beta]_,\[Phi]_},opts___Rule]/;TrueQ[\[Beta]<0]:=
(Message[Pulse::neg\[Beta]];$Failed)


(* ::Input::Initialization:: *)
Pulse[spins_List,{\[Beta]_,\[Phi]_String},opts___Rule]:=
Pulse[spins,
{\[Beta],
Switch[\[Phi],
"x",0,
"y",\[Pi]/2,
"-x",\[Pi],
"-y",3\[Pi]/2,
_,(Message[Pulse::inval\[Phi]];$Failed)
]},
opts];


(* ::Input::Initialization:: *)
Pulse[spins_List,{\[Beta]_,\[Phi]:Except[_String]},opts___Rule]/;!FreeQ[{opts},HoldPattern[PhaseShift->_]]:=
Module[{\[CapitalPhi]},(
\[CapitalPhi]=PhaseShift/.{opts};
Pulse[spins,{\[Beta],\[Phi]+\[CapitalPhi]},
Sequence@@FilterRules[{opts},Except[PhaseShift]]
]
)];


(* ::Input::Initialization:: *)
Pulse[spins_List,{\[Beta]_,\[Phi]_?NumericQ},opts___Rule]/;(\[Phi]<-\[Pi])||(\[Phi]>\[Pi]):=Pulse[spins,{\[Beta],Mod[\[Phi],2\[Pi],-\[Pi]]},opts];


(* ::Input::Initialization:: *)
Pulse/:InvolvedSpins[Pulse[spins_List,angles_List,opts___Rule]]:=spins;


(* ::Input::Initialization:: *)
Pulse/:InvolvedSpins[Pulse[Automatic,angles_List,opts___Rule]]:=Automatic


(* ::Input::Initialization:: *)
Pulse/:Duration[Pulse[spins:(_List|Automatic),{\[Beta]_,\[Phi]_},popts___Rule],opts___Rule]/;MatchQ[{NutationFrequency,PulseDuration}/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]],{Automatic,Automatic}]:=
Duration@Pulse[spins,{\[Beta],\[Phi]},
SimplifyRules[NutationFrequency->Infinity,popts,opts]
];


(* ::Input::Initialization:: *)
Pulse/:Duration[
Pulse[spins:(_List|Automatic),{\[Beta]_,\[Phi]_},popts___Rule],
opts___Rule]/;MatchQ[{NutationFrequency,PulseDuration}/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]],{Automatic,_?((Chop[#]==0)&)}]:=
Duration@Pulse[spins,{\[Beta],\[Phi]},
SimplifyRules[NutationFrequency->Infinity,popts,opts]
];


(* ::Input::Initialization:: *)
Pulse/:Duration[
Pulse[spins:(_List|Automatic),{\[Beta]_,\[Phi]_},popts___Rule],
opts___Rule]/;MatchQ[{NutationFrequency,PulseDuration}/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]],{Except[Automatic|Infinity],Except[Automatic|_?((Chop[#]==0)&)]}]:=(Message[Pulse::\[Nu]\[Tau]clash];$Failed);


(* ::Input::Initialization:: *)
Pulse/:Duration[
Pulse[spins:(_List|Automatic),{\[Beta]_,\[Phi]_},popts___Rule],
opts___Rule]/;TrueQ[(PulseDuration/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]])<0]:=(Message[Pulse::neg\[Tau]];$Failed);


(* ::Input::Initialization:: *)
Pulse/:Duration[
Pulse[spins:(_List|Automatic),{\[Beta]_,\[Phi]_},popts___Rule],
opts___Rule]/;MatchQ[{NutationFrequency,PulseDuration}/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]],{Except[Automatic|Infinity],Automatic}]:=
Module[{\[Omega]nut,\[Tau]p},(
\[Omega]nut=NutationFrequency/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]];
\[Tau]p=\[Beta]/\[Omega]nut;
Duration@Pulse[spins,{\[Beta],\[Phi]},
SimplifyRules[
PulseDuration->\[Tau]p,
Sequence@@FilterRules[{popts,opts},Except[NutationFrequency->_]]
]
]
)];


(* ::Input::Initialization:: *)
Pulse/:Duration[
Pulse[spins:(_List|Automatic),{\[Beta]_,\[Phi]_},popts___Rule],
opts___Rule]:=
Module[{\[Tau]p},(
\[Tau]p
)/;(
\[Tau]p=PulseDuration/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]];
MatchQ[\[Tau]p,Except[Automatic]]
)];


(* ::Input::Initialization:: *)
Pulse/:Duration[
Pulse[spins:(_List|Automatic),{\[Beta]_,\[Phi]_},popts___Rule],
opts___Rule]/;MatchQ[NutationFrequency/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]],Infinity]:=0;


(* ::Input::Initialization:: *)
Pulse/:StandardizeEventSpecification[
Pulse[Automatic,more___],
opts___Rule]:=
StandardizeEventSpecification[
Pulse[All,more],
opts];


(* ::Input::Initialization:: *)
Pulse/:StandardizeEventSpecification[
Pulse[spins:(_List|Automatic),{\[Beta]_,\[Phi]_},popts___Rule],
opts___Rule]/;MatchQ[{NutationFrequency,PulseDuration}/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]],{Automatic,Automatic}]:=
StandardizeEventSpecification@Pulse[spins,{\[Beta],\[Phi]},
SimplifyRules[NutationFrequency->Infinity,popts,opts]
];


(* ::Input::Initialization:: *)
Pulse/:StandardizeEventSpecification[
Pulse[spins:(_List|Automatic),{\[Beta]_,\[Phi]_},popts___Rule],
opts___Rule]/;MatchQ[{NutationFrequency,PulseDuration}/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]],{Automatic,_?((Chop[#]==0)&)}]:=
StandardizeEventSpecification@Pulse[spins,{\[Beta],\[Phi]},
SimplifyRules[NutationFrequency->Infinity,popts,opts]
];


(* ::Input::Initialization:: *)
Pulse/:StandardizeEventSpecification[
Pulse[spins:(_List|Automatic),{\[Beta]_,\[Phi]_},popts___Rule],
opts___Rule]/;MatchQ[{NutationFrequency,PulseDuration}/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]],{Except[Automatic|Infinity],Except[Automatic|_?((Chop[#]==0)&)]}]:=(Message[Pulse::\[Nu]\[Tau]clash];$Failed);


(* ::Input::Initialization:: *)
Pulse/:StandardizeEventSpecification[
Pulse[spins:(_List|Automatic),{\[Beta]_,\[Phi]_},popts___Rule],
opts___Rule]/;TrueQ[(PulseDuration/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]])<0]:=(Message[Pulse::neg\[Tau]];$Failed);


(* ::Input::Initialization:: *)
Pulse/:StandardizeEventSpecification[
Pulse[spins:(_List|Automatic),{\[Beta]_,\[Phi]_},popts___Rule],
opts___Rule]/;MatchQ[{NutationFrequency,PulseDuration}/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]],{Except[Automatic|Infinity],Automatic}]:=
Module[{\[Omega]nut,\[Tau]p},(
\[Omega]nut=NutationFrequency/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]];
\[Tau]p=\[Beta]/\[Omega]nut;
StandardizeEventSpecification@Pulse[spins,{\[Beta],\[Phi]},
SimplifyRules[
PulseDuration->\[Tau]p,
Sequence@@FilterRules[{popts,opts},Except[NutationFrequency->_]]
]
]
)];


(* ::Input::Initialization:: *)
Pulse/:StandardizeEventSpecification[
Pulse[spins_List,{\[Beta]_,\[Phi]_},popts___Rule],
opts___Rule]/;MatchQ[NutationFrequency/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]],Infinity]:=
Module[{f,\[CapitalPhi]},(
{f,\[CapitalPhi]}={AmplitudeFactor,PhaseShift}/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]];
EventSpecifications[
{RotationSuperoperator[spins,{f*\[Beta],\[Phi]+\[CapitalPhi]}],
FilterOptionsOnInterpretation[Pulse][opts]
}
]
)];


(* ::Input::Initialization:: *)
Pulse/:StandardizeEventSpecification[
Pulse[spins_List,{\[Beta]_,\[Phi]_},popts___Rule],
opts___Rule]/;MatchQ[{NutationFrequency,PulseDuration}/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]],{Automatic,Except[Automatic]}]:=
Module[{\[Omega]nut,\[Tau]p,f,\[CapitalPhi]},(
{f,\[Tau]p,\[CapitalPhi]}={AmplitudeFactor,PulseDuration,PhaseShift}/.{popts,opts}/.Join[Options[Pulse],Options[PulseSequence]];
\[Omega]nut=\[Beta]/\[Tau]p;
EventSpecifications[
{f \[Omega]nut opI[spins,\[Phi]+\[CapitalPhi]],\[Tau]p,
FilterOptionsOnInterpretation[Pulse][opts]
}
]
)];


(* ::Input::Initialization:: *)
Pulse/:Expand[pulse_Pulse,opts___Rule]:=EventSpecifications[pulse,opts][[2,1]];


(* ::Input::Initialization:: *)
Pulse::neg\[Beta]="Flip angle argument for Pulse cannot be negative.";


(* ::Input::Initialization:: *)
Pulse::inval\[Phi]="Invalid phase argument for Pulse.";


(* ::Input::Initialization:: *)
Pulse::\[Nu]\[Tau]clash="The NutationFrequency and the PulseDuration may not be specified simultaneously. One of these options should be omitted.";


(* ::Input::Initialization:: *)
Pulse::neg\[Tau]="The value of PulseDuration may not be negative.";


(* ::Input::Initialization:: *)
SyntaxInformation[ShapedPulse]=
{
"ArgumentsPattern"->{_.,_,{_,_},OptionsPattern[]}
};


(* ::Input::Initialization:: *)
Options[ShapedPulse]={AmplitudeFactor->1,PhaseShift->0};


(* ::Input::Initialization:: *)
ShapedPulse[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
ShapedPulse[Except[_Rule],opts___Rule]:=(Message[ShapedPulse::invalargs];$Failed)


(* ::Input::Initialization:: *)
ShapedPulse[\[Tau]p:Except[_List],funcs_,opts___Rule]:=ShapedPulse[Automatic,\[Tau]p,funcs,opts];


(* ::Input::Initialization:: *)
ShapedPulse[spin:Except[_List|Automatic|All],\[Tau]p_,functions_,opts___Rule]:=ShapedPulse[{spin},\[Tau]p,functions,opts];


(* ::Input::Initialization:: *)
ShapedPulse[All,\[Tau]p_,functions_,opts___Rule]:=ShapedPulse[First/@SpinSystem[],\[Tau]p,functions,opts];


(* ::Input::Initialization:: *)
ShapedPulse[spins_List,\[Tau]p_,functions_,opts___Rule]/;!ValidSpinQ[spins,SpinSystem[]]:=(Message[PulseSequence::invalspins,spins];$Failed);


(* ::Input::Initialization:: *)
ShapedPulse[spins:(_List|Automatic),\[Tau]p_,functions_,opts___Rule]/;TrueQ[\[Tau]p<0]:=(Message[ShapedPulse::invaldur];$Failed);


(* ::Input::Initialization:: *)
ShapedPulse[spins:(_List|Automatic),\[Tau]p_,ampfunc:Except[_List],opts___Rule]:=ShapedPulse[spins,\[Tau]p,{ampfunc},opts];


(* ::Input::Initialization:: *)
ShapedPulse[spins:(_List|Automatic),\[Tau]p_,{ampfunc:Except[_List]},opts___Rule]:=Module[{\[Tau]},ShapedPulse[spins,\[Tau]p,{\[Tau],ampfunc},opts]];


(* ::Input::Initialization:: *)
ShapedPulse[spins:(_List|Automatic),\[Tau]p_,{\[Tau]:Except[_Symbol|_List],funcs__},opts___Rule]:=(Message[ShapedPulse::nonsymbloc\[Tau],\[Tau]];$Failed);


(* ::Input::Initialization:: *)
ShapedPulse[spins:(_List|Automatic),\[Tau]p_,{\[Tau]:Except[_List],funcs__},opts___Rule]:=ShapedPulse[spins,\[Tau]p,{{\[Tau],1/2},funcs},opts];


(* ::Input::Initialization:: *)
ShapedPulse[spins:(_List|Automatic),\[Tau]p_,{{\[Tau]:Except[_Symbol],x_},ampfunc:Except[_List]},opts___Rule]:=
(Message[ShapedPulse::nonsymbloc\[Tau],\[Tau]];$Failed);


(* ::Input::Initialization:: *)
ShapedPulse[spins:(_List|Automatic),\[Tau]p_,{\[Tau]x_List,ampfunc:Except[_List]},opts___Rule]:=ShapedPulse[spins,\[Tau]p,{\[Tau]x,{ampfunc}},opts];


(* ::Input::Initialization:: *)
ShapedPulse[spins:(_List|Automatic),\[Tau]p_,{\[Tau]x_List,{ampfunc_}},opts___Rule]:=ShapedPulse[spins,\[Tau]p,{\[Tau]x,{ampfunc,0}},opts];


(* ::Input::Initialization:: *)
ShapedPulse[spins:(_List|Automatic),\[Tau]p_,{\[Tau]x_List,{ampfunc_,\[Phi]func_}},opts___Rule]:=ShapedPulse[spins,\[Tau]p,{\[Tau]x,{ampfunc,\[Phi]func,0}},opts];


(* ::Input::Initialization:: *)
ShapedPulse/:InvolvedSpins[ShapedPulse[spins_List,\[Tau]p_,functions_,opts___Rule]]:=spins;


(* ::Input::Initialization:: *)
ShapedPulse/:InvolvedSpins[ShapedPulse[Automatic,\[Tau]p_,functions_,opts___Rule]]:=Automatic;


(* ::Input::Initialization:: *)
ShapedPulse/:Duration[ShapedPulse[spins:(_List|Automatic),\[Tau]p_,functions_,opts___Rule]]:=\[Tau]p;


(* ::Input::Initialization:: *)
ShapedPulse/:StandardizeEventSpecification[
HoldPattern@ShapedPulse[Automatic,more___],
opts___Rule]:=
StandardizeEventSpecification[
ShapedPulse[All,more],
opts];


(* ::Input::Initialization:: *)
ShapedPulse/:StandardizeEventSpecification[
ShapedPulse[spins_List,\[Tau]p_,{{\[Tau]_,x_},{ampfunc_,phasefunc_,freqfunc_}},popts___Rule],
opts___Rule]:=
Module[{f,\[CapitalPhi],t},(
{f,\[CapitalPhi]}={AmplitudeFactor,PhaseShift}/.{popts,opts}/.Join[Options[ShapedPulse],Options[PulseSequence]];
EventSpecifications[
{TimeDependentGeneratorFunction[t,{\[Tau],x},
f*ampfunc*opI[spins,\[CapitalPhi]+phasefunc]-freqfunc*opI[spins,"z"]
],
\[Tau]p,
FilterOptionsOnInterpretation[ShapedPulse][opts]
}
]
)];


(* ::Input::Initialization:: *)
ShapedPulse/:Expand[shp_ShapedPulse,opts___Rule]:=EventSpecifications[shp,opts][[2,1]];


(* ::Input::Initialization:: *)
SetOptions[
LocalGeneratorSymbols,
TargetFunctions->Union@Append[
TargetFunctions/.Options[LocalGeneratorSymbols],
_ShapedPulse]
];


(* ::Input::Initialization:: *)
LocalGeneratorSymbols[sp_ShapedPulse,___Rule]:=sp[[3,1,1]];


(* ::Input::Initialization:: *)
ShapedPulse::invalargs="Invalid arguments for ShapedPulse.";


(* ::Input::Initialization:: *)
ShapedPulse::invaldur="Invalid duration for ShapedPulse.";


(* ::Input::Initialization:: *)
ShapedPulse::nonsymbloc\[Tau]="The local time variable must be symbolic and cannot have an assigned value. Here it has the value of `1`.";


(* ::Input::Initialization:: *)
Options[CoherenceOrderFiltration]={};


(* ::Input::Initialization:: *)
CoherenceOrderFiltration[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
CoherenceOrderFiltration[opts___Rule]:=UnitySuperoperator[];


(* ::Input::Initialization:: *)
CoherenceOrderFiltration[spins___,p:Except[_List],opts___Rule]:=CoherenceOrderFiltration[spins,{p},opts];


(* ::Input::Initialization:: *)
CoherenceOrderFiltration[orders:{Except[_List]..},opts___Rule]:=CoherenceOrderFiltration[First/@SpinSystem[],orders,opts];


(* ::Input::Initialization:: *)
CoherenceOrderFiltration[spin:Except[_List],orders:{Except[_List]..},opts___Rule]:=CoherenceOrderFiltration[{spin},orders,opts];


(* ::Input::Initialization:: *)
CoherenceOrderFiltration[spins:{Except[_List]..},orders:{Except[_List]..},opts___Rule]:=CoherenceOrderFiltration[{spins,orders},opts];


(* ::Input::Initialization:: *)
CoherenceOrderFiltration[arg1___,{spins:{Except[_List]..},p:Except[_List]},arg2___,opts___Rule]:=
CoherenceOrderFiltration[arg1,{spins,{p}},arg2,opts];


(* ::Input::Initialization:: *)
CoherenceOrderFiltration[arg1___,{spin:Except[_List],orders:{Except[_List]..}},arg2___,opts___Rule]:=
CoherenceOrderFiltration[arg1,{{spin},orders},arg2,opts];


(* ::Input::Initialization:: *)
CoherenceOrderFiltration[spinsandorders:({{Except[_List]..},{Except[_List]..}}..),opts___Rule]:=
Module[{spins},(
spins=Union@@(First/@{spinsandorders});
If[
And@@(ValidSpinQ[#,SpinSystem[]]&/@spins),
CoherenceOrderFiltration[True,spinsandorders,opts],
(Message[PulseSequence::invalspins,spins];$Failed)
]
)];


(* ::Input::Initialization:: *)
CoherenceOrderFiltration/:
HoldPattern@InvolvedSpins[CoherenceOrderFiltration[args___]]:={};


(* ::Input::Initialization:: *)
CoherenceOrderFiltration/:HoldPattern@Duration[CoherenceOrderFiltration[args___]]:=0;


(* ::Input::Initialization:: *)
StandardizeEventSpecification[
HoldPattern@CoherenceOrderFiltration[
True,spinsandorders:({{Except[_List]..},{Except[_List]..}}..),cofopts___Rule],
opts___Rule]:=
EventSpecifications[
{CoherenceOrderFiltrationSuperoperator[spinsandorders,cofopts],
FilterOptionsOnInterpretation[CoherenceOrderFiltration][cofopts,opts]
}
];


(* ::Input::Initialization:: *)
CoherenceOrderFiltration/:Expand[cof_CoherenceOrderFiltration,opts___Rule]:=EventSpecifications[cof,opts][[2,1]];


(* ::Input::Initialization:: *)
PulseSequence::invalspin="The first argument of CoherenceOrderFiltration must be a list of valid spins.";


(* ::Input::Initialization:: *)
Options[RepeatPulseSequence]=
SimplifyRules[
Join@@(Options/@
Complement[PulseSequenceElementTypes,{RepeatPulseSequence}])
]; 


(* ::Input::Initialization:: *)
RepeatPulseSequence[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
Repeat[arg_,n_,repopts___Rule]/;PulseSequenceQ[arg]:=RepeatPulseSequence[arg,n,repopts];


(* ::Input::Initialization:: *)
DownValues[Repeat]=RotateRight[DownValues[Repeat],1];


(* ::Input::Initialization:: *)
RepeatPulseSequence[el:Except[_PulseSequence],n_,opts___Rule]/;PulseSequenceQ[el]:=RepeatPulseSequence[PulseSequence[el,opts],n,opts];


(* ::Input::Initialization:: *)
RepeatPulseSequence[HoldPattern@PulseSequence[st_,spins_,dur_,els__,pseqopts___Rule],n_,
repopts__Rule
]:=RepeatPulseSequence[
PulseSequence[False,spins,Automatic,els,
FilterPulseSequenceElementOptions[PulseSequence][pseqopts,repopts]
],
n
]; 


(* ::Input::Initialization:: *)
RepeatPulseSequence/:
InvolvedSpins[
RepeatPulseSequence[pseq:HoldPattern@PulseSequence[args___,pseqopts___Rule],n_,
repopts___Rule
]
]:=InvolvedSpins[pseq];


(* ::Input::Initialization:: *)
RepeatPulseSequence/:
Duration[
RepeatPulseSequence[pseq:HoldPattern@PulseSequence[args___,pseqopts___Rule],n_,
repopts___Rule
]
]:=n*Duration[pseq];


(* ::Input::Initialization:: *)
RepeatPulseSequence/:StandardizeEventSpecification[
RepeatPulseSequence[HoldPattern@PulseSequence[args___,pseqopts___Rule],n_,
repopts___Rule
],
opts___Rule]:=
EventSpecifications[
{RepeatPulseSequence[
EventSpecifications[
PulseSequence[args,
FilterOptionsOnInterpretation[RepeatPulseSequence][pseqopts,repopts,opts]
]
],
n,
FilterOptionsOnInterpretation[RepeatPulseSequence][pseqopts,repopts,opts]
]
}
]; 


(* ::Input::Initialization:: *)
RepeatPulseSequence/:StandardizeEventSpecification[
RepeatPulseSequence[evspecs_EventSpecifications,n_,repopts___Rule],
opts___Rule]:=
EventSpecifications[
{Repeat[evspecs,n,
Sequence@@FilterRules[{repopts,opts},EventSpecifications]
]
}
]; 


(* ::Input::Initialization:: *)
RepeatPulseSequence/:Expand[reppseq_RepeatPulseSequence,opts___Rule]:=EventSpecifications[reppseq,opts][[2,1]];


(* ::Input::Initialization:: *)
Options[PulseSequence]={NutationFrequency->Automatic,PulseDuration->Automatic,AmplitudeFactor->1,PhaseShift->0};


(* ::Input::Initialization:: *)
PulseSequence[args___]/;!FreeQ[{args},$Failed]:=$Failed;


(* ::Input::Initialization:: *)
HoldPattern@PulseSequence[arg:Except[_?BooleanQ|{_?BooleanQ,___}|_HoldPattern],moreargs___,opts___Rule]:=PulseSequence[False,arg,moreargs,opts];


(* ::Input::Initialization:: *)
StatusDimension[PulseSequence]=3;


(* ::Input::Initialization:: *)
PulseSequence[False,args:(Except[_?BooleanQ|_Rule|{_?BooleanQ,___}]..),opts___Rule]:=PulseSequence[Evaluate@Table[False,{StatusDimension[PulseSequence]}],args,opts];


(* ::Input::Initialization:: *)
PulseSequence[{True..},args___,opts___Rule]:=PulseSequence[True,args,opts];


(* ::Input::Initialization:: *)
PulseSequence[st:False|{_?BooleanQ..},els_,opts___Rule]:=
PulseSequence[st,Automatic,els,opts];


(* ::Input::Initialization:: *)
PulseSequence[st:False|{_?BooleanQ..},spins_,els_,opts___Rule]:=
PulseSequence[st,spins,Automatic,els,opts];


(* ::Input::Initialization:: *)
PulseSequence[st:False|{_?BooleanQ..},spins_,\[Tau]:Except[_List],el:PulseSequenceElementPattern,opts___Rule]:=PulseSequence[st,spins,\[Tau],{el},opts];


(* ::Input::Initialization:: *)
PulseSequence[st:False|{_?BooleanQ..},spins_,\[Tau]:Except[_List],el:Except[_List|_Rule],opts___Rule]/;!MatchQ[el,PulseSequenceElementPattern]:=(Message[PulseSequence::badels,{el}];$Failed);


(* ::Input::Initialization:: *)
PulseSequence[st:False|{_?BooleanQ..},spins_,\[Tau]:Except[_List],{els1___,{els2:PulseSequenceElementPattern..,els2opts___Rule},els3___},opts___Rule]:=PulseSequence[st,spins,\[Tau],{els1,PulseSequence[{els2},els2opts],els3},opts];


(* ::Input::Initialization:: *)
PulseSequence[st:False|{_?BooleanQ..},spins_,\[Tau]:Except[_List],els_List,opts___Rule]/;!MatchQ[els,{PulseSequenceElementPattern..,___Rule}]:=
(Message[PulseSequence::badels,Cases[els,Except[PulseSequenceElementPattern],{1}]];$Failed);


(* ::Input::Initialization:: *)
PulseSequence[
st:False|{_?BooleanQ..},
All,
\[Tau]:Except[_List],
elements:{pseqels:PulseSequenceElementPattern..,___Rule},opts___Rule]:=
PulseSequence[
st,
First/@SpinSystem[],
\[Tau],
elements,opts];


(* ::Input::Initialization:: *)
PulseSequence[
st:False|{_?BooleanQ..},
spin:Except[All|Automatic|_List],
\[Tau]:Except[_List],
elements:{pseqels:PulseSequenceElementPattern..,___Rule},opts___Rule]:=
PulseSequence[
st,
{spin},
\[Tau],
elements,opts];


(* ::Input::Initialization:: *)
PulseSequence[
st:False|{_?BooleanQ..},
spins_List,
\[Tau]:Except[_List],
elements:{pseqels:PulseSequenceElementPattern..,___Rule},opts___Rule]:=
Module[{spinsets},(
PulseSequence[st,spins,\[Tau],
Replace[
elements,
{
Pulse[Automatic,specs_,elopts___Rule]:>Pulse[spins,specs,elopts],
ShapedPulse[Automatic,dur_,specs_,elopts___Rule]:>ShapedPulse[spins,dur,specs,elopts],
HoldPattern@PulseSequence[status_,Automatic,dur_,more__,pseqopts___Rule]:>
PulseSequence[False,spins,Automatic,more,pseqopts]
},
1],
opts]
)/;(
spinsets=InvolvedSpins/@{pseqels};
!FreeQ[spinsets,Automatic]
)]


(* ::Input::Initialization:: *)
PulseSequence[
st:False|{_?BooleanQ..},
Automatic,
\[Tau]:Except[_List],
elements:{pseqels:PulseSequenceElementPattern..,___Rule},opts___Rule]:=
Module[{spinsets},(
PulseSequence[st,Union@@spinsets,\[Tau],elements,opts]
)/;(
spinsets=InvolvedSpins/@{pseqels};
FreeQ[spinsets,Automatic]&&MatchQ[spinsets,{_List...}]
)];


(* ::Input::Initialization:: *)
PulseSequence[
st:False|{_?BooleanQ..},
pseqspins_List,
\[Tau]:Except[_List],
elements:{pseqels:PulseSequenceElementPattern..,___Rule},opts___Rule]:=
Module[{spinsets,elspins},(
Message[PulseSequence::inconsistspins,Complement[elspins,pseqspins],pseqspins];
PulseSequence[
st,Automatic,\[Tau],
elements,
opts]
)/;(
spinsets=InvolvedSpins/@{pseqels};
MatchQ[spinsets,{_List..}]&&
(elspins=Union@@spinsets;
!SubsetQ[pseqspins,elspins]
)
)];


(* ::Input::Initialization:: *)
PulseSequence[
st:False|{_?BooleanQ..},
spins_List,\[Tau]_,elements:{PulseSequenceElementPattern..,___Rule},opts___Rule]/;!ValidSpinQ[spins,SpinSystem[]]:=(Message[PulseSequence::invalspins,spins];$Failed);


(* ::Input::Initialization:: *)
PulseSequence[
HoldPattern[st:{True,True,False,morest___}],
spins:(_List|Automatic),
Automatic,
elements:{PulseSequenceElementPattern..,___Rule},
opts___Rule
]:=
PulseSequence[{True,True,True,morest},spins,Plus@@(Duration/@elements),elements,opts];


(* ::Input::Initialization:: *)
PulseSequence[
HoldPattern[st:{True,True,False,morest___}],
spins_,
\[Tau]:Except[Automatic],elements:{PulseSequenceElementPattern..,___Rule},
opts___Rule]:=
If[(Chop[Duration[elements]-\[Tau]]==0),
PulseSequence[{True,True,True,morest},spins,\[Tau],elements,opts],
(Message[PulseSequence::incons\[Tau]];$Failed)
];


(* ::Input::Initialization:: *)
PulseSequence[st:{False,morest___},spins_,\[Tau]_,{els:PulseSequenceElementPattern..,elsopts___Rule},opts___Rule]:=PulseSequence[{True,morest},spins,\[Tau],{els,elsopts}];


(* ::Input::Initialization:: *)
PulseSequence[st:{False,morest___},spins_,\[Tau]_,{els:PulseSequenceElementPattern..,elsopts___Rule},opts__Rule]:=
PulseSequence[
st,
spins,\[Tau],
{els}/.{
HoldPattern@PulseSequence[innerst_,innerspins_,inner\[Tau]_,innerargs:(Except[_Rule]...),inneropts___Rule]:>
PulseSequence[False,innerspins,Automatic,innerargs,
FilterPulseSequenceElementOptions[PulseSequence][inneropts,elsopts,opts]],
(type:(Alternatives@@PulseSequenceElementTypes))[args:Except[_Rule]..,argopts___Rule]:>
type[args,
FilterPulseSequenceElementOptions[type][argopts,elsopts,opts]
]
}
];


(* ::Input::Initialization:: *)
PulseSequence[
HoldPattern[st:{optst_,False,morest___}],
spins_,\[Tau]_,
(elements:{els:PulseSequenceElementPattern..,___Rule}),
opts___Rule]/;FreeQ[{els},HoldPattern[Delay[{Automatic,_},___]|PulseSequence[_,_,Automatic,___]],{1}]:=
PulseSequence[{optst,True,morest},spins,\[Tau],elements,opts];


(* ::Input::Initialization:: *)
PulseSequence[
HoldPattern[st:{optst_,False,morest___}],
spins_,Automatic,
(elements:{els:PulseSequenceElementPattern..,___Rule}),
opts___Rule]/;!FreeQ[{els},HoldPattern@Delay[{Automatic,_},___]&&!FreeQ[{els},HoldPattern@PulseSequence[_,_,Automatic,___]],{1}]:=
(Message[PulseSequence::flexdandps];$Failed); 


(* ::Input::Initialization:: *)
PulseSequence[
HoldPattern[st:{optst_,False,morest___}],
spins_,
\[Tau]:Except[Automatic],
{els:PulseSequenceElementPattern..,___Rule},opts___Rule]/;!FreeQ[{els},HoldPattern@Delay[{Automatic,_},___],{1}]:=
Module[{elements,xtot,flexdels,nonflexels,flex\[Tau]},(
elements={els};
flexdels=Cases[elements,HoldPattern@Delay[{Automatic,_},___],{1}];
nonflexels=Complement[elements,flexdels];
flex\[Tau]=\[Tau]-Duration[nonflexels];
xtot=Plus@@(Part[#,1,2]&/@flexdels);
If[
TrueQ[(flex\[Tau]<0)||(flex\[Tau]>\[Tau])],
	(Message[PulseSequence::negflex\[Tau]];$Failed),
PulseSequence[
{optst,True,morest},
spins,\[Tau],
Replace[
elements,
Delay[{Automatic,x_},evgen_,dopts___Rule]:>Delay[flex\[Tau]*(x/xtot),evgen,dopts],
{1}
],
opts
]
]
)];


(* ::Input::Initialization:: *)
PulseSequence[
HoldPattern[st:{optst_,False,morest___}],
spins_,
\[Tau]:Except[Automatic],
{els:PulseSequenceElementPattern..,___Rule},opts___Rule]/;!FreeQ[{els},HoldPattern@PulseSequence[_,_,Automatic,___]]:=
Module[{elements,flexpseqs,nflexpseqs,nonflexels,flex\[Tau]},(
elements={els};
flexpseqs=Cases[elements,HoldPattern@PulseSequence[_,_,Automatic,___],{1}];
nflexpseqs=Length[flexpseqs];
nonflexels=Complement[elements,flexpseqs];
flex\[Tau]=\[Tau]-Duration[nonflexels];
If[
TrueQ[(flex\[Tau]<0)||(flex\[Tau]>\[Tau])],
	(Message[PulseSequence::negflex\[Tau]];$Failed),
PulseSequence[
{optst,True,morest},
spins,\[Tau],
Replace[
elements,
HoldPattern@PulseSequence[st$_,spins$_,Automatic,more$___]:>PulseSequence[False,spins,flex\[Tau]/nflexpseqs,more$],
{1}
],
opts
]
]
)];


(* ::Input::Initialization:: *)
PulseSequence/:
InvolvedSpins[
PulseSequence[True,spins_,\[Tau]:Except[_List],{els:PulseSequenceElementPattern..,elsopts___Rule},opts___Rule]]:=spins;


(* ::Input::Initialization:: *)
PulseSequence/:
Duration[
PulseSequence[True,spins_,\[Tau]:Except[_List],{els:PulseSequenceElementPattern..,elsopts___Rule},opts___Rule]]:=\[Tau];


(* ::Input::Initialization:: *)
PulseSequence/:StandardizeEventSpecification[
HoldPattern@PulseSequence[_,_,Automatic,___],
opts___Rule]:=(Message[PulseSequence::autodur];$Failed);


(* ::Input::Initialization:: *)
PulseSequence/:StandardizeEventSpecification[
HoldPattern@PulseSequence[Except[True],___],
opts___Rule]:=(Message[PulseSequence::notready];$Failed);


(* ::Input::Initialization:: *)
PulseSequence/:StandardizeEventSpecification[
PulseSequence[True,spins_,\[Tau]:Except[Automatic],elements:{els:PulseSequenceElementPattern..,elopts___Rule},
pseqopts___Rule
],
opts___Rule]:=
EventSpecifications[
StandardizeEventSpecification[#,SimplifyPulseSequenceElementRules[elopts,pseqopts,opts]]&/@{els},
Sequence@@FilterRules[{Chronology->"LeftToRight",elopts,pseqopts,opts},Options[EventSpecifications]]
];


(* ::Input::Initialization:: *)
PulseSequence/:Expand[pseq_PulseSequence,opts___Rule]:=EventSpecifications[pseq,opts][[2]];


(* ::Input::Initialization:: *)
PulseSequence::invalspins="One or more spins `1` is invalid for the current spin system.";


(* ::Input::Initialization:: *)
PulseSequence::no\[Tau]="A PulseSequence containing a Delay[{Automatic,..}..] argument requires an explicit duration.";


(* ::Input::Initialization:: *)
PulseSequence::incons\[Tau]="The PulseSequence duration is inconsistent with the set of pulse sequence elements.";


(* ::Input::Initialization:: *)
PulseSequence::negflex\[Tau]="The flexible objects cannot be accommodated within the PulseSequence without generating negative intervals.";


(* ::Input::Initialization:: *)
PulseSequence::badels="The following elements are inappropriate for PulseSequence: <`1`>";


(* ::Input::Initialization:: *)
PulseSequence::flexdandps="A PulseSequence cannot contain both flexible Delay and flexible PulseSequence objects.";


(* ::Input::Initialization:: *)
PulseSequence::notready="The PulseSequence is not ready for interpretation.";


(* ::Input::Initialization:: *)
PulseSequence::autodur="A PulseSequence with an Automatic duration is not ready for interpretation.";


(* ::Input::Initialization:: *)
PulseSequence::inconsistspins="An inconsistency has been detected between the spins defined in the PulseSequence and the spins employed in the pulse sequence elements. The spins `1` contained in the PulseSequence elements are not included in the PulseSequence spins `2`. The inconsistency has been corrected.";


(* ::Input::Initialization:: *)
End[];
EndPackage[];
